### ISSUE TITLE
XepAllErrorsAsWarnings does not find all bugs in one pass

### ISSUE THREAD

**Issue by pcurrivan** [google/error-prone#1024]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?
2.3.1

### Does this issue reproduce with the latest release?
Yes

### What did you do?
When adding ErrorProne to a large existing project, it found many warnings and some errors.  Understandably, it causes compilation to fail once it finds any errors in a file.  I enabled the XepAllErrorsAsWarnings option so I could see the complete list of bugs.

### What did you expect to see?
I expected the option XepAllErrorsAsWarnings to make ErrorProne report all bugs in one pass

### What did you see instead?
Not all bugs were reported.  Some files were seemingly skipped (although ErrorProne - or maybe Plexus compiler - did log a message saying it had parsed the file).  I had the exact same function in several files, and yet only one of these produced a (StreamResourceLeak) warning.  After disabling each reported bug one-by-one using Xep:PatternName:OFF options, a new set of bugs were reported.

**Comment by Stephan202** [comment]
Could it be that the code produces more warnings than are emitted by `javac` by default? If so, you could [increase](https://stackoverflow.com/questions/3115537/java-compilation-errors-limited-to-100) that limit by specifying `-Xmaxwarns`.

**Comment by pcurrivan** [comment]
Thanks, Stephan, that explains it.  Not a problem with ErrorProne.
