### ISSUE TITLE
[ResultOfMethodCallIgnored] False Positive using AssertJ.isThrownBy

### ISSUE THREAD

**Issue by amarocco** [google/error-prone#1028]
Hello,

I encountered some issue with ErrorProne 2.3.1 and AssertJ 3.9.0
I have a Test that check Exception is well raised using AssertJ's Assertions.assertThatExceptionOfType().isThrownBy() and compilation failed due to errorProne and rule ResultOfMethodCallIgnored

Please look at the following repository for reproduce :
https://github.com/amarocco/error-prone-issue

**Comment by nglorioso** [comment]
Thanks for the detailed repro! You should see this in the next snapshot release or released version.

**Comment by amarocco** [comment]
Ok many thanks
