### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by minhodang** [google/error-prone#1051]
I understand error-prone as the project that informs the web page having bug pattern information related to the error if there is an error in the code when building code with a build tool such as maven

So I expected DivZero bug pattern and compiled the code, but the results were different than I expected.

I am wondering if what I understand is correct, and whether this program is used in this way.

![default](https://user-images.githubusercontent.com/38343803/41095904-830071ec-6a42-11e8-9082-39b298255ac6.jpg)
![pom](https://user-images.githubusercontent.com/38343803/41095911-85f85f36-6a42-11e8-971e-079f778f99bd.jpg)

**Comment by Stephan202** [comment]
@minhodang Error Prone should work when running the build using Maven (e.g. `mvn clean install` on the command line), but it won't be activated while working in Eclipse.

**Comment by eaftan** [comment]
That's correct, Error Prone works as part of the build and not inside Eclipse, which has its own compiler.

**Comment by minhodang** [comment]
thank.
