### ISSUE TITLE
AssertionFailureIgnored recommends to use a method that does not exist

### ISSUE THREAD

**Issue by iemejia** [google/error-prone#1059]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?
latest

### Does this issue reproduce with the latest release?
yes

### What did you do?
A warning is reported that directs me to this documentation
http://errorprone.info/bugpattern/AssertionFailureIgnored

### What did you expect to see?
A way to solve the issue out of the box

### What did you see instead?
The documentation suggests to use Assert.assertThrows that is a method that does not exist in Junit 4.

**Comment by cushon** [comment]
`assertThrows` is available in JUnit 5, and will be included in 4.13 once it's released.

Until then, you can disable the check by passing `-Xep: AssertionFailureIgnored:OFF`.

**Comment by iemejia** [comment]
Mmm I see, but well 97% of the Java projects still use Junit 4, and given that the last release of Junit 4 was in 2014 and that [there is not even an ETA for the next release](https://github.com/junit-team/junit4/issues/1496) probably is a better idea to clarify this in the docs don't you think?, and even better to propose a backwards compatible recommendation.

**Comment by cushon** [comment]
JUnit 4.13 has been released

**Comment by cushon** [comment]
JUnit 4.13 has been released!

**Comment by iemejia** [comment]
Thanks for the info @cushon
