### ISSUE TITLE
non-guava suggestion for printing stack trace?

### ISSUE THREAD

**Issue by techieshark** [google/error-prone#1064]
### What version of Error Prone are you using?
2.3.1

### Does this issue reproduce with the latest release?
Yes

### What did you do?

Run Error Prone on some code which calls toString on an array like `e.getStackTrace().toString()`:

```
put(e.getStackTrace().toString());
```

### What did you expect to see?

A suggestion to fix via standard Java, like:

```
Did you mean 'put("StackTrace", Arrays.toString(e.getStackTrace()));'
```

### What did you see instead?

A suggested fix which assumes the use of [guava](https://google.github.io/guava/releases/21.0/api/docs/com/google/common/base/Throwables.html):

```
Did you mean 'put("StackTrace", Throwables.getStackTraceAsString(e));'
```

**Comment by cushon** [comment]
If you're unable to use guava there are some other ideas here: https://stackoverflow.com/questions/1149703/how-can-i-convert-a-stack-trace-to-a-string
