### ISSUE TITLE
Refaster docs on the web site are out-of-date

### ISSUE THREAD

**Issue by dmitry-timofeev** [google/error-prone#1078]
Hi,
"Running the Refaster refactoring" section of the Refaster documentation page is out of date, 
the instructions no longer work with 2.3.1: https://errorprone.info/docs/refaster

Would it be possible to update them, or add a link to https://github.com/google/error-prone/tree/master/examples/refaster if the latter page is supposed to contain an up-to-date example?

Thanks!

**Comment by cushon** [comment]
Thanks, I pushed an update to https://errorprone.info/docs/refaster in 0ede1de0a59a6c782a242ca85981b8b71c92f944. Please re-open or file additional bugs if you run into any issues with the updated instructions.

**Comment by dmitry-timofeev** [comment]
Brilliant, thank you!
