### ISSUE TITLE
Exception when compiling with -PWithErrorProne

### ISSUE THREAD

**Issue by mdelolmo** [google/error-prone#1080]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?
error-prone version: 2.3.1

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Run `./gradlew -PWithErrorProne :mymodule:compileDebugJavaWithJavac --continue`

### What did you expect to see?
No errors

### What did you see instead?
/project/apps/SomeClass.java:41: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
                    return mPageFactory.createPage(pageModel);
                    ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.3.1
     BugPattern: FutureReturnValueIgnored
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.episodes.ListViewBinder not found

Note: `Future` is not used in the failing module

**Comment by cushon** [comment]
That indicates that `com.episodes.ListViewBinder` is referenced transitively by that expression, and that the dependency is not on the classpath. Is the build missing a dependency?

**Comment by msridhar** [comment]
We've run into this kind of issue before.  Even though the Gradle build succeeds, I think you're getting lucky that `javac` happens to not look up what interfaces are implemented by the other class in module B.  AFAIK it's not specified anywhere that compilation will succeed without `com.episodes.ListViewBinder` in the classpath, it's just an implementation detail of `javac`.

That said, we've also noticed that the `FutureReturnValueIgnored` check is often guilty of exposing such missing classpath dependencies and causing `Symbol$CompletionFailure` errors.  I wonder if it could be rewritten in some way to not do supertype lookups so aggressively.

**Comment by cushon** [comment]
I recently made some changes to `FutureReturnValueIgnored` that might help on this front: bd99432f1f1ce9b27f4e8d4aded7500c71bd6158.

> I think you're getting lucky that javac happens to not look up what interfaces are implemented by the other class in module B

Right, javac does its best to be lazy and avoid reading classes it doesn't need to, but the exact list of classes it doesn't need to read is just an implementation detail that has changed between releases. There are certain error prone checks that tend to need slightly more/different information than a regular compilation. So it's hard to completely avoid this issue, and usually it indicates that there are some under-declared dependencies.
