### ISSUE TITLE
Illegal Access Error

### ISSUE THREAD

**Issue by zsweigart** [google/error-prone#1114]
### What version of Error Prone are you using?
2.1.3

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I am incorporating null away and error prone into my app and have added the following to my top-level build.gradle

```
    buildscript {
        repositories {
            google()
            maven { url 'https://plugins.gradle.org/m2/' }
            ...
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.1.2'
            classpath "net.ltgt.gradle:gradle-errorprone-plugin:0.0.16"
        }
    }
    
    subprojects {
        apply from: rootProject.file("gradle/nullaway.gradle")
    }
    ...
```

then in the `nullaway.gradle` file I have 

```
    buildscript {
        repositories {
            maven {
                url "https://plugins.gradle.org/m2/"
            }
        }
    }
    
    apply plugin: 'net.ltgt.errorprone'
    
    if (this.name == 'javalib1' || this.name == 'javalib2') {
        apply plugin: 'java-library'
    
        dependencies {
            annotationProcessor deps.thirdparty.nullaway
    
            errorprone deps.thirdparty.error_prone
        }
    } else {
        if (this.name == 'app') {
            apply plugin: 'com.android.application'
        } else {
            apply plugin: 'com.android.library'
        }
    
        dependencies {
            annotationProcessor deps.thirdparty.nullaway
    
            errorprone deps.thirdparty.error_prone
        }
    }
    
    tasks.withType(JavaCompile) {
        if (!name.toLowerCase().contains("test")) {
            options.compilerArgs += [
                    "-Xep:NullAway:WARN",
                    "-XepOpt:NullAway:AnnotatedPackages=com.mypackage",
                    "-Xep:RestrictTo:WARN",
                    "-XepExcludedPaths:.*/build/generated/.*"]
        }
    }
```

With this setup whenever I try to build my app I get an exception 

> Caused by: java.lang.IllegalAccessError: tried to access class com.google.common.graph.BaseGraph from class com.google.common.graph.Traverser
>     	at com.google.common.graph.Traverser.forTree(Traverser.java:134)
>     	at dagger.internal.codegen.ValidationReport.<clinit>(ValidationReport.java:63)
>     	at dagger.internal.codegen.InjectValidator.validateMembersInjectionType(InjectValidator.java:257)
>     	at dagger.internal.codegen.InjectBindingRegistryImpl.tryRegisterMembersInjectedType(InjectBindingRegistryImpl.java:269)
>     	at dagger.internal.codegen.InjectBindingRegistryImpl.tryRegisterMembersInjectedType(InjectBindingRegistryImpl.java:253)
>     	at dagger.internal.codegen.InjectProcessingStep$1.visitVariableAsField(InjectProcessingStep.java:67)
>     	at dagger.internal.codegen.InjectProcessingStep$1.visitVariableAsField(InjectProcessingStep.java:57)
>     	at com.sun.tools.javac.code.Symbol$VarSymbol.accept(Symbol.java:1550)
>     	at dagger.internal.codegen.InjectProcessingStep.process(InjectProcessingStep.java:56)
>     	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
>     	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)

I check the notes and I am using dagger version 2.16 and as you can see I have the exclude for `build/generated` files.  

### What did you expect to see?
I expected the build to work

### What did you see instead?
Full Stack Trace

> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':CoffeeMeetsBagel:compileRegularSuperuserJavaWithJavac'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
>         at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
>         at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
>         at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
>         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
>         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
>         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
> Caused by: org.gradle.internal.UncheckedException: java.lang.reflect.InvocationTargetException
>         at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
>         at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
>         at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:76)
>         at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:25)
>         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
>         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
>         at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
>         at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
>         at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
>         at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringDecorator.execute(IncrementalResultStoringDecorator.java:44)
>         at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringDecorator.execute(IncrementalResultStoringDecorator.java:28)
>         at org.gradle.api.internal.tasks.compile.incremental.IncrementalAnnotationProcessingCompiler.execute(IncrementalAnnotationProcessingCompiler.java:50)
>         at org.gradle.api.internal.tasks.compile.incremental.IncrementalAnnotationProcessingCompiler.execute(IncrementalAnnotationProcessingCompiler.java:36)
>         at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:156)
>         at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:126)
>         at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:115)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
>         at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
>         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
>         ... 29 more
> Caused by: java.lang.reflect.InvocationTargetException
>         at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:73)
>         ... 54 more
> Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access class com.google.common.graph.BaseGraph from class com.google.common.graph.Traverser
>         at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
>         at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
>         at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
>         at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:137)
>         at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
>         at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:118)
>         at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:65)
>         ... 55 more
> Caused by: java.lang.IllegalAccessError: tried to access class com.google.common.graph.BaseGraph from class com.google.common.graph.Traverser
>         at com.google.common.graph.Traverser.forTree(Traverser.java:134)
>         at dagger.internal.codegen.ValidationReport.<clinit>(ValidationReport.java:63)
>         at dagger.internal.codegen.InjectValidator.validateMembersInjectionType(InjectValidator.java:257)
>         at dagger.internal.codegen.InjectBindingRegistryImpl.tryRegisterMembersInjectedType(InjectBindingRegistryImpl.java:269)
>         at dagger.internal.codegen.InjectBindingRegistryImpl.tryRegisterMembersInjectedType(InjectBindingRegistryImpl.java:253)
>         at dagger.internal.codegen.InjectProcessingStep$1.visitVariableAsField(InjectProcessingStep.java:67)
>         at dagger.internal.codegen.InjectProcessingStep$1.visitVariableAsField(InjectProcessingStep.java:57)
>         at com.sun.tools.javac.code.Symbol$VarSymbol.accept(Symbol.java:1550)
>         at dagger.internal.codegen.InjectProcessingStep.process(InjectProcessingStep.java:56)
>         at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
>         at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1204)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1313)
>         at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1267)
>         at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:943)
>         at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
>         at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
>         ... 61 more

**Comment by jsarma** [comment]
Why was this closed? I'm getting a similar error with java8 and intellij.
