### ISSUE TITLE
Debugging error-prone checks 

### ISSUE THREAD

**Issue by oferb** [google/error-prone#1123]
### What version of Error Prone are you using?
I'm using it as part of Bazel:
```
Build label: 0.17.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Sep 14 10:39:25 2018 (1536921565)
Build timestamp: 1536921565
Build timestamp as int: 1536921565
```

### Does this issue reproduce with the latest release?
Don't know.

### What did you do?
Try to debug a custom check by adding a `System.out.println()`:
https://github.com/google/startup-os/tree/master/examples/errorprone

### What did you expect to see?
The printout :)

### What did you see instead?
`Did you try to print something to stdout? Workers aren't allowed to do this, as it breaks the protocol between Bazel and the worker process.`

What is the recommended way to debug error-prone checks?

**Comment by cushon** [comment]
Can you try passing `--strategy=Javac=standalone` to Bazel? That should disable the feature that's complaining when you print to stdout.

**Comment by oferb** [comment]
It works! Thanks!
