### ISSUE TITLE
please release 2.3.2 to maven

### ISSUE THREAD

**Issue by Dieken** [google/error-prone#1127]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?

2.3.1

### Does this issue reproduce with the latest release?

yes

### What did you do?

I got same issue with #1091 whose fix is not released yet.  Maven doesn't download SNAPSHOT artifacts by default and I would like to keep this behaviour for stable dependencies.

Could you release 2.3.2 soon? JDK 11 is released yesterday.

**Comment by eaftan** [comment]
We'll try to get this out, say by end of next week.

**Comment by AustinShalit** [comment]
Folks, Any updates on this?

**Comment by eaftan** [comment]
We're still working on it, sorry for the delay.

**Comment by mernst** [comment]
I still don't see 2.3.2 in either of these locations:
https://jcenter.bintray.com/com/google/errorprone/error_prone_ant/
https://repo1.maven.org/maven2/com/google/errorprone/error_prone_ant/
Has 2.3.2 been released to Bintray or Maven Central yet?

**Comment by cushon** [comment]
The ant plugin doesn't exist anymore: 3f2ca43e53266e84e17e4fb3f34888be5cb29293. The [ant installation instructions](http://errorprone.info/docs/installation#ant) have been updated to recommend the `-Xplugin` integration instead.

The replacement for the error_prone_ant jar is: https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.3.2/error_prone_core-2.3.2-with-dependencies.jar

**Comment by mernst** [comment]
Thanks for the quick response!  I see the file there.
I was not trying to use the ant installation instructions, but the Java 8 command line instructions, which still say:
```
wget https://repo1.maven.org/maven2/com/google/errorprone/error_prone_ant/2.3.2/error_prone_ant-2.3.2.jar
```

It would be nice to update those instructions as well.

**Comment by cushon** [comment]
Ah, thanks. Done: https://github.com/google/error-prone/commit/61841e1763581e883187ab6d875bba39cc79f7c3
