### ISSUE TITLE
Exponential performance degradation with `#compilesWithFix`

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#1166]
Consider the following code:
```java
class WithNonFinalFields {
  private String prop1 = null;
  private String prop2 = null;
  private String prop3 = null;
  private String prop4 = null;
  private String prop5 = null;
}
```

Compile the code as follows:
```sh
javac \
  -XDcompilePolicy=simple \
  -processorpath error_prone_core-2.3.2-with-dependencies.jar \
  '-Xplugin:ErrorProne -XepDisableAllChecks -Xep:FieldCanBeFinal:WARN' \
  WithNonFinalFields.java
```

Each field in this class will yield a warning, but the compilation as a whole takes about a minute to complete. Adding a sixth field increases the compilation time to almost 6 (!) minutes, etc.

Running `jstack` while the compilation is ongoing clearly shows what's going on. [This thread dump](https://github.com/google/error-prone/files/2546326/stacktrace.txt) shows that `SuggestedFixes#compilesWithFix` recursively invokes Error Prone. The result is a runtime exponential in the number of violations.

It seems (didn't actually try implementing this yet) that the issue can be resolved simply by pruning the `-Xplugin:ErrorProne` argument from the secondary compilation run. I see only one (minor, IMHO) downside to this approach: it wouldn't flag fixes that _introduce_ another Error Prone violation. That seems like a small price to pay.

NB: This issue relates to #849, which also discusses pruning of the flags passed to the secondary compilation round.

**Comment by cushon** [comment]
can you check if this problem is fixed at head (i.e. by 02cebcd6263d43e7b08b175f2bf1451e8975df52) ?

**Comment by Stephan202** [comment]
Hah, I missed that commit. Will do and report back.

**Comment by Stephan202** [comment]
@cushon I can confirm that this is indeed fixed at HEAD (tested against 406d00ca75f80d395172a20abff9edd14e8a68fd). Expanded the test class to 100 fields; compilation finished in under 7 seconds.

I guess this is the point where I ask... is there a timeline for a 2.3.3 release? :D

**Comment by cushon** [comment]
The next release is scheduled for December.

Are you seeing this affect any non-experimental, enabled-by-default checks?

**Comment by Stephan202** [comment]
Nope, when I disable `FieldCanBeFinal` the compilation of our largest project terminates in "nominal time". For now I'll just this able this check :+1:.
