### ISSUE TITLE
not compatible with hibernate annotation processor

### ISSUE THREAD

**Issue by davidkarlsen** [google/error-prone#1176]
### What version of Error Prone are you using?
2.3.2

### Does this issue reproduce with the latest release?
yes

### What did you do?
Add both:
  <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator-annotation-processor</artifactId>
                <version>6.0.13.Final</version>
and error-prone 2.3.2

### What did you expect to see?
Both plugins working ok

### What did you see instead?

19:52:50 compiler message file broken: key=compiler.misc.msg.bug arguments=11, {1}, {2}, {3}, {4}, {5}, {6}, {7}
19:52:50 java.lang.NoSuchMethodError: com.google.common.base.Verify.verify(ZLjava/lang/String;Ljava/lang/Object;)V
19:52:50 	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:124)
19:52:50 	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
19:52:50 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
19:52:50 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
19:52:50 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
19:52:50 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
19:52:50 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
19:52:50 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
19:52:50 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
19:52:50 	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
19:52:50 	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
19:52:50 	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
19:52:50 	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
19:52:50 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
19:52:50 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
19:52:50 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
19:52:50 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
19:52:50 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
19:52:50 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
19:52:50 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
19:52:50 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
19:52:50 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
19:52:50 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
19:52:50 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
19:52:50 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
19:52:50 	at java.base/java.lang.Thread.run(Thread.java:834)
19:52:50 [INFO] -------------------------------------------------------------
19:52:50 [ERROR] COMPILATION ERROR : 
19:52:50 [INFO] -------------------------------------------------------------
19:52:50 [ERROR] An unknown compilation problem occurred
19:52:50 [INFO] 1 error

Also see https://hibernate.atlassian.net/browse/HV-1664

**Comment by Stephan202** [comment]
Interesting. We have an internal Maven build with those same two annotation processors, but don't observe this issue. Maybe there's a third dependency pulled in somewhere? If not, crazy idea: what if you swap the declaration order of the processors, so that the other one's Guava comes first?

**Comment by davidkarlsen** [comment]
Whee - changing order fixed it!
