### ISSUE TITLE
Broken static pages 

### ISSUE THREAD

**Issue by jaredsburrows** [google/error-prone#1180]
Example URL: 
 - https://errorprone.info/bugpattern/ThreadLocalUsage

Image:
 - <img width="1285" alt="screen shot 2018-11-17 at 12 38 08 pm" src="https://user-images.githubusercontent.com/1739848/48676982-417e9e80-eb23-11e8-970b-5fe77faeb059.png">

**Comment by jaredsburrows** [comment]
Any update on this?

Can we migrate the following:
 - ` ```java {.bad}` -> ` ```java`
 - ` ```java {.good}` -> ` ```java`

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by cpovirk** [comment]
I recall a commit to fix this, and I no longer see `{.bad}` and `{.good}`, so I think it's fixed. Are you seeing any remaining problems?

**Comment by jaredsburrows** [comment]
You are right. Closing, this is fixed here: https://github.com/google/error-prone/commit/e43a577723a52de9d000f18b553bc55616d9e5df.
