### ISSUE TITLE
installation instructions with maven incomplete

### ISSUE THREAD

**Issue by davidmoten** [google/error-prone#1184]
Docs at https://errorprone.info/docs/installation are incomplete with regards to using error-prone with Maven with JDK 8 support. 

In particular, please specify that this property needs to be set in the pom:

```xml
<javac.version>9+181-r4173-1</javac.version>
```
Without that the compile fails with no useful diagnostics at all (and wasted my time for a while).

BTW that no diagnostics appeared may be another issue to chase if anyone is interested.

**Comment by AMalahov** [comment]
This is especially confusing for ones like me, who has little experience with maven in general, because `javac.version` looks like some predefined property. Would be a bit clearer if it was named something like `<error-prone.javac-version>9+181-r4173-1</error-prone.javac-version>`

**Comment by cushon** [comment]
Thanks for the suggestion, I updated the example to set the property.
