### ISSUE TITLE
error_prone_ant is missing for 2.3.2

### ISSUE THREAD

**Issue by richharms** [google/error-prone#1194]
### Description of the problem / feature request:

When attempting to update to 2.3.2, I noticed that error_prone_ant has not been made available for 2.3.2:

https://search.maven.org/classic/#search%7Cga%7C1%7Ca%3A%22error_prone_ant%22

I use Apache Ivy to pull down dependencies for a project, and there is definitely value to having this variation of Error Prone available.

### What version of Error Prone are you using?

Attempting to use error_prone_ant 2.3.2.

###  Have you found anything relevant by searching the web?

No.

**Comment by cushon** [comment]
there's some information on the change here: https://github.com/google/error-prone/issues/1127#issuecomment-436854432

**Comment by richharms** [comment]
Thank you!
