### ISSUE TITLE
Cannot build Errorprone plugin with Jigsaw

### ISSUE THREAD

**Issue by KengoTODA** [google/error-prone#1210]
### Description of the problem / feature request:

When I build [my Errorprone plugin](https://github.com/KengoTODA/errorprone-slf4j) with `module-info.java`, I found that Errorprone plugin API has not support Jigsaw yet. To migrate tech stack from old Java 8 to latest LTS Java 11, I want to request to support Jigsaw. Here is detailed description:

1. I need to add both of `requires error.prone.check.api;` and `requires error.prone.annotation;` in `module-info.java` because Errorprone plugin needs to depend on both of [error_prone_check_api](https://mvnrepository.com/artifact/com.google.errorprone/error_prone_check_api/2.3.2) and [error_prone_annotation](https://mvnrepository.com/artifact/com.google.errorprone/error_prone_annotation/2.3.2). But both of them provides the package `com.google.errorprone` so my build fails with following error messages:

> [ERROR] the unnamed module reads package com.google.errorprone from both error.prone.check.api and error.prone.annotation
> [ERROR] module error.prone.check.api reads package com.google.errorprone from both error.prone.check.api and error.prone.annotation
> [ERROR] module com.google.common reads package com.google.errorprone from both error.prone.check.api and error.prone.annotation
> [ERROR] module auto.service reads package com.google.errorprone from both error.prone.check.api and error.prone.annotation
> [ERROR] module error.prone.annotation reads package com.google.errorprone from both error.prone.check.api and error.prone.annotation

Major problem is that, both of check_api and annotation uses `com.google.errorprone` package to provide API. It may require us to change package of each API, because Jigsaw requests us to make sure that the package is provided by only one module.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Simply clone my GitHub repo, and switch to [e15b478a](https://github.com/KengoTODA/errorprone-slf4j/commit/e15b478a30f8a80012120c163b0590e48d54e529) then `mvn clean verify` will reproduce this issue. Make sure you have JDK9 on `JAVA_HOME`.

### What version of Error Prone are you using?

2.3.2

###  Have you found anything relevant by searching the web?

I searched both of ML and Issues, however I found nothing related with this topic. There are several questions from Errorprone users, but no question from Errorprone plugin developers.

**Comment by sgammon** [comment]
@cushon Also this one
