### ISSUE TITLE
UnusedVariable and UnusedMethod false positives with Java EE

### ISSUE THREAD

**Issue by codylerum** [google/error-prone#1235]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> UnusedVariable causes false positives for private fields annotated with Java EE annotations.

javax.enterprise.inject.Produces

Also Unused method for

javax.annotation.PreDestroy
javax.annotation.PostConstruct

### Feature requests: what underlying problem are you trying to solve with this feature?

> Correct false positives

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Class with private class variable having any of the referenced annotations

### What version of Error Prone are you using?

>2.3.3

###  Have you found anything relevant by searching the web?

> No
>
> Places to look:
> - GitHub issues: https://github.com/google/error-prone/issues
> - email threads on https://groups.google.com/forum/#!forum/error-prone-discuss

**Comment by lgemeinhardt** [comment]
Similar issue with TestNG annotations (https://testng.org/doc/documentation-main.html#annotations), because they work for private methods too!

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/c619de8f9934a2f0c947c07a0a3383a318549c30
