### ISSUE TITLE
URL outdated / don't know new location

### ISSUE THREAD

**Issue by LorenzNickel** [google/error-prone#1241]
[This URL](http://code.google.com/searchframe#Fccnll6ERQ0/trunk/findbugs/src/java/edu/umd/cs/findbugs/ba/CheckReturnAnnotationDatabase.java) is outdated and I don't know if and where this can be found now. If somebody tells me, how this should be handled (new url, remove url, remove parts of the comment), I can create a PR or somebody else fixes it himself.

https://github.com/google/error-prone/blob/61cb540c08ec63faa56dccce00049cff1f8b41ea/core/src/main/java/com/google/errorprone/bugpatterns/ReturnValueIgnored.java#L54

**Comment by zimmi** [comment]
SpotBugs is the new FindBugs, so I would look here: https://github.com/spotbugs/spotbugs/blob/3883a7b750fb339577be073bc45e36b6f268777b/spotbugs/src/main/java/edu/umd/cs/findbugs/ba/CheckReturnAnnotationDatabase.java

Note that I'm not a maintainer of this project, just a drive by observation.

**Comment by LorenzNickel** [comment]
Looks good, thanks, can someone confirm that this should be the new url?

**Comment by eaftan** [comment]
Yes, that's the current URL.  I'll update the code to point to it as well.
