### ISSUE TITLE
On account of using error-prone in JDK 8

### ISSUE THREAD

**Issue by atulim** [google/error-prone#1245]
Sir, I am trying to configure error-prone for JDK 8. I read your article for JDK 8 support in https://github.com/tbroyer/gradle-errorprone-plugin but can you state in more detail on how to do it.It would be very helpful of you.

**Comment by tbroyer** [comment]
Please file a bug in that project instead, but first, have a look at https://github.com/tbroyer/gradle-apt-plugin/blob/master/build.gradle.kts for an example of use (search for all instances of `errorprone` in that file). If that example and the README aren't enough, I'd be glad to improve the README but you'd have to help me understand what you think is missing or unclear (also look at the closed issues and pull requests, there have already been some discussions on this topic)
