### ISSUE TITLE
DoNotMock removed without notice

### ISSUE THREAD

**Issue by dclements** [google/error-prone#1246]
As part of: https://github.com/google/error-prone/commit/66f4d6ef01a90d7422d2292c8735d4e14375599c#diff-e9fcfd3db76c805219c6849391a9cdcf

`DoNotMock` and `SpyNoMock` were removed.  But there are no notes indicating that this was the case in any of the release notes since this change. 

This means anything that used the public annotation was spontaneously broken when they upgraded.

**Comment by kurtisnelson** [comment]
@cushon can we document the replacement?

**Comment by eaftan** [comment]
Sorry about this.  These were not intended to be external because the enforcement story is more difficult.  I will re-opensource `@DoNotMock`, but I'm less happy with `@SpyNoMock`, and I'm not excited about people using that one.  Do you use both these annotations, or just `@DoNotMock`?

**Comment by kurtisnelson** [comment]
Just DoNotMock. It feels like it should be put over in JSR for anyone to use.
