### ISSUE TITLE
ReturnMissingNullable check is broken in error-prone 2.3.3

### ISSUE THREAD

**Issue by m-titov** [google/error-prone#1248]
### Description of the problem / feature request:
After switching error-prone version from 2.3.2 to 2.3.3 following warning is appearing:

```
[ReturnMissingNullable] May return null
        return Optional.ofNullable(browseItemId)
        ^
    (see https://errorprone.info/bugpattern/ReturnMissingNullable)
  Did you mean '@Nullable public String fetchBrowseItemId(String browseName) {'?
``` 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

just compile following code:

```
public String main() {
        @Nullable String browseItemId = null;

        return Optional.ofNullable(browseItemId)
            .orElseThrow(() -> new IllegalStateException(""));
    }
```

### What version of Error Prone are you using?

2.3.3

###  Have you found anything relevant by searching the web?
no

**Comment by yborovikov** [comment]
The same for returning:
- `com.google.common.base.Preconditions.checkNotNull(...)`
- `java.util.Objects.requireNonNull(...)`

What is the error-prone prone way of checking for `null`s?

**Comment by kevin1e100** [comment]
`ReturnMissingNullable` is based on explicit nullness annotations in source, which means that it'll behave suboptimally on unannotated APIs such as `j.u.Optional` and `j.u.Objects`.  There's no easy way to fix that ATM, and I'd recommend just suppressing warnings resulting from that.  However, it's great to hear about APIs where this is limiting, so thank you for filing this.

Given its current annotations, `com.google.common.base.Verify.verifyNotNull` should work better for null-checking a possibly-`null` value (see issue #1253).

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/c8c034d99b48df0034aad64ea777b480f6c3cbf9
