### ISSUE TITLE
Method matchers do not match method references

### ISSUE THREAD

**Issue by dmdashenkov** [google/error-prone#1283]
### Description of the problem

Method matchers do not match method references.

I have a custom bug checker. The purpose of it is to encourage users to call one method and the other.

Example:
```java
class Builder {
    // ...

    public Result build() {
        // ...
    }

    public Result validateAndBuild() {
        // ...
    }
}
```

I'd like the users to call `validateAndBuild()` instead of `build()` whenever possible. I do not have control over the `Builder` class, thus the need in a custom bug checker.

This is how I match the `build()` method calls:
```java
@Override
public Description matchMethodInvocation(MethodInvocationTree tree, VisitorState state) {
    boolean matches = MethodMatchers.instanceMethod()
                            .onClass(isDescendantOf(Builder.class.getName()))
                            .named("build");
    if (matches) {
        // Collect and return description and fixes.
    } else {
        return NO_MATCH;
    }
}
```

When I try to match simple expressions of the form `builder.build()`, the checker matches it successfully. However, the checker does not match expressions of form `builder::build`.

Also, a simple method call placed into a lambda works fine as well.

### What version of Error Prone are you using?

Error Prone Java libraries of version `2.3.3`.
The Javac tool for testing of version `9+181-r4173-1`.
Error Prone Gradle plugin of version `0.8`.

With that, I'm using Java `1.8.0_121` and Gradle `5.4.1`.

###  Have you found anything relevant by searching the web?

I did not find GitHub issues or mailing threads on this topic. Also, I've checked the `AmbiguousMethodReference` check source code and it seems to have nothing to do with the actual method reference invocations, rather with the method declaration.

I guess, I could write the matching by hand, using only the Javac API. Not sure if that's what I should do, as, probably, I'm not the only user who could find matching method references helpful.

**Comment by tbroyer** [comment]
I think you have to implement `MemberReferenceTreeMatcher` too (see how `DoNotCallChecker` does it for example)

**Comment by dmdashenkov** [comment]
Thanks, this seems to work for me. Seems like this API is dictated by the Javac API, thus I consider the issue resolved.
