### ISSUE TITLE
Extend CompileTimeConstant to (static) fields

### ISSUE THREAD

**Issue by leventov** [google/error-prone#1285]
### Description of the feature request

Allow `@CompileTimeConstant` to annotate fields.

### What underlying problem are you trying to solve with this feature?

On static fields, it means that the field's value is computed as a compile-time constant. This is useful as a self-check in some performance-critical code because accidentally making a static final field not a compile-time constant may break some optimizations, such as replacing integral division with a shift.

On instance fields, this annotation may mean that only compile-time constants are written to the field. I don't know why this may be useful, but it would be consistent with the existing meaning of `@CompileTimeConstant` on method parameters. Alternatively, the annotation may be prohibited on instance fields.

###  Have you found anything relevant by searching the web?

No.

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/121f090aa6388bd6c21d6f6e1c1f09e535512984
