### ISSUE TITLE
Documentation improvement request for TreeToString: provide options.

### ISSUE THREAD

**Issue by lazaroclapp** [google/error-prone#1308]
### Description of the problem / feature request: 

Documentation improvement request: Provide some actionable alternative to suppressions on https://errorprone.info/bugpattern/TreeToString 

Simply pointing out the existence of `VisitorState.getSourceForNode(...)` would be quite helpful.

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently, the entire documentation for this check is "Tree#toString shouldn't be used for Trees deriving from the code being compiled, as it discards whitespace and comments." followed by instructions on how to suppress the check. This is not actionable for most developers writing EP checks (at least not in the case where they do care about whitespace or comments). 

Just pointing out that the `VisitorState.getSourceForNode(...)` could be used instead, should one want a call that preserves whitespace and comments, would probably make that explanation help much more helpful.

### What version of Error Prone are you using?

2.3.3 (but it's irrelevant, public docs seem to be version agnostic)

###  Have you found anything relevant by searching the web?

Found `VisitorState..getSourceForNode(...)`, but it would have been even better if I didn't have to search for it 😄

**Comment by Stephan202** [comment]
Additional caveat: contrary to `.toString()`, `.getSourceForNode(Tree)` may return `null` in some circumstances. So when replacing one for the other, the larger context should be considered, too.

**Comment by lazaroclapp** [comment]
True. Worth having that note in the error page, I think, but still worth pointing to that API. I don't think an autofix here is necessarily a good idea, but I'd have loved to open that link and seen a list of options like: 
a) If you don't care about comments/spacing, simply add a suppression, but 
b) if you need exact source code, use `getSourceForNode(Tree)` (note: this might return `null` when [...])

**Comment by graememorgan** [comment]
If there's a VisitorState in the current scope, we suggest using that: https://github.com/google/error-prone/blob/88cf5c655277f3b301540e1fa8c46d003473fdfb/core/src/main/java/com/google/errorprone/bugpatterns/TreeToString.java#L97

But you're right, the docs could be improved.

**Comment by lazaroclapp** [comment]
> If there's a VisitorState in the current scope, we suggest using that:
> 
> https://github.com/google/error-prone/blob/88cf5c655277f3b301540e1fa8c46d003473fdfb/core/src/main/java/com/google/errorprone/bugpatterns/TreeToString.java#L97
> 
> But you're right, the docs could be improved.

Thanks for the response! And that's useful, for sure, but on the cases I saw (at least on the first target that hit this check) the errors were all inside e.g. private methods which could easily take a VisitorState but didn't currently have one in scope. Mentioning this in the docs would be helpful either way :)
