### ISSUE TITLE
block in JavacFileManager$ArchiveContainer.<init>

### ISSUE THREAD

**Issue by yixiaoerguo** [google/error-prone#1315]
It is likely memory leaks, I scan a project block in [JavacFileManager$ArchiveContainer.<init>] more than one day.  The project just contains 100 files.

![image](https://user-images.githubusercontent.com/5442619/61770829-c93e4a80-ae20-11e9-9587-891353e7bd59.png)

**Comment by cushon** [comment]
Thanks for the report, but there's not much we can do without a repro. Please re-open if you have an example that reproduces the problem.
