### ISSUE TITLE
Contradicting advice about -XDcompilePolicy

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#1322]
If error-prone is used and `-XDcompilePolicy` is not used as command-line argument for `javac`, error-prone throws an exception with the following message

> Exception in thread "main" com.sun.tools.javac.util.PropagatedException: com.google.errorprone.InvalidCommandLineOptionException: The default compilation policy (by-todo) is not supported by Error Prone, pass -XDcompilePolicy=byfile instead

An exception with the same recommendation occurs if an unsupported compile policy is specified.

However, the [installation instructions](https://errorprone.info/docs/installation) specify to pass `-XDcompilePolicy=simple` (for all of the build systems).

Since d4b291e19a40d3292c4fa28ce2fec009363f3e76 error-prone accepts both compile policies, but which one is preferred?

The same compile policy should be suggested by the error message and by the documentation to avoid confusion.

Does https://bugs.openjdk.java.net/browse/JDK-8155674 mean that `byfile` is the better choice? Do these compile policies have any relevant effect for the user? I was not able to find any documentation on them.

**Comment by cushon** [comment]
If you're using the Error Prone javac, it has a fix (https://github.com/google/error-prone-javac/commit/94c6b72ed2f9af2cc2ad0d6a114da2980ec9a975) that isn't currently in the stock OpenJDK javac, but which is discussed in one of the threads link from JDK-8155674.

If you're using a stock OpenJDK javac, `-XDcompilePolicy=simple` is currently a better choice.

**Comment by PhilippWendler** [comment]
Thanks for the clarification! Might be nice for others if the exception message were adjusted, but if you do not think this is important enough feel free to close this issue.

**Comment by cushon** [comment]
We should probably update the message, or document it somewhere outside the issue.

The hope is still to fix the default compilation policy so it works with Error Prone and avoid the need for the error message, but progress on that has obviously been slow.
