### ISSUE TITLE
Add java.time.Clock to "WellKnownMutability" immutable list

### ISSUE THREAD

**Issue by dclements** [google/error-prone#1326]
### Description of the problem / feature request:

Error prone does not recognize java.time.Clock as "well known" immutable: https://github.com/google/error-prone/blob/master/core/src/main/java/com/google/errorprone/bugpatterns/threadsafety/WellKnownMutability.java

This is despite that java.time.Clock implementations are always supposed to be immutable and thread safe: 

> Implementation Requirements:
This abstract class must be implemented with care to ensure other classes operate correctly. All implementations that can be instantiated must be final, immutable and thread-safe.

(source: https://docs.oracle.com/javase/8/docs/api/java/time/Clock.html )

### Feature requests: what underlying problem are you trying to solve with this feature?

A little bit easier to work with injected clocks. 

### What version of Error Prone are you using?

`2.3.3`

###  Have you found anything relevant by searching the web?

Nope.

**Comment by michaelhixson** [comment]
I regularly use a mutable Clock in tests, and this led me to contribute one such implementation ([MutableClock](https://github.com/ThreeTen/threeten-extra/blob/master/src/main/java/org/threeten/extra/MutableClock.java)) to the threeten-extra library.  Searching now, I found a couple of other implementations like this on GitHub ([mock-clock](https://github.com/state-machine-systems/mock-clock), [test-clock](https://github.com/robfletcher/test-clock)).  [Others suggest using mocking libraries](https://stackoverflow.com/questions/27067049/unit-testing-a-class-with-a-java-8-clock) to stub `clock.instant()` to accomplish the same thing, which is being able to supply *one* Clock instance to the production code whose time can be adjusted by the test code.

That said, having Clock on the WellKnownImmutability list may still be more useful than not having it on that list.  I don't know.  I just wanted to point out that Clock is perhaps more likely than other "immutable" interfaces to have contract-breaking, mutable implementations.

**Comment by dclements** [comment]
It's a bit like saying "ConcurrentMap can't be regarded as well known to be thread safe because implementations exist, especially for testing, that deliberately break the contract."

**Comment by cushon** [comment]
42757849a92fb59180e38d3a71c07b2a15020b1c
