### ISSUE TITLE
Improve usability of error prone with respect to showing all errors

### ISSUE THREAD

**Issue by victornoel** [google/error-prone#1341]
### Description of the problem / feature request:

When using error prone, say, with maven, there are two possibilities:
- either showing errors as errors, but then you only get the first error shown at every run
- either showing errors as warnings, but then the build does not fail (adding the `-Werror` flag has the same behaviour as the first point)

In both case, this is not usable as a way to ease the life of developers: one has to run a lot of time error-prone to be sure all errors are covered OR it is easy to miss errors when lots of modules are built (you have to go look in the console output which can be quite big).

I believe something should be done to improve usability of error prone for this use case.

### Feature requests: what underlying problem are you trying to solve with this feature?

Saving my time :)

### What version of Error Prone are you using?

2.3.3

###  Have you found anything relevant by searching the web?

There is an issue about the question of showing all errors (#436, which, IMHO, could have been closed), but I believe it would be best to discuss the need of improving usability in a new issue.

**Comment by tbroyer** [comment]
IMO, this is more a build system or JavaC issue than an Error Prone one (if only because there can be other warnings and errors than those from Error Prone, and Error Prone plugs into JavaC so it might not even have the ability to do that).

When using Maven, you can use [`failOnWarning`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#failOnWarning)

See also https://bugs.openjdk.java.net/browse/JDK-8187591

Fwiw, this was improved (fixed?) in https://github.com/google/error-prone/commit/91a57840f42c887a55ccc38cf1fb6aa4f5f6f111 already (I'll note that the test uses `--should-stop:ifError=LOWER`, as already suggested in the JavaC issue linked above)

**Comment by victornoel** [comment]
@tbroyer very interesting, thanks a lot. I'm going to experiment with this and post a solution here to be able to close this issue then :)

**Comment by victornoel** [comment]
Here are my notes

> When using Maven, you can use failOnWarning

This actually seems to enable `-Werror`, which fails on the first error, so by itself it is not enough.

Then I've tried various combination of
- `-Werror`
- `-XepAllErrorsAsWarnings` or not
- `-XDcompilePolicy=byfile` or `-XDcompilePolicy=simple` (see #1322, not sure which one should be used)
- `--should-stop:ifError=LOWER`, or `--should-stop=ifError=LOWER` (this one seems the correct way of specifying it) or not

By the way, surprisingly, even without `-XepAllErrorsAsWarnings`, error prone errors appear as warnings…

In all cases, the build fails with the first warning, so I'm not sure this is actually fixed nor improved by the commit you reference.
At least we should aim for finding what is the correct setting and improve documentation.

**Comment by victornoel** [comment]
Maybe @cushon you could chip in as you are the author of the aforementioned commit?

**Comment by msridhar** [comment]
For Maven maybe you want to use `--fail-at-end` or `--fail-never`?  http://maven.apache.org/ref/3.6.1/maven-embedder/cli.html  That should at least continue the build for other modules even if you get an Error Prone error on one module.  It does not affect how many errors get reported for a single module though.

**Comment by victornoel** [comment]
@msridhar I don't think those options will help at all with my use case. As you said, they will just continue building other modules even if one fail, but it won't show all the warnings and/or errors for a given module. So it will be even more confusing :)

**Comment by victornoel** [comment]
or maybe @amalloy have an idea? Since you seem to have worked on the same source code :)

**Comment by cpovirk** [comment]
I think this got fixed about a week after the last post here: https://github.com/google/error-prone/issues/436#issuecomment-2256213390.
