### ISSUE TITLE
ReturnValueIgnored - All DateTimeFormatterBuilder methods should be ignored

### ISSUE THREAD

**Issue by pcurrivan** [google/error-prone#1363]
### Description of the problem / feature request:

The ALLOWED_JAVA_TIME_METHODS matcher object currently has exceptions for only the append* methods of DateTimeFormatterBuilder, but all of the methods on that class return "this for chaining" and should be ignored by this rule. (see https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatterBuilder.html)

### What version of Error Prone are you using?

2.3.3

**Comment by kluever** [comment]
Thanks, this looks like a legit report!

**Comment by kluever** [comment]
I'm going to go with:

```
instanceMethod()
    .onExactClass("java.time.format.DateTimeFormatterBuilder")
    .withNameMatching(Pattern.compile("^append.*|^parse.*|^pad.*|^optional.*"))
```
