### ISSUE TITLE
PreferJavaTimeOverload does not play well with AssertJ assertThat

### ISSUE THREAD

**Issue by lgemeinhardt** [google/error-prone#1377]
### Description of the problem / feature request:

PreferJavaTimeOverload does not play well with AssertJ assertThat

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
package sample;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;

public class SampleTest {

	@Test
	public void testSomething() {
		assertThat(1 + 2).isEqualTo(3);
	}

}

```
raises

```
sample\SampleTest.java:11: warning: [PreferJavaTimeOverload] If the numeric primitive (1 + 2) represents a Instant, please call assertThat(Instant) instead.
     		assertThat(1 + 2).isEqualTo(3);
```

Could we may exclude AssertJ assertThat from this check to avoid tons of @SuppressWarnings("PreferJavaTimeOverload")?

### What version of Error Prone are you using?

2.3.4 SNAPSHOT (error_prone_core-2.3.4-20191015.160021-47-with-dependencies.jar)

**Comment by kluever** [comment]
We don't use AssertJ inside of Google, so we haven't run into this, but this is definitely reasonable.

**Comment by tbroyer** [comment]
I suppose you'll have the same issue with Truth once you add java.time support to Truth8 :wink:

**Comment by kluever** [comment]
@tbroyer Yup, that's true - we're still [trying to figure out](https://github.com/google/truth/issues/420) if adding `java.time` support to Truth makes sense :-)

**Comment by kluever** [comment]
Perhaps a good heuristic to use would be: "if there's >2 overloads for the method, then don't flag it".
