### ISSUE TITLE
README link to https://groups.google.com/forum/#!forum/error-prone-announce says Group does not exist or don't have permission to view it

### ISSUE THREAD

**Issue by kennknowles** [google/error-prone#1380]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

README link to https://groups.google.com/forum/#!forum/error-prone-announce says Group does not exist or don't have permission to view it

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Click on the link for announcements in the README

###  Have you found anything relevant by searching the web?

Nope. No existing issues or error-prone-discuss@ that I can see.

**Comment by eaftan** [comment]
Thanks for the report.  It looks like the permissions on the announce group were not set properly, so I updated them.  Can you please try again and let me know if it is working for you now?

**Comment by kennknowles** [comment]
Yup, looks good!
