### ISSUE TITLE
Automated robolectric migration fails with gradle exception

### ISSUE THREAD

**Issue by ashish-kshirsagar** [google/error-prone#1390]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Getting exception while trying to use robolectric migration suggestions from the link http://robolectric.org/automated-migration/ 

### Feature requests: what underlying problem are you trying to solve with this feature?

> Migrate existing connected (Espresso) tests to robolectric tests.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Use the steps mentioned at provided link above to migrate espresso tests. Update errorprone google javac library to version com.google.errorprone:javac:9-dev-r3297-1 

### What version of Error Prone are you using?

> 2.3.2
[gradle_error_stacktrace.txt](https://github.com/google/error-prone/files/3779451/gradle_error_stacktrace.txt)

###  Have you found anything relevant by searching the web?

> None

**Comment by cushon** [comment]
These robolectric checks are not part of core Error Prone, please report issues with them to https://github.com/robolectric/robolectric.
