### ISSUE TITLE
 An unhandled exception was thrown by the Error Prone static analysis plugin

### ISSUE THREAD

**Issue by guismart** [google/error-prone#1394]
### Description of the problem
encounter error when use gradle to compile original google code with error-prone plugin:
src/com/android/providers/settings/SettingsProvider.java:1487: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
            return settingsState.new Setting(ssaidSetting) {
                                 ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
error-prone version: 2.3.3
     BugPattern: NullAway

     Stack Trace:
     java.lang.RuntimeException: whoops, better handle OTHER null
  	at com.uber.nullaway.NullAway.mayBeNullExpr(NullAway.java:1952)
  	at com.uber.nullaway.NullAway.handleInvocation(NullAway.java:1352)
  	at com.uber.nullaway.NullAway.matchNewClass(NullAway.java:354)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:433)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:759)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:150)
  	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1705)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Gradle compile passed without error-prone plugin, but failed if plugin integrated.

###  Have you found anything relevant by searching the web?
None.

### relevant code fragment
private Setting mascaradeSsaidSetting(SettingsState settingsState, Setting ssaidSetting) {
        if (ssaidSetting != null) {
            return settingsState.new Setting(ssaidSetting) {
                @Override
                public int getKey() {
                    final int userId = getUserIdFromKey(super.getKey());
                    return makeKey(SETTINGS_TYPE_SECURE, userId);
                }

                @Override
                public String getName() {
                    return Settings.Secure.ANDROID_ID;
                }
            };
        }
        return null;
    }

**Comment by Stephan202** [comment]
The NullAway issue is uber/NullAway#366; I think this one can be closed.

**Comment by guismart** [comment]
> The NullAway issue is [uber/NullAway#366](https://github.com/uber/NullAway/issues/366); I think this one can be closed.

Yes.
