### ISSUE TITLE
InterruptedExceptionSwallowed.getThrownExceptions incorrectly handles catch blocks

### ISSUE THREAD

**Issue by carterkozak** [google/error-prone#1428]
### Description of the problem / feature request:

InterruptedExceptionSwallowed.getThrownExceptions incorrectly handles catch blocks when there are multiple catch trees. As written, the function assumes each catch is capable of handling errors thrown by previous catch blocks, which is not the case.

### Feature requests: what underlying problem are you trying to solve with this feature?

The bug checker should take into account how TryTrees are executed in java.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I will push a failing test shortly.

### What version of Error Prone are you using?

df4cdefbf351c76098562c2d83eebf4cafaa8eea

###  Have you found anything relevant by searching the web?
No.

**Comment by carterkozak** [comment]
PR is up: https://github.com/google/error-prone/pull/1429

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/60de2dc1aa996d20263163d846d81ea2cbdc417f
