### ISSUE TITLE
PreferJavaTimeOverload fails on AssertJ extensions which handle time

### ISSUE THREAD

**Issue by carterkozak** [google/error-prone#1435]
### Description of the problem / feature request:

PreferJavaTimeOverload fails eroniously on assertj assertion classes which have time overloads, or extend `org.assertj.core.api.Assertions`.

### Feature requests: what underlying problem are you trying to solve with this feature?
Consider allowing methods named `assertThat` which return subtypes of `org.assertj.core.api.Assert` to pass validation rather than whitelisting only `org.assertj.core.api.Assertions.assertThat`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Easiest way to reproduce this is by subclassing Assertions (nonfinal utility class, obviously it's bad practice to extend static utility classes in modern java, but this occurs relatively frequently in the wild).

### What version of Error Prone are you using?
2.3.4

###  Have you found anything relevant by searching the web?
no.

**Comment by Stephan202** [comment]
Relates to #1377; sounds like a subtype-aware variation on f1df86d66b92aeea6e9f5fa9263e366034b68209 will fix this.

**Comment by php-coder** [comment]
> Easiest way to reproduce this is by subclassing Assertions (nonfinal utility class, obviously it's bad practice to extend static utility classes in modern java, but this occurs relatively frequently in the wild).

In my case, a test implements [`WithAssertions`](https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/WithAssertions.html) that also fired this check but it doesn't seem a bad practice.

**Comment by kluever** [comment]
I think this can be closed now. Please re-open if you'd like additional opt-out heuristics
