### ISSUE TITLE
PreferJavaTimeOverload interacts poorly with AssertJ assumeThat

### ISSUE THREAD

**Issue by carterkozak** [google/error-prone#1437]
### Description of the problem / feature request:

There's already special casing for AssertJ assertThat, however the `assumeThat` function has similar problems. Perhaps it would be best to exclude invocations with overloads that are not date types (boolean, arrays, etc) as a general solution rather than individually excluding common libraries.

### Feature requests: what underlying problem are you trying to solve with this feature?

Same as above.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`org.assertj.core.api.Assumptions.assumeThat(1).isEqualTo(1);`

### What version of Error Prone are you using?

2.3.4

###  Have you found anything relevant by searching the web?

no.

**Comment by kluever** [comment]
Thanks - we should fix this (and thanks for the PR!)
