### ISSUE TITLE
SuggestedFixes.renameMethodInvocation renames parameters with names matching the method

### ISSUE THREAD

**Issue by carterkozak** [google/error-prone#1451]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

`SuggestedFixes.renameMethodInvocation(tree, "updated", state)` results in:

```diff
- obj.foo(bar, foo);
+ obj.foo(bar, updated);
```

### Feature requests: what underlying problem are you trying to solve with this feature?

See above, methods are rewritten incorrectly.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See above example.

### What version of Error Prone are you using?

2.3.4

###  Have you found anything relevant by searching the web?

no.

**Comment by graememorgan** [comment]
Thanks for the report. Sent out a fix internally.

**Comment by cushon** [comment]
This was fixed by https://github.com/google/error-prone/commit/b7f7883b5eb93d1cc8fc881cfce69bac4f46d98c.
