### ISSUE TITLE
Incorrectly rendered markdown in IdentityBinaryExpression

### ISSUE THREAD

**Issue by raynicho** [google/error-prone#1487]
### Description of the problem / feature request:

IdentityBinaryExpression markdown still includes `java {.good}` and `java {.bad}`. These tags were supposed to be removed in issue #962 (commit - e43a577723a52de9d000f18b553bc55616d9e5df). This leads to the markdown rendering incorrectly. 

http://errorprone.info/bugpattern/IdentityBinaryExpression

![image](https://user-images.githubusercontent.com/18505724/73384174-5bbc1c80-4290-11ea-845d-1e1f2f26c2b1.png)

### Feature requests: what underlying problem are you trying to solve with this feature?

Fix the IdentityBinaryExpression markdown so the example is rendered correctly.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

IdentityBinaryExpression includes `java {.good}` and `java {.bad}` tags. This causes issues rendering the markdown.

### What version of Error Prone are you using?

I'm not using Error Prone. This is about the errorprone.info documentation.

###  Have you found anything relevant by searching the web?

Yes. I found the related issue #962 and commit (e43a577723a52de9d000f18b553bc55616d9e5df). The commit (e43a577723a52de9d000f18b553bc55616d9e5df) does not include changes to `IdentityBinaryExpression.md`.

**Comment by cushon** [comment]
This has been fixed: https://github.com/google/error-prone/blob/0a645f95de5942ec0e389e16d3c4217b20f31e40/bugpattern/IdentityBinaryExpression.md
