### ISSUE TITLE
@SuppressWarnings support for Refaster templates

### ISSUE THREAD

**Issue by knutwannheden** [google/error-prone#1517]
For a given Refaster template it would be nice if client code could use an `@SuppressWarnings` annotation to suppress a particular match from being reported. I suppose the simplest solution would be to use the Refaster template's fully qualified class name as the ID of the warning.

**Comment by Stephan202** [comment]
A (not super nice) workaround is to add a comment "inside" the expression that would otherwise be transformed. Any comment will do (e.g. `/* No Refaster */`), but this doesn't work for e.g. constants :)

**Comment by knutwannheden** [comment]
@Stephan202 Thanks for the tip.

Similarly I would also have hoped that I can use `-Xep:my.refaster.Template:OFF` to disable a given Refaster template. But this doesn't appear to work, AFAICT.

**Comment by rickie** [comment]
@cushon do you think that this issue is resolved with PR #1517?

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/ca6b5300852f3e67e8938afffe01863825a3880d
