### ISSUE TITLE
Inconsistent library versions notice.

### ISSUE THREAD

**Issue by calvinhkf** [google/error-prone#1527]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 1 inconsistent library and 3 false consistent libraries.

Take com.google.auto.service:auto-service for example, this library is declared as version 1.0-rc4 in core, 1.0-rc2 in refaster and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take com.google.auto.service:auto-service for example, if we harmonize all the library versions into 1.0-rc4. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table shows the overall harmonization cost on APIs. It seems your project have no API invokes on this library, which could be safely upgrade to 1.0-rc4

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|core|0(0)|0(0)|0(0)|
|2|refaster|0(0)|0(0)|0(0)|
|3|docgen|0(0)|0(0)|0(0)|
|4|..|..|..|..|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

As for false consistency, take com.google.truth truth jar for example. The library is declared in version 0.45 in all modules. However they are declared differently.  As components are developed in parallel, if one single library version is updated, which could become inconsistent as mentioned above, may cause above-mentioned inconsistency issues

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[google error-prone.pdf](https://github.com/google/error-prone/files/4270533/google.error-prone.pdf)

**Comment by cushon** [comment]
https://github.com/google/error-prone/pull/1531
