### ISSUE TITLE
Getting a NoClassDefFoundError for "com/github/benmanes/caffeine/cache/Caffeine" when running Error Prone on ant build

### ISSUE THREAD

**Issue by ptr5201** [google/error-prone#1536]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Getting a NoClassDefFoundError for "com/github/benmanes/caffeine/cache/Caffeine" when running Error Prone on ant build for Apache Nutch v1.1 project.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

After changing "target" and "source" to "1.8" (using version 1.8.0_144 for Java compiler), adding dependencies to locations in .m2 repository and updating build.xml file per instructions in https://errorprone.info/docs/installation#ant, I'm getting the following error below:

compile-core:
    [javac] Compiling 236 source files to C:\Users\Philip\Documents\RIT\Graduate\2019-2020\Spring\SWEN.777.01 Quality Assurance\Assignment 3\apache-nutch-1.1\build\classes
    [javac] error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    [javac]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]
    [javac]      error-prone version: 2.3.4
    [javac]      BugPattern: (see stack trace)
    [javac]      Stack Trace:
    [javac]      java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/Caffeine
    [javac]     at com.google.errorprone.util.ASTHelpers.<clinit>(ASTHelpers.java:694)
    [javac]     at com.google.errorprone.SuppressionInfo$1.visitClass(SuppressionInfo.java:117)
    [javac]     at com.google.errorprone.SuppressionInfo$1.visitClass(SuppressionInfo.java:114)
    [javac]     at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
    [javac]     at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:80)
    [javac]     at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:94)
    [javac]     at com.google.errorprone.SuppressionInfo.forCompilationUnit(SuppressionInfo.java:121)
    [javac]     at com.google.errorprone.scanner.Scanner.updateSuppressions(Scanner.java:87)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:54)
    [javac]     at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
    [javac]     at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
    [javac]     at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:302)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:162)
    [javac]     at com.sun.tools.javac.Main.compile(Main.java:57)
    [javac]     at com.sun.tools.javac.Main.main(Main.java:43)
    [javac]   Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.Caffeine
    [javac]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    [javac]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    [javac]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    [javac]     ... 19 more
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
C:\Users\Philip\Documents\RIT\Graduate\2019-2020\Spring\SWEN.777.01 Quality Assurance\Assignment 3\apache-nutch-1.1\build.xml:127: Compile failed; see the compiler error output for details.

Total time: 10 seconds

Even after adding the ben-manes artifact (which contains the Caffeine class) to the project's lib folder, I'm still getting the same error. I'm also getting this error when running the ant example for error-prone, but I'm not getting the error when running the maven example (which is working as expected).

### What version of Error Prone are you using?

2.3.4

###  Have you found anything relevant by searching the web?

No

**Comment by ptr5201** [comment]
Attached is the build.xml file (as a text file) I'm attempting to run Error Prone on; build.xml file has already been modified according to instructions to run Error Prone using Ant.

[build.xml.txt](https://github.com/google/error-prone/files/4303945/build.xml.txt)

The link to the Apache Nutch v1.1 source code is:

https://github.com/apache/nutch/releases/tag/1.1

**Comment by tbroyer** [comment]
Related to #1398

**Comment by ptr5201** [comment]
After locally making the change in #1398 and generating the new "...-with-dependencies.jar" file via "mvn package -DskipTests", I'm now getting the following error:


An unhandled exception was thrown by the Error Prone static analysis plugin.
    [javac] package org.apache.nutch.analysis;
    [javac] ^
    [javac]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]
    [javac]      error-prone version: 2.3.5-SNAPSHOT
    [javac]      BugPattern: AutoValueSubclassLeaked
    [javac]      Stack Trace:
    [javac]      java.lang.NoClassDefFoundError: com/google/auto/value/AutoValue
    [javac]     at com.google.errorprone.bugpatterns.AutoValueSubclassLeaked$2.visitClass(AutoValueSubclassLeaked.java:101)
    [javac]     at com.google.errorprone.bugpatterns.AutoValueSubclassLeaked$2.visitClass(AutoValueSubclassLeaked.java:98)
    [javac]     at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
    [javac]     at com.sun.source.util.TreeScanner.scan(TreeScanner.java:86)
    [javac]     at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
    [javac]     at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
    [javac]     at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
    [javac]     at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
    [javac]     at com.google.errorprone.bugpatterns.AutoValueSubclassLeaked.findAutoValueClasses(AutoValueSubclassLeaked.java:97)
    [javac]     at com.google.errorprone.bugpatterns.AutoValueSubclassLeaked.matchCompilationUnit(AutoValueSubclassLeaked.java:60)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:557)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:152)
    [javac]     at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
    [javac]     at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:56)
    [javac]     at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
    [javac]     at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
    [javac]     at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:302)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:162)
    [javac]     at com.sun.tools.javac.Main.compile(Main.java:57)
    [javac]     at com.sun.tools.javac.Main.main(Main.java:43)
    [javac]   Caused by: java.lang.ClassNotFoundException: com.google.auto.value.AutoValue
    [javac]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    [javac]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    [javac]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    [javac]     ... 26 more
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED

**Comment by cushon** [comment]
This should be fixed by #1587
