### ISSUE TITLE
Suggested Error Prone pattern: computeIfAbsent

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/error-prone#1552]
### Description of the problem / feature request:

`map.computeIfAbsent(someLong, AtomicLong::new).incrementAndGet();`

Code of this form can seemingly look like it's trying to make a counter, creating the key if absent.   Unfortunately the code is surprising, because it will call the wrong AtomicLong constructor.  Instead, it will create the counter initialized with the key value, which is probably not desired.

### What version of Error Prone are you using?

2.3.4

**Comment by JakeWharton** [comment]
Funny because this would make for a good error-prone check itself!

**Comment by cpovirk** [comment]
Neat :) A naive search finds one hit internally (possibly the only one to ever be submitted, thankfully), and I see a couple other people who are working around it with a custom `MyClass::newAtomicInteger` method reference. (They seem to have caught the problem during development (or avoided it entirely).)

**Comment by sumitbhagwani** [comment]
The check was added in https://github.com/google/error-prone/commit/7572c1aff7b2995c7874332415ff8aaf4d8a01c5
