### ISSUE TITLE
No definition for ImmutableTypeParameter annotation mentioned in Immutable document

### ISSUE THREAD

**Issue by MichalStehlikCz** [google/error-prone#1569]
### Description of the problem / feature request:

Document error-prone/docs/bugpattern/Immutable.md mentions ImmutableTypeParameter type annotation, but no such annotation exists in code.

### Feature requests: what underlying problem are you trying to solve with this feature?

Purpose of such annotation is described in document. When implementing immutable interface via generic container, it would be nice to be able to restrict parameter type to immutable via annotation

### What version of Error Prone are you using?

2.3.4

**Comment by MichalStehlikCz** [comment]
Ok, it can be found in error-prone/type_annotations/src/main/java/com/google/errorprone/annotations/, my mistake

**Comment by hugmanrique** [comment]
What's the reasoning for this single annotation to be in another package in the first place? This isn't mentioned anywhere in the docs, and can lead to confusion.

**Comment by MichalStehlikCz** [comment]
I believe it was placed in separate library to maintain support for pre-java 1.8 targets, as type annotations were only added in java 8. Obviously I was confused as well, as need for separate dependency is not mentioned in document, but eventually found it.

**Comment by creemama** [comment]
If you are looking for the Maven artifact containing `ImmutableTypeParameter`, see https://mvnrepository.com/artifact/com.google.errorprone/error_prone_type_annotations.
