### ISSUE TITLE
Missing space after word 'inclusive' in the string.

### ISSUE THREAD

**Issue by amarlearning** [google/error-prone#1570]
Missing space after word `inclusive` in the string.

https://github.com/google/error-prone/blob/b443cc8ec4ef04f1d927f534bca6fb907a052668/core/src/main/java/com/google/errorprone/bugpatterns/SubstringOfZero.java#L38-L40

**Comment by nglorioso** [comment]
Thanks for the callout! I'll have a fix synced out in the next day or two.
