### ISSUE TITLE
ErrorProne unhandled Exception

### ISSUE THREAD

**Issue by vpinna80** [google/error-prone#1574]
### Description of the problem / feature request:

> error: An unhandled exception was thrown by the Error Prone static analysis plugin.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Just launch maven build with compile target.

### What version of Error Prone are you using?

> 2.3.4.

###  More info

     error-prone version: 2.3.4
     BugPattern: HashtableContains
     Stack Trace:
     java.lang.AssertionError: unexpected argument to contains(): key: it.bancaditalia.oss.vtl.model.data.DataStructureComponent<?,?,?>, value: it.bancaditalia.oss.vtl.model.data.ScalarValue<?,?,?>, argument: java.lang.Object

**Comment by cushon** [comment]
What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**Comment by vpinna80** [comment]
Sorry but in the end we decided to move onto a different product.
Thank you.
