### ISSUE TITLE
Invalid flag: -XepCompilingTestOnlyCode

### ISSUE THREAD

**Issue by zielint0** [google/error-prone#1582]
Error prone properly scans *production* code (e.g. src\main\java\ ... \Library.java) and detects an intended error (new Exception();) but skips analysis of my *test* code (e.g. src\test\java\ ... \LibraryTest.java) and does not find the same error (new Exception();).

If I understand situation correctly, test code analysis is skipped by default. So there is a flag to include a test code: -XepCompilingTestOnlyCode

I tried to include a test code using -XepCompilingTestOnlyCode but obtained an error:

*[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ...: Fatal error compiling: error
: invalid flag: -XepCompilingTestOnlyCode -> [Help 1]*

```
                <configuration>
                    <release>11</release>
                    <compilerArgs>
                        <arg>-Xlint:all</arg>
                        <arg>-Werror</arg>
                        <arg>-XDcompilePolicy=simple</arg>
                        <arg>-Xplugin:ErrorProne</arg>
                        <arg>-XepCompilingTestOnlyCode</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.errorprone</groupId>
                            <artifactId>error_prone_core</artifactId>
                            <version>2.3.4</version>
                        </path>
                    </annotationProcessorPaths>
                    <showWarnings>true</showWarnings>
                </configuration>
```
I also tried:
<arg>-Xplugin:ErrorProne -XepCompilingTestOnlyCode</arg>
<arg>-Xplugin:ErrorProne -Xep:CompilingTestOnlyCode:ON</arg>
according to http://errorprone.info/docs/flags

It works on Gradle so should also on Maven
https://github.com/tbroyer/gradle-errorprone-plugin/issues/26
```
tasks {
    compileJava {
        options.compilerArgs.addAll(arrayOf("-XDcompilePolicy=simple", "-Xplugin:ErrorProne -XepDisableWarningsInGeneratedCode"))
    }
    testCompileJava {
        options.compilerArgs.addAll(arrayOf("-XDcompilePolicy=simple", "-Xplugin:ErrorProne -XepDisableWarningsInGeneratedCode -XepCompilingTestOnlyCode"))
    }
}
```

Configuration:

D:\Projects\...>mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\Applications\mvn\bin\..
Java version: 11.0.2, vendor: Oracle Corporation, runtime: D:\Programs\Java\openjdk-11.0.2
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

What is my mistake?

**Comment by tbroyer** [comment]
`-XepCompilingTestOnlyCode` needs to be in the same `<arg>` as `-Xplugin:ErrorProne`, separated by blanks (just like you put them in the same string in your Gradle configuration).

But that's not what will make error prone work on your test code if it's not already, it only changes to some checks behave.
You probably only configured the `compile` goal and not `testCompile` (or is it `compileTest`? can't remember), i.e. you put your `<configuration>` inside an `<execution>`, or you override the `<compilerArgs>` for `testCompile`

**Comment by zielint0** [comment]
@tbroyer 
Thank you for your answer.

>You probably only configured the compile goal and not testCompile (or is it compileTest? can't remember), i.e. you put your <configuration> inside an <execution>, or you override the <compilerArgs> for testCompile

No. I configured Error Prone in general configuration. It works for production (src\main\java...) AND test code (src\test\java\...).

The problem was that Error Prone does not find problems in classes that have one or more methods with `@Test` annotation.

I commented out a line with `@Test` annotation and Error Prone found a problem ([DeadException]).
```
public class LibraryTest {
    void x() { new Exception(); }

    //@Test
    public void testMethod() {
        Library classUnderTest = new Library();
        assertThat("...", c.f(0), is(false));
        assertThat("...", c.f(1), is(true));
    }
}
```

Is it an intended behaviour to skip classes with `@Test` annotation?

**Comment by cushon** [comment]
> Is it an intended behaviour to skip classes with @Test annotation?

That's a heuristic for that specific check, yes: https://github.com/google/error-prone/blob/2a76bb966210568607f4772b4c671591c112319f/core/src/main/java/com/google/errorprone/bugpatterns/DeadException.java#L61-L65

**Comment by zielint0** [comment]
@cushon 
Thank you for clarification.
