### ISSUE TITLE
[MockitoCast] Failure type changed since Mockito 2.24.3

### ISSUE THREAD

**Issue by gm2211** [google/error-prone#1616]
### Description of the problem / feature request:

The `MockitoCast` bugpattern https://errorprone.info/bugpattern/MockitoCast mentioned that it was necessary until https://github.com/mockito/mockito/issues/357 got resolved.

https://github.com/mockito/mockito/pull/1612 closed that issue and was released into Mockito `2.24.3` (https://github.com/mockito/mockito/commit/cbedbe567d5bf902b13e8cebc4a2a2ccfef7758f)

However, that PR simply changed the type of error being thrown `NullPointerException` instead of `ClassCast` exception.

### Feature requests: what underlying problem are you trying to solve with this feature?

The description of the bugpattern should be maybe be updated to include the new behavior since `Mockito 2.24.3` (i.e. `NullPointerException` being thrown instead of class cast)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Example of `NullPointerException` being thrown (interestingly only during `verify`) instead of class cast exception:

```
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.clearInvocations;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Answers;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

final class MyTest {
    interface Job {}

    interface JobList {
        List<Job> jobs();

        static JobList of(Job... jobs) {
            return () -> List.of(jobs);
        }
    }

    public interface JobClient {
        Createable<JobList, Job> jobs();
    }

    public interface Createable<T, I> {
        T create(I... item);
    }

    @Mock(answer = Answers.RETURNS_DEEP_STUBS)
    private JobClient client;

    @BeforeEach
    void beforeEach() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void name() {
        Job job = mock(Job.class);

        when(client.jobs().create(any(Job.class))).thenReturn(JobList.of(job));
        clearInvocations(client);

        // Interestingly does not fail
        assertThat(client.jobs().create(job).jobs()).containsExactly(job);

        // Fails with null pointer exception
        verify(client).jobs().create(job);
    }
}

```

### What version of Error Prone are you using?

`2.3.4`

**Comment by cushon** [comment]
> that PR simply changed the type of error being thrown NullPointerException instead of ClassCast exception.

My understanding is that the PR fixes some, but not all, of the cases where a CCE was being thrown. From the PR description:

> This solves a large number of edge-cases where null will actually
> remove the runtime ClassCastException. This essentially negates the
> whole MockitoCast ErrorProne check. We can still not support every use
> case, but causing a NPE instead of a CCE does not seem to make this
> worse.
