### ISSUE TITLE
Release Error Prone 2.4.0

### ISSUE THREAD

**Issue by cushon** [google/error-prone#1639]
Tracking bug for 2.4.0 release.

**Comment by davido** [comment]
Great new! Waiting for EP 2.4.0 to show up, so that I can bump outdated and actually unknown EP version in Bazel (2.3.2-SNAPSHOT version is currently used there).

**Comment by cushon** [comment]
Thanks @davido! Have you had a chance to test the latest snapshot of EP against Bazel's CI?

**Comment by davido** [comment]
> Have you had a chance to test the latest snapshot of EP against Bazel's CI?

Sure! Already build EP 2.3.5-SNAPSHOT that includes all your recent changes and uploaded a new version of my [PR](https://github.com/bazelbuild/bazel/pull/11426) (forced push). Unfortunately, the outdated Android SDK used in Bazel, that still depends on outdated Guava library causing all Android tests in Bazel to fail.

I have also built `java_tools_java11.zip` on Linux and published it on my `java_tools` fork: [1]. Now I will kick the verification for Gerrit eco-system with this new and shiny `java_tools`, with the latest and greatest EP 2.3.5-SNAPSHOT: [2].

Next step is to use EP 2.4.0 for "java_tools_java14.zip" work. Hope to upload a PR for review ASAP (jdk.compiler module is missing, but i think it can be skipped in the toolchain definition).

[1] https://github.com/davido/java_tools/releases/tag/javac11-v12.0
[2] https://gerrit-review.googlesource.com/c/gerrit/+/265493

**Comment by cushon** [comment]
I think Error Prone is still compatible with `guava-25.1-jre`. It might be possible to defer upgrading Bazel's version of guava, and avoid the issue with the Android SDK?

**Comment by cushon** [comment]
Anyway, let me know if the latest snapshot looks sane to you, and I can go ahead it release it. We can always do a point release if additional testing with Bazel reveals other issues.

**Comment by davido** [comment]
> I think Error Prone is still compatible with guava-25.1-jre. 

Thanks for clarifying, let me try to downgrade `guava` again and update the PR. Will upload new version in a moment.

**Comment by davido** [comment]
Thanks, @cushon. After downgrading `guava` again to `guava-25.1-jre` Bazel CI is passing all tests with the latest EP 2.3.5-SNAPSHOT upgrade: https://github.com/bazelbuild/bazel/pull/11426.

I have also tested Gerrit and JGit againt latest EP snapshot and have not found any issues. Looks sane to me. I think you can go ahead and release it ;-)

Thanks again for demoting problematic bug patterns that broke Bazel cross compilation use case from error severity to warning and adding JDK 14 support!

**Comment by cushon** [comment]
As a quick update, I found a few crashes while validating the release, and I'm preparing fixes for those. I'll cut the 2.4.0 release as soon as those fixes land.

**Comment by cushon** [comment]
https://github.com/google/error-prone/releases/tag/v2.4.0
