### ISSUE TITLE
@SuppressWarnings("InlineFormatString") doesn't work

### ISSUE THREAD

**Issue by anthonyvdotbe** [google/error-prone#1650]
### Description of the problem / feature request:

I'm unable to suppress `InlineFormatString`, neither by annotating the constant, nor by annotating the method that uses the constant.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

````java
class Foo {

    @SuppressWarnings("InlineFormatString")
    private static final String FMT = "%s";

    @SuppressWarnings("InlineFormatString")
    String foo() {
        return String.format(FMT, "bar");
    }

}
````

### What version of Error Prone are you using?

2.4.0

###  Have you found anything relevant by searching the web?

No.

**Comment by cushon** [comment]
This was an oversight, I agree `@SuppressWarnings("InlineFormatString")` should work if the constant or an enclosing scope is annotated.

Out of curiosity, was there a particular real-world example where this suggestion wasn't useful? If you disagree with it in general, you can also disable the check with `-Xep:InlineFormatString:OFF`.

**Comment by anthonyvdotbe** [comment]
In this case, I had relatively large text blocks (think: templates) which contained just 1/2 arguments, and the format strings were used like:
````java
builder
.with(Foo.class, o -> String.format(FMT_FOO, v.apply(o.content().text())))
.with(Bar.class, (v, o) -> String.format(FMT_BAR, v.apply(o.content())))
...
.with(Baz.class, (v, o) -> String.format(FMT_BAZ, v.apply(o.content())))
````

So inlining the format Strings would make the code look messy, and I felt that refactoring the code to use separate methods wasn't worth the effort. I don't disagree with it in general, though.
