### ISSUE TITLE
`BadImport` replaces enum declarations

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#1653]
Consider the following code:
```java
package foo;

import foo.Dummy.Type;

final class Dummy {
    private final Type type = Type.SIMPLE;

    enum Type {
        SIMPLE,
        COMPLEX;
    }
}
```

Applying the `BadImport` check to this code:
```sh
wget \
  https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.4.0/error_prone_core-2.4.0-with-dependencies.jar
javac \
  -XDcompilePolicy=simple \
  -processorpath error_prone_core-2.4.0-with-dependencies.jar \
  '-Xplugin:ErrorProne -XepPatchChecks:BadImport -XepPatchLocation:/tmp' \
  foo/Dummy.java
```

This yields:
```diff
--- foo/Dummy.java
+++ foo/Dummy.java
@@ -1,12 +1,12 @@
 package foo;
 
-import foo.Dummy.Type;
 
+
 final class Dummy {
-    private final Type type = Type.SIMPLE;
+    private final Dummy.Type type = Dummy.Type.SIMPLE;
 
     enum Type {
-        SIMPLE,
-        COMPLEX;
+        Dummy.SIMPLE,
+        Dummy.COMPLEX;
     }
 }
```

As can be seen, the `Type` enum declaration is now invalid.

(Related question: perhaps `BadImport` shouldn't flag any direct imports of types defined in the same compilation unit? That would also automatically fix this bug.)

**Comment by graememorgan** [comment]
Nice finding. Sent out a fix internally.

> perhaps BadImport shouldn't flag any direct imports of types defined in the same compilation unit? That would also automatically fix this bug

This seems reasonable as a heuristic to me: it shouldn't be as ambiguous within the same file.
