### ISSUE TITLE
[Suggestion]BoxedPrimitiveEquality supports detection assertSame(foo, bar) is recommended

### ISSUE THREAD

**Issue by wuchiuwong** [google/error-prone#1661]
### Description of the problem / feature request:

For rule BoxedPrimitiveEquality, <code>assertSame(foo, bar);</code> is also used to determine whether reference is equalalled. It is recommended that this rule supplement the detection of this case,
This rule is implemented in error_prone_core-2.3.4-sources.jar!\com\google\errorprone\bugpatterns\BoxedPrimitiveEquality.java, which is extended from error_prone_core-2.3.4-sources.jar!\com\google\errorprone\bugpatterns\AbstractReferenceEquality.java
In AbstractReferenceEquality.java, the operations for detecting equality are listed, for example: <code>==, !=, Objects.equals(a, b), a.equals(b)</code>, 
but <code>assertSame(foo, bar);</code> is not among them, so this situation can not be detected.

### Feature requests: what underlying problem are you trying to solve with this feature?

```
assertSame(c, converter.coerceToCharacter(c));
Assert.assertSame(3, nodes.size());
Assert.assertSame('H', player.getSymbol());
```

### What version of Error Prone are you using?

2.3.4

###  Have you found anything relevant by searching the web?

no

**Comment by graememorgan** [comment]
I tend to think `assertSame` is explicit enough (and unusual enough: it stands out) that this probably isn't worth flagging.

The issue is that `boxedLong == otherBoxedLong` is misleading.

**Comment by cushon** [comment]
> The issue is that `boxedLong == otherBoxedLong` is misleading.

We're catching the general case of that in http://errorprone.info/bugpattern/BoxedPrimitiveEquality
