### ISSUE TITLE
Strange compiler error using Error Prone 2.4.0

### ISSUE THREAD

**Issue by serhii-lekariev** [google/error-prone#1693]
### Description of the problem 

Declaring an enum with a method documented with a `{@link }` causes a compiler error in Error Prone `2.4.0`. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[This repo](https://github.com/serhii-lekariev/error-prone-error-repro) contains the steps to reproduce and additional details.

In short:

1) Declare an enum. 
2) Declare an enum constant.
3) In the body of this constant, declare a method.
4) Document the method with a Javadoc that references another class with a `{@link }`. The class itself doesn't seem to matter, I've tested against `java.lang.Object` and `java.lang.Throwable`.
5) Try to `mvn clean compile`.

### What version of Error Prone are you using?

2.4.0

###  Have you found anything relevant by searching the web?
I have not.

**Comment by cushon** [comment]
Thanks for the report, the underlying issue here appears to be a javac bug: https://bugs.openjdk.java.net/browse/JDK-8248117. I think I can work around it.
