### ISSUE TITLE
PreferJavaTimeOverload generates false positive with jOOQ DSL.val()

### ISSUE THREAD

**Issue by niktekusho** [google/error-prone#1694]
### Description of the problem / feature request:

This issue is very similar to #1504.
When I use Jooq's `DSL.val(0)`, ErrorProne emits the **PreferJavaTimeOverload** warning. 
`[PreferJavaTimeOverload] If the numeric primitive (0) represents a Instant, please call DSL.val(Instant) instead.`
I don't think ErrorProne should emit the warning since `DSL.val` returns an object with the same generic type:

- `DSL.val(int)` returns `Field<Integer>`
- while `DSL.val(Instant)` returns `Field<Instant>`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Simply call `DSL.val(0)`.

### What version of Error Prone are you using?

`2.3.4`

###  Have you found anything relevant by searching the web?

Looking through ErrorProne's issues, I saw #1504, which is very similar to my case.

Since the fix to this issue is virtually the same as #1511, should I open a PR with the fix?

**Comment by kluever** [comment]
Thanks for the report - I'll get this fixed up internally.

**Comment by kluever** [comment]
(Planning on just ignoring any static methods on the entire `DSL` class.)
