### ISSUE TITLE
Remove <repositories> from POMs

### ISSUE THREAD

**Issue by tbroyer** [google/error-prone#1809]
### Description of the problem / feature request:

The `error_prone_core` POM contains a `<repository>`, which shouldn't be needed but will be inherited by users' builds (in Maven, not Gradle; don't know about other build tools)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The error was reported on the gradle-errorprone-plugin issue tracker: https://github.com/tbroyer/gradle-errorprone-plugin/issues/47, I don't have more information (user seems to be Chinese, so it might be related to the Great Firewall, or it could be something entirely different), but having declared `<repositories>` in published POMs is not a good practice.

### What version of Error Prone are you using?

The repository is present in the 2.4.0 POM, and many previous versions: https://search.maven.org/artifact/com.google.errorprone/error_prone_core/2.4.0/jar

###  Have you found anything relevant by searching the web?

The repository was added 8 years ago in https://github.com/google/error-prone/commit/25502534ab1ecef7a7251991c784d71a7753c2a2, apparently because `com.google.code.findbugs:jsr305:2.0.1` was not available in Central.
According to https://search.maven.org/artifact/com.google.code.findbugs/jsr305, it was there already at the time though, so this repository shouldn't even have been added to begin with, but here we are.

I suggest removing those lines from the POM and confirm that the project still build correctly (even from a clean state / empty local repository).

**Comment by albanyqq** [comment]
Yes,i'm come from china .
but because of the my company regulations,I can't connect to the external network inside the company.So that's the problem
I have to modify the warehouse address, To be able to download dependencies.

**Comment by tbroyer** [comment]
That helps understand how to possibly reproduce the issue, thanks.

BTW, if you have an internal repository, then you probably should setup a mirror in your Maven settings.xml with `<mirrorOf>*</mirrorOf>`: https://maven.apache.org/guides/mini/guide-mirror-settings.html (or set one up for each repository you want to mirror, explicitly, as I suggested in https://github.com/tbroyer/gradle-errorprone-plugin/issues/47, depending on your corporate policy)
