### ISSUE TITLE
when i run with idea error-prone plugin, the idea message is display "Failed to download

### ISSUE THREAD

**Issue by albanyqq** [google/error-prone#1810]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

When I run an idea plugin, it reports an error.
The idea message display is "Failed to download 'https://repo1.maven.org/maven2....../error_prone_ant-2.x.x.jar'  "

> Replace this line with your answer.

Failed to download 'https://repo1.maven.org/maven2....../error_prone_ant-2.x.x.jar'  
Depending on my corporate policy, I can't connect to the external network inside the company.So,How can I solve this problem？

> Replace this line with your answer.

Install the plugin for the first time, close the network and start the javac with error-prone 

> Replace this line with your answer.

I installed errpr-prone-plugins v182.3911.36,and add settings to the maven-compiler-plugin with java 1.8.

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?
no

> Replace these lines with your answer.
>
> Places to look:
> - GitHub issues: https://github.com/google/error-prone/issues
> - email threads on https://groups.google.com/forum/#!forum/error-prone-discuss

**Comment by albanyqq** [comment]
God
error-prone-plugin ->  error-prone.jar-> lib/library/error-prone.xml   
The download address is fixed to “repo1.maven ....."

**Comment by gregallen** [comment]
work around - fetch the jar to your maven repo via corporate maven mirror:

`mvn dependency:get -Dartifact=com.google.errorprone:error_prone_core:2.6.0:jar:with-dependencies`
