### ISSUE TITLE
javadoc search broken

### ISSUE THREAD

**Issue by Zemnmez** [google/error-prone#1825]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Searching in the [javadoc], for e.g. `WrongOneof` and pressing enter gets you:

```URL
https://errorprone.info/api/latest//undefined/com/google/errorprone/bugpatterns/WrongOneof.html
```

When instead it should be:

```URL
https://errorprone.info/api/latest//com/google/errorprone/bugpatterns/WrongOneof.html
```

This makes it hard to read the docs, as they go to a broken page.

[javadoc]: https://errorprone.info/api/latest//com/google/errorprone/bugpatterns/WrongOneof.html

### Feature requests: what underlying problem are you trying to solve with this feature?

Not being able to read the reference documentation

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Search a known identifier in the published reference docs (see above)

### What version of Error Prone are you using?

N/A

###  Have you found anything relevant by searching the web?

No

**Comment by cpovirk** [comment]
FYI: https://github.com/google/truth/pull/672

**Comment by Zemnmez** [comment]
looks good to me

**Comment by cushon** [comment]
The is fixed in the latest versions of the generated javadoc.
