### ISSUE TITLE
Warning: 'this' escapes constructor

### ISSUE THREAD

**Issue by cushon** [google/error-prone#184]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=184) created by **kevinb@google.com** on 2013-09-11 at 05:28 PM_

---

A constructor body should never pass 'this' ... anywhere?  In general APIs do not expect to receive partly-constructed instances!  I suppose there might be exceptions to this rule.  We'll have to see what the violations look like.

**Comment by vmaverick** [comment]
Do you think this is a check a novice might try contributing?

**Comment by kevinb9n** [comment]
As you heard in other forum - certainly!

**Comment by cushon** [comment]
A check for this was added but never enabled by default, and removed in https://github.com/google/error-prone/commit/98d25b520237aacb941bdf27ad4b73ffddacbb14 because "it found too many issues that were hard to fix -- the pattern may not be good, but it's deeply ingrained."

There is a related javac lint check in JDK 21 called `this-escape` that specifically looks for calling overrideable methods in constructors, it might make sense to use a similar approach, or just use that check instead of trying to do something in Error Prone:

* https://bugs.openjdk.org/browse/JDK-8015831
* https://bugs.openjdk.org/browse/JDK-8314437

**Comment by cushon** [comment]
I'm going to close this out for now. If anyone is interested in static analysis for this, I recommend trying out the JDK `this-escape` diagnostic mentioned in https://github.com/google/error-prone/issues/184#issuecomment-1711923438.
