### ISSUE TITLE
lombok.Generated annotation is ignored

### ISSUE THREAD

**Issue by sergeykad** [google/error-prone#1863]
### Description of the problem / feature request:

Enabling Lombok's `@Generated` annotation via `lombok.addLombokGeneratedAnnotation = true` does not reduce the number of reported issues.

### Feature requests: what underlying problem are you trying to solve with this feature?

Error Prone ignores the [lombok.Generated](https://projectlombok.org/api/lombok/Generated.html) annotation. Unlike the `javax.annotation.processing.Generated` annotation this one has `@Retention(CLASS)` instead of `SOURCE`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Adding a few Lombok annotations is usually enough to trigger a violation. There are already some examples available here:
https://github.com/google/error-prone/issues/1700
https://github.com/google/error-prone/issues/1482
https://github.com/google/error-prone/issues/1481

### What version of Error Prone are you using?

2.4.0

###  Have you found anything relevant by searching the web?
No

**Comment by tbroyer** [comment]
It would actually be great if ErrorProne accepted any annotation named `Generated` whichever the package.

The fact that `javax.annotation.processing.Generated` has `SOURCE` retention is a real problem, leading to many code generators to come with their own `Generated` annotation with `CLASS` retention (like the now-defunct `javax.annotation.Generated`): Lombok, [Immutables](https://github.com/immutables/immutables/blob/e31f58d44612f2211679a07229a96d9ddf62aa7a/value-annotations/src/org/immutables/value/Generated.java#L22-L32), someone [asked it for jOOQ](https://github.com/jOOQ/jOOQ/issues/8617), someone else [for MapStruct](https://github.com/mapstruct/mapstruct/issues/1528), and I'm sure there are (many) others.

**Comment by cushon** [comment]
#1984 is a related bug about `org.immutables` (which I think is supposed to try to use the `javax.*` annotations if they're available, but doesn't seem to be doing that).

**Comment by cushon** [comment]
> It would actually be great if ErrorProne accepted any annotation named Generated whichever the package.

Done: https://github.com/google/error-prone/commit/4d6a0cce2d2ccc6a945352c2ba38201f753994bd

That doesn't solve all of our problems with lombok (see https://github.com/google/error-prone/issues/1250#issuecomment-763097162 for current thoughts on that), but it should be enough to recognize lombok's annotation in `-XepDisableWarningsInGeneratedCode`
