### ISSUE TITLE
RemoveUnusedImports is not working

### ISSUE THREAD

**Issue by cnarsimharaju** [google/error-prone#1893]
> ATTENTION! Please read and follow:

### Description of the problem / feature request:
We are planning to use errorprone with our service. We have a challenge with respect to removal of unused imports.

### Feature requests: what underlying problem are you trying to solve with this feature?
We want to use RemoveUnusedImports feature from ErrorProne. These are our pom.xml arguments. Even after the build the unused import are not removed.

 ` <arg>-Xplugin:ErrorProne -XepDisableAllChecks -Xep:RemoveUnusedImports -Xep:Piranha:WARN -XepPatchChecks:Piranha -XepPatchLocation:IN_PLACE -XepOpt:Piranha:FlagName=${SAMPLE_STALE_FLAG} -XepOpt:Piranha:IsTreated=true -XepOpt:Piranha:Config=${project.basedir}/src/main/resources/config/pirahana.json</arg>
    `                `

We tried on a vanilla spring boot application as well we are not seeing the removal of the unused import. We tried with the option of `-Xep:RemoveUnusedImports:ERROR` it is showing compilation error for unused import. These are the pluginInfo which we tried

`<plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId<version>3.8.0</version><configuration><source>8</source><target>8</target><compilerArgs><arg>-XDcompilePolicy=simple</arg><arg>-Xplugin:ErrorProne -Xep:RemoveUnusedImports:ERROR</arg></compilerArgs><annotationProcessorPaths><path><groupId>com.google.errorprone</groupId><artifactId>error_prone_core</artifactId><version>2.4.0</version></path></annotationProcessorPaths></configuration></plugin>
`
### What version of Error Prone are you using?
2.4.0

###  Have you found anything relevant by searching the web?

http://errorprone.info/docs/flags

>
> Places to look:
> - GitHub issues: https://github.com/google/error-prone/issues
> - email threads on https://groups.google.com/forum/#!forum/error-prone-discuss

**Comment by cushon** [comment]
> `-XepPatchChecks:Piranha`

I think you also need `-XepPatchChecks:RemoveUnusedImports` ?

The following simple example works for me:

```
javac -XDcompilePolicy=simple -processorpath error_prone_core-2.4.0-with-dependencies.jar:dataflow-shaded-3.1.2.jar:jFormatString-3.0.0.jar \
  '-Xplugin:ErrorProne -XepDisableAllChecks -Xep:RemoveUnusedImports -XepPatchChecks:RemoveUnusedImports -XepPatchLocation:IN_PLACE'  \
  Test.java
```

**Comment by cnarsimharaju** [comment]
Hey @cushon  Even after adding this property i could not see removal of unused imports. I could also see piranha is not working if i add this. We are integrating this with our micro-service which  uses maven for build.

**Comment by cushon** [comment]
> I could also see piranha is not working if i add this

I think I should have suggested `-XepPatchChecks:Piranha,RemoveUnusedImports` instead of passing ``-XepPatchChecks:` twice.

If `RemoveUnusedImports` still isn't working for you, can you provide a minimal, self-contained example that demonstrates the problem?

**Comment by cnarsimharaju** [comment]
Thanks @cushon  this option worked for me. The only challenge is it is taking 2 passes
1. In the first pass it removed my stale flag but imports are not imported.
2. In the second pass it removed the unused imports.

**Comment by cushon** [comment]
I think that's WAI: Error Prone checks run in parallel, they can't 'see' the code after it has been refactored by other checks. To use `RemoveUnusedImports` to clean up after another check it's necessary to run two serial passes.

(FWIW, the approach we use for cleaning up imports is to do that separately after applying fixes with a [formatter](https://github.com/google/google-java-format).)
