### ISSUE TITLE
Refaster crashes with NoSuchFieldException in Inliner on OpenJDK 11.0.9

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#1907]
### Description of the problem:

On OpenJDK 11, since the recent update to 11.0.9, running Refaster to build rules breaks with the following (shortened) stack trace:
```
    [javac] An exception has occurred in the compiler (11.0.9). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
    [javac] com.sun.tools.javac.util.ClientCodeException: java.lang.RuntimeException: Error analysing: copyOfSingletonList
    [javac] 	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:832)
[...]
    [javac] Caused by: java.lang.RuntimeException: Error analysing: copyOfSingletonList
    [javac] 	at com.google.errorprone.refaster.RefasterRuleBuilderScanner.visitMethod(RefasterRuleBuilderScanner.java:148)
[...]
    [javac] Caused by: java.lang.LinkageError: bound
    [javac] 	at com.google.errorprone.refaster.Inliner.setUpperBound(Inliner.java:246)
[...]
    [javac] Caused by: java.lang.NoSuchFieldException: bound
    [javac] 	at java.base/java.lang.Class.getField(Class.java:1999)
    [javac] 	at com.google.errorprone.refaster.Inliner.setUpperBound(Inliner.java:243)
    [javac] 	... 59 more
```

A full stack trace is [here](https://gitlab.com/sosy-lab/software/cpachecker/-/jobs/826479250#L294), but not important because the problem becomes obvious when looking at the source of `Inliner`:

https://github.com/google/error-prone/blob/1e2c8ac094d6d8b8c968f722d723800c5a79fb20/core/src/main/java/com/google/errorprone/refaster/Inliner.java#L239-L244

Thanks to @cushon for putting that link in the comment!

If we look at that [JDK bug](https://bugs.openjdk.java.net/browse/JDK-8193367), we can see it was fixed in Java 11.0.9 with [this change](https://hg.openjdk.java.net/jdk-updates/jdk11u/rev/796a0f3db99b#l1.23), which removes the field `bound`.

I think the best fix would be to always call `setUpperBound` first with a fallback to setting `bound` instead of a version check. Removing the access of `bound` completely would make Refaster fail or people still on OpenJDK <= 11.0.8.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run Refaster on OpenJDK 11.0.9. Not sure if it happens for all rules or only for our rule set, and I could provide a minimum example if necessary, but as explained above I think this is not necessary.

### What version of Error Prone are you using?

Error-prone 2.4.0, OpenJDK 11.0.9

It works on OpenJDK 11.0.8 and 14.0.2.

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/733d0212af52d621bb820415f7d446dae5352ca2
