### ISSUE TITLE
DeadException lint hides an error when the source file has multiple top-level classes.

### ISSUE THREAD

**Issue by kanapin** [google/error-prone#1920]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

DeadException lint hides an error when the source file has multiple top-level classes.

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Install bazel 3.7.0

2. Create a simple workspace

```
$ cat ./WORKSPACE

# empty file

$ cat ./BUILD

load("@rules_java//java:defs.bzl", "java_library")
java_library(
    name = "hello",
    srcs = ["HelloWorld.java"],
    javacopts = [
        "-Xep:DeadException:ERROR",
    ],
)

$ cat ./HelloWorld.java

public class HelloWorld {
  public static void main(String[] args) {
    new Exception("hey");
  }
}

class Foo {}

$ bazel build :hello

INFO: Analyzed target //:hello (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:hello up-to-date:
  bazel-bin/libhello.jar
INFO: Elapsed time: 0.204s, Critical Path: 0.08s
INFO: 2 processes: 1 internal, 1 worker.
INFO: Build completed successfully, 2 total actions
```

Note that if the line `class Foo {}` is removed, the DeadException is correctly reported.

### What version of Error Prone are you using?

Using bazel 3.7.0-homebrew

###  Have you found anything relevant by searching the web?

Nope.

**Comment by kanapin** [comment]
More details:

It looks like this happens with other lints like `SizeGreaterThanOrEqualsZero` if there are multiple top-level classes in the file.

**Comment by eaftan** [comment]
If you add `-XDcompilePolicy=byfile` to the javacopts for your `java_library`, does that fix the problem?

**Comment by kanapin** [comment]
Thanks – that fixed it!

**Comment by cushon** [comment]
Bazel now passes `-XDcompilePolicy=simple` by default (which also works around this): https://github.com/bazelbuild/bazel/issues/12270

This will be fixed in the next Bazel release.
