### ISSUE TITLE
MissingSummary warning doesn't include filename

### ISSUE THREAD

**Issue by pburka** [google/error-prone#1981]
### Description of the problem / feature request:

The MissingSummary warning doesn't include the name of the file that caused the warning.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cat foo/Foo.java
package foo;
/** */
public class Foo {}

$ javac -version -processorpath dataflow-shaded-3.1.2.jar:error_prone_core-2.4.0-with-dependencies.jar:jFormatString-3.0.0.jar:javac-9+181-r4173-1.jar:javacutil-2.5.7.jar:threeten-extra-1.5.0.jar -Xplugin:ErrorProne -XDcompilePolicy=byfile foo/Foo.java
javac 11.0.8
warning: [MissingSummary] A summary line is required on public/protected Javadocs.
    (see http://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
1 warning
```

### What version of Error Prone are you using?

2.4.0

### Expected behavior

The warning should include the name of the file and the relevant line number, if any, just like other warnings from error-prone. E.g.:

```
foo/Foo.java:2: warning: [MissingSummary] ...
```

**Comment by vitalyd** [comment]
Seems the necessary condition to tickle this bug is a completely empty javadoc stub (i.e. ```/** */```), as in @pburka's example, since most occurrences of this lint emit the file and line number.
