### ISSUE TITLE
Error Prone 2.5.0 release notes contain two broken links

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#2096]
Congratulations on the 2.5.0 release! Will give it a spin soon :tada: .

Just dropping a message to say that while reading the [release notes](https://github.com/google/error-prone/releases/tag/v2.5.0) I noticed two broken URLs:
- `DangerousLiteralNullChecker` shouldn't have the `Checker` suffix and link to [DangerousLiteralNull](http://errorprone.info/bugpattern/DangerousLiteralNull).
- `JavaUtilDateChecker` shouldn't have the `Checker` suffix and  link to [JavaUtilDate](http://errorprone.info/bugpattern/JavaUtilDate).

**Comment by cushon** [comment]
Thanks! The links are now fixed :)
