### ISSUE TITLE
Calling getClass on a variable of type Class

### ISSUE THREAD

**Issue by cushon** [google/error-prone#217]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=217) created by **fixpoint@google.com** on 2013-11-22 at 02:32 AM_

---

Have just encountered an instance of this (some details changed):

@﻿Provides
boolean provideEligibility(Class&lt;? extends Action&gt; action) {
&nbsp;&nbsp;return actionClass.getClass().getAnnotation(IsEligible.class) != null;
}

Calling getClass() on a Class can be substituted with Class.class for practically all cases with an improvement of readability.

**Comment by JeffreyFalgout** [comment]
Looks like this is done: https://github.com/google/error-prone/blob/master/core/src/main/java/com/google/errorprone/bugpatterns/GetClassOnClass.java

**Comment by cushon** [comment]
Yep, thanks. Resolved by 5a89046a4f1f9ce1f51d2e8e5021cb458ea18f65.
