### ISSUE TITLE
Check for arrays passed to Objects.hashCode()

### ISSUE THREAD

**Issue by cushon** [google/error-prone#218]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=218) created by **geb@google.com** on 2013-11-22 at 10:18 PM_

---

The javadoc for Objects.hashCode() contains the following:

"Note that array arguments to this method, with the exception of a single Object array, do not get any special handling; their hash codes are based on identity and not contents."

In other words, since an array's hashCode() method derives from Object.hashCode(), calling Object.hashCode(array) will yield the hash derived from the array's object reference. This is almost certainly not what the author intended: what they actually wanted was a hash derived from each of the array's elements. This can lead to subtle bugs because the hash code derived from the array is not stable; for example it can change if the array is recomputed.

The fix is to call Arrays.hashCode(array) instead. Hence I propose that whenever the analyzer detects Objects.hashCode() being called with a single array argument, it should suggest calling Arrays.hashCode() instead.

For motivation, see b/11825155 for an example bug which could have easily been avoided with this check. For the CL that implements the fix, see cl/57133395.

**Comment by eaftan** [comment]
This was fixed by 945244020a12e2143b50be4eb6f6a0dc89859627
