### ISSUE TITLE
UnusedMethod no longer works

### ISSUE THREAD

**Issue by anthonyvdotbe** [google/error-prone#2215]
### Description of the problem / feature request:

UnusedMethod doesn't detect unused methods.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. create a file `Test.java` with the following content:
```java
class Test {
    private static void unusedStatic() {
    }

    private void unused() {
    }
}
```
2. run ErrorProne (in this case, in PowerShell on Windows, with javac 15.0.1):
```
javac '-XDcompilePolicy=simple' '-processorpath' 'error_prone_core-2.5.1-with-dependencies.jar;dataflow-shaded-3.7.1.jar;jFormatString-3.0.0.jar' '-Xplugin:ErrorProne -Xep:DefaultPackage:OFF' Test.java
```
3. no errors occur

### What version of Error Prone are you using?

2.5.1

###  Have you found anything relevant by searching the web?

No.

**Comment by cushon** [comment]
I don't think this is a regression, it has had a heuristic that looks for methods that start with "unused" since a17a68eefa156bebe9280d82e342bee65a1d2d1e. We treat that as a suppression mechanism that documents methods that are deliberately unused.

**Comment by anthonyvdotbe** [comment]
@cushon My bad, I just wanted to verify my Maven setup worked, and adding unused method with these most original names was the first thing I came up with. I've filed a PR to document this mechanism.
