### ISSUE TITLE
CheckReturnValue and ReturnValueIgnored should disable checking on mocked objects

### ISSUE THREAD

**Issue by cushon** [google/error-prone#226]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=226) created by **eaftan@google.com** on 2014-01-15 at 12:04 AM_

---

Currently these checks will issue an error on code like:
Mockito.verify(mock).methodWithCheckReturnValue()

We should turn off the check for these cases.  Bonus points if we also disable it for comparable methods in other mocking frameworks like EasyMock and jMock.

**Comment by kluever** [comment]
Copying my notes from my internal email:

One issue I'm running into are people who are using Mockito to mock out return values for methods or to verify that a method has been called on a mock. For example:
    `doReturn(startTimeNs).when(fakeTicker).read();`
    `verify(ticker, times(2)).read();`

This prevents us from adding `@CRV` to `Ticker.read()` ...which really should have the the annotation I think.

I'm not sure what the best solution here is.  We could:
1) Not add `@CRV` to `Ticker.read()`
2) Spew `@SuppressWarnings("CheckReturnValue")` on the enclosing methods
3) Change the error prone checker to not enforce `@CRV` on mocked methods
4) Fix their tests some how? Is there a better/different way to write those calls using Mockito?


Liam said:
Option (3) shouldn't be hard. It's nice to avoid having to special case things, but I can't think of a better alternative here.
How many methods like doReturn and verify does mockito have? If there are a lot, maybe the check should ignore invocations of `@CRV` methods if the receiver is a call to any mockito method.


Peter said:
Re: your fourth point, in most cases you could rewrite the statement like this:
  `when(fakeTicker.read()).thenReturn(..);`
However I believe that this doesn't work with spies when you don't want the underlying method to be executed, here you still need the problematic syntax. So (3) seems like the nicest solution, and `Stubber.when()` should be the only method that causes this IIRC.

**Comment by cushon** [comment]
Fixed by 6804d6f006e1595247ff4dc67a19ab7f47daa808

**Comment by kluever** [comment]
We should consider adding support for Mockito's InOrder API as well (more details and examples on the internal b/24397431).
