### ISSUE TITLE
InvalidParam warning on Javadoc for Java record components

### ISSUE THREAD

**Issue by DenWav** [google/error-prone#2321]
### Description of the problem / feature request:

Javadoc on Java record components are `@param` tags on the record itself. It's also possible to override the accessor methods, but that shouldn't be necessary. error-prone produces an `InvalidParam` warning here though, as it doesn't seem to understand the Java record syntax.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```java
/**
 * Example record.
 * @param name Name of the example record.
 */
public record ExampleRecord(String name) {
}
```

### What version of Error Prone are you using?

`2.6.0`

**Comment by dododge** [comment]
Ran into this in 2.10.0 as well.

**Comment by grongor** [comment]
I can confirm that this is still an issue today, on 2.11.0.

**Comment by bkrieger** [comment]
@rickie I see you made a PR to fix this, but it’s against your fork. Do you plan to merge it into the main repo?

**Comment by rickie** [comment]
We have a process where we first review and verify the code in our own fork. Once we are satisfied with the quality we open a PR upstream. 

In other words, yes, we plan to open a PR for this in the main repository.

**Comment by bkrieger** [comment]
Thanks! Do you have an estimated timeline (trying to decide how much time we should spend on a workaround on our side)?

**Comment by rickie** [comment]
@bkrieger Opened https://github.com/google/error-prone/pull/3437 which contains a fix 😄.

**Comment by mmedum** [comment]
hey @rickie and @bkrieger, is there anything I can do to help move this along? It would be great to have working. @rickie do you miss anything on your fix at the moment?

**Comment by rickie** [comment]
I just rebased the branch and it's actually ready to be reviewed and merged by the Error Prone Team. Maybe @cushon or @graememorgan have some time to take a look at this?

**Comment by mmedum** [comment]
> I just rebased the branch and it's actually ready to be reviewed and merged by the Error Prone Team. Maybe @cushon or @graememorgan have some time to take a look at this?

Really awesome work @rickie :D
