### ISSUE TITLE
Prefer getNumber() to ordinal() on com.google.protobuf.ProtocolMessageEnum

### ISSUE THREAD

**Issue by cushon** [google/error-prone#237]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=237) created by **schwardo@google.com** on 2014-03-07 at 02:52 PM_

---

Enumerations specified in Protocol Buffers (https://code.google.com/p/protobuf/) are translated to subclasses of java.lang.Enum.  However, the numeric value specified in the protocol value does not map to the numeric value of the Java enumeration.  Instead, a getNumber() method is provided on the ProtocolMessageEnum interface, which provides access to the numeric value as specified in the .proto definition.

Any use of ordinal() on a class that implements ProtocolMessageEnum is probably a bug, and may lead to incorrect behavior.

**Comment by nglorioso** [comment]
This is done now as http://errorprone.info/bugpattern/ProtocolBufferOrdinal
