### ISSUE TITLE
[Java] A false negative about InvalidZoneId

### ISSUE THREAD

**Issue by Belle-PL** [google/error-prone#2431]
### Description of the problem / feature request

Hi, I found a false negative about [InvalidZoneId](https://errorprone.info/bugpattern/InvalidZoneId).

### Feature requests: what underlying problem are you trying to solve with this feature?

I used class ZoneId to generate a zone id, but error prone didn't report a warning when I input a wrong parameter. This problem can throw an exception and result in a runtime crash.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```java
public void testZoneId() {
    String str = "123";
    zoneId = ZoneId.of(str);  // Should report a warning here
}
```

### What version of Error Prone are you using?

> 2.7.1

**Comment by graememorgan** [comment]
`InvalidZoneId` only handles compile-time constants, which, (perhaps confusingly), that isn't.

While that case is certainly possible to catch at compile time by walking the tree and finding the value that the local is initialised to, it isn't possible to catch every possible crash.

**Comment by cushon** [comment]
This seems similar to #2414 and #2432
