### ISSUE TITLE
Malformed XML in Documentation: https://errorprone.info/docs/flags

### ISSUE THREAD

**Issue by atb-brown** [google/error-prone#2458]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Malformed XML in documentation
> 
> At this URL: https://errorprone.info/docs/flags
> 
> If you go near the bottom of the page and look at the XML under the `Maven` heading, there is some malformed XML
> 
> ```xml
> <project>
>   <build>
>     <plugins>
>       <plugin>
>         <artifactId>maven-compiler-plugin</artifactId>
>         <configuration>
>           <showWarnings>true</showWarnings>
>           <compilerArgs>
>             <arg>-XDcompilePolicy=simple</arg>
>             <arg>-Xplugin:ErrorProne -Xep:DeadException:WARN -Xep:GuardedBy:OFF</arg>
>           </compilerArgs>
>         </configuration>
>       </build>
>     </plugins>
>   </plugin>
> </project>
> ```

### Feature requests: what underlying problem are you trying to solve with this feature?

> Fix the malformed XML in the documentation. (Or point me to where I can try and fix it.)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Go to the url (https://errorprone.info/docs/flags) and scroll to the bottom.

### What version of Error Prone are you using?

> N/A

###  Have you found anything relevant by searching the web?

> No.
>
> Places to look:
> - GitHub issues: https://github.com/google/error-prone/issues
> - email threads on https://groups.google.com/forum/#!forum/error-prone-discuss

**Comment by Stephan202** [comment]
@atb-brown the documentation resides on the `gh-pages` branch. I filed #2459.
