### ISSUE TITLE
Full Java 8 support

### ISSUE THREAD

**Issue by cushon** [google/error-prone#246]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=246) created by **eaftan@google.com** on 2014-03-27 at 04:19 PM_

---

Right now we have a build for javac 8 but are missing two important items needed for full support:

1) Our Jenkins continuous build does not run Java 8 yet, only 6 and 7.

2) We don't yet distribute the error-prone 8 jars to Sonatype.  We probably want to distribute two sets of jars, one for versions 6 and 7, and one for 8.  It would be nice if Maven could figure out which dependency to use based on the version of javac installed.

**Comment by tbroyer** [comment]
But the maven plugin is another project that won't automatically update to 1.1.3 when it's released, right?

**Comment by TomDmitriev** [comment]
I don't understand why a new version of error-prone must be released along with a new version of the maven plugin either. What about other build tools, particularly gradle (https://github.com/tbroyer/gradle-errorprone-plugin)? Is there any additionaly work required for it to support error-prone 1.1.3?

**Comment by tbroyer** [comment]
@TomDmitriev Yes, there's some work needed: tbroyer/gradle-errorprone-plugin#6, but that's another story (also, we should avoid putting `tools.jar` in the classpath, or move it at the end so it doesn't conflict with the javac bundled into errorprone; this is probably what needs to be changed in the maven plugin too, the difference there being that the plugin is tied to a specific –though overridable– version of errorprone, contrary to the gradle plugin).

@eaftan It looks like the error_prone_core.jar (built locally) contains much more classes than necessary (junit? javax.tools?)

**Comment by tbroyer** [comment]
@eaftan Actually, `error_prone_core` has to be in the bootclasspath or the classloader needs a custom `loadClass` when not running Java 8, as at some point `com.sun.tools.javac.file.Locations` (from `error_prone_core`) tries to access `javax.tools.StandardLocation.NATIVE_HEADER_OUTPUT` which only exists since Java 8 and will be loaded from the current JVM (default classloader priority). If the shaded dependencies could be moved into their own package, that would prevent such conflicts; not sure if it's feasible though.

**Comment by cushon** [comment]
We'll update the maven plugin once 1.1.3 is out.

There are a couple of alternatives to putting javac on the bootclasspath or doing custom classloading, but they have disadvantages. Repackaging the dependencies under `javax.tools.*` prevents error-prone from working with code that invokes javac programmatically, and breaks annotation processors. We could patch javac8 to work with jdk7 (e.g. using reflection for the enum values added in 8), but that gets hacky and also causes problems for annotation processors.

**Comment by cushon** [comment]
@eaftan pushed a new release (2.0) to maven, and I have fixes in progress for the maven and ant integrations:

- sonatype/plexus-compiler#31
- #290 

@tbroyer - the issue with `error_prone_core` bundling all of its deps has been fixed: 4b323a3f4c57cd2b3bc2c6b15d9353c74c105b6e. The classloading hackery required to run javac8 on JDK7 is definitely annoying, but I don't have a better alternative yet.

**Comment by tbroyer** [comment]
@cushon - Thanks, I made similar changes to the gradle-errorprone-plugin: tbroyer/gradle-errorprone-plugin@4cf8096f44786d57e3c9de89166a39bd77a86af1 (I however went as far as trying to make the classloader "correct" wrt resources ;-) )

**Comment by cushon** [comment]
@tbroyer - great, thanks. And nice catch re: resources. Was that just to be thorough, or does it fix a problem you saw? I didn't think the javac.jar/rt.jar overlap affected any resources.

**Comment by tbroyer** [comment]
@cushon - just to be thorough.

Note: I have errors using the plugin in a multi module project. Haven't had time to investigate yet. I get unknown symbol errors when referencing classes from other modules in the project.

**Comment by cushon** [comment]
If you have a repro, we can try to investigate. That sounds like it might require more knowledge of gradle / classloading than error-prone, though.

When javac is invoked programatically it can pick up classes from the 'ambient' classpath and add them to the compilation classpath. Maybe multi module builds were previously relying on that, and the new classloader broke them? If that's the problem, setting the compilation classpath explicitly should still work.

**Comment by tbroyer** [comment]
OK, the problem is that in the first module, one class is not output: errorprone is passed the `.java` file as input (and other classes depend on it so it's correctly taken into account) but there's no `.class` file in the output directory. I'll try to create a repro case.

**Comment by tbroyer** [comment]
And the problem is apparently only triggered by classes named `Token` (and probably others). Here's the smallest repro-case I could come up with: https://gist.github.com/tbroyer/b087c7151d6da4a774fc

**Comment by cushon** [comment]
Thanks for the nice repro. This was entirely an errorprone bug, should be fixed by 1f912d223295f55acca7456e46eea2a035e4629a. Let me know if that doesn't do it.

There's some duplication right now between the internal and open source integration, and we didn't catch this earlier because it's only present on the open source side. I'm working on removing some of that duplication (and cleaning up the error-prone/javac integration in general), which should make bugs like this less likely.

**Comment by tbroyer** [comment]
:+1: that fixes it! Waiting for that 2.0.1 release now ;-)

**Comment by cushon** [comment]
I just pushed 2.0.1.

**Comment by tbroyer** [comment]
Great, thanks!
