### ISSUE TITLE
ErrorProne's JodaDurationConstructor is not a valid checker name

### ISSUE THREAD

**Issue by piotrdzz** [google/error-prone#2483]
Hello, 
I am using errorProne 2.8.1 and with 
-Xep:JodaDurationConstructor:ERROR
it throws an error: 

>  JodaDurationConstructor is not a valid checker name

With 2.3.4 it works fine. 
I couldn't find an information that this flag got deprecated. 
Should this really not be used or is it a bug ? 

Also, I am using maven with java 8 and maven-compiler-plugin (3.8.0) and with forked=false compilation just fails with "unknown compilation error" (which is expected to just not work in that mode) and with forked=true it fails with "compilation error", but the exact error is nowhere to be found, even with -X flag. 
The only way I found this error is running error-prone plugin in Intellij which gets its output outside. 
Is there an issue with error-prone errors being pushed to stdout when run via maven-compile plugin with forked=true?

**Comment by cushon** [comment]
The check was deleted in https://github.com/google/error-prone/commit/c2f4360a3172aad95f85d6751f8967e2e7c184ae.

It has been replaced by `JodaConstructors`.

**Comment by piotrdzz** [comment]
@cushon maybe it is worth to mention it in 
https://errorprone.info/bugpattern/JodaDurationConstructor
because this is where user will go at first, 
Thanks for reply!

**Comment by cushon** [comment]
Ah, thanks. The script that generates the docs isn't deleting pages for checks that have been removed. I manually pushed an update and will fix the script to remove stale pages automatically.
