### ISSUE TITLE
Release notes for Error Prone 2.8.1

### ISSUE THREAD

**Issue by joschi** [google/error-prone#2502]
The release notes for Error Prone 2.8.1 seem to be missing: https://github.com/google/error-prone/releases/tag/v2.8.1

It would be great if there was a description of changes between Error Prone 2.8.0 and 2.8.1 in the release notes:
https://github.com/google/error-prone/compare/v2.8.0...v2.8.1

**Comment by cushon** [comment]
Done, thanks. There much new in 2.8.1, the release was partly to verify a change to the maven configuration we're using to push releases to sonatype.
