### ISSUE TITLE
BugPattern: SameNameButDifferent

### ISSUE THREAD

**Issue by aparnamitra97** [google/error-prone#2526]
[ERROR]      error-prone version: 2.6.0
[ERROR]      BugPattern: SameNameButDifferent
[ERROR]      Stack Trace:
[ERROR]      java.lang.IllegalArgumentException: Replacement{range=[685..693), replaceWith=ImmutableSet.@Builder} conflicts with existing replacement Replacement{range=[685..693), replaceWith=ServerStreamTracer.@Builder}

**Comment by cushon** [comment]
This might be #2273.

Are you using lombok? Do you have a self-contained example that reproduces the crash?
