### ISSUE TITLE
Additional no match cases for EmptyCatch

### ISSUE THREAD

**Issue by Donnerbart** [google/error-prone#2565]
I would kindly ask to re-open and merge [this PR](https://github.com/google/error-prone/pull/1726). It was linked into the [last issue](https://github.com/google/error-prone/issues/1654) regarding this topic, but closed without any comment. Maybe it was auto-closed due to the `Fixes #1654` when that issue was closed?

Using `ignored` as parameter name is the default way to suppress the empty catch warning in IntelliJ, so this is widely adapted. It would be great to support this case to remove a ton of unwanted warnings.

Are there any objections in applying this change?
If there is consensus, can the old PR be re-used or does it need to be re-created?

**Comment by cushon** [comment]
I think this is why the PR was closed: https://github.com/google/error-prone/issues/1654#issuecomment-661190637

**Comment by Donnerbart** [comment]
Oh, I actually misread the style guide as in "parameter is ..." _or_ there is a comment.

Okay, then this will probably not be "fixed". Thanks for the clarification.
