### ISSUE TITLE
Use ArrayDeque instead of LinkedList or Stack

### ISSUE THREAD

**Issue by cushon** [google/error-prone#257]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=257) created by **joebowbeer@google.com** on 2014-06-24 at 09:56 PM_

---

Detect use of java.util.LinkedList and java.util.Stack.

Use of java.util.LinkedList should be discouraged. ArrayList is almost always a better choice than LinkedList. For queue-like behavior, ArrayDeque is the best choice.

Use of Stack, which is based on LinkedList, is best replaced by ArrayDeque.

This check should (1) locate instances of LinkedList and encourage replacing them with ArrayList or ArrayDeque, and (2) locate instances of Stack and encourage replacing them with ArrayDeque.

There are no negative cases.

**Comment by godmar** [comment]
FWIW, Stack is not based on LinkedList, it is based on Vector.

**Comment by mmoayyed** [comment]
Ran into a glitch with this warning: if you are dealing with a library that explicitly wants you to pass a linked-list to a method, you are then forced to create that linked-list; there is no way to turn off warnings only for that piece of code or section of the codebase.

**Comment by msridhar** [comment]
@mmoayyed can't you do `@SuppressWarnings("JdkObsolete")` on the method that is calling into the library?

**Comment by mmoayyed** [comment]
Thank you. That did the trick. I looked around for a while prior to posting and it didnt seem like the compiler had a way of accepting ignore-rules via annotations. Nice to see this is supported. Sorry about the noise :)
