### ISSUE TITLE
snapshots not deployed since August 2nd

### ISSUE THREAD

**Issue by gemmellr** [google/error-prone#2588]
The last deployed snapshot is nearing a couple months old, published on August 2nd. The CI jobs show it has been failing deploy since with "401 Unauthorized".

This likely isnt as obvious as it normally is due to having a fixed version (#2108), meaning that a snapshot still exists and didnt go away despite a release being done weeks later, and also masking that none have actually been deployed since [before] that release.

**Comment by cushon** [comment]
Thanks, I think this was broken by fb208dddb4346f74a95d4af34d366838a61003d0, I'll take a look

**Comment by gemmellr** [comment]
Seems likely, as the server id was changed there but not at https://github.com/google/error-prone/blob/872cbf58c65d5dff77feef26b3805877f66f7cbb/.github/workflows/ci.yml#L72

**Comment by cushon** [comment]
I think this is fixed now, e.g. https://oss.sonatype.org/content/repositories/snapshots/com/google/errorprone/error_prone_core/HEAD-SNAPSHOT/error_prone_core-HEAD-20211001.202552-286.jar
