### ISSUE TITLE
Add module-info.java

### ISSUE THREAD

**Issue by cowwoc** [google/error-prone#2649]
JPMS users who depend on this library get the following build warning:

`[WARNING] requires transitive directive for an automatic module`

Can you please publish a multi-release or exclusive JAR with `module-info` for users of Java 9+?

**Comment by cushon** [comment]
A couple of notes:

We only support JDK 11 and newer at this point, so we could add a module-info without the need for multi-release jars.

The annotations jar is now using `Automatic-Module-Name`: https://github.com/google/error-prone/commit/5793bcac8edcd6f3ae781b2a2511a6dab4fb1ba1

**Comment by sgammon** [comment]
@cowwoc There's a PR for this now at #4311.

**Comment by cushon** [comment]
I think a little more work is needed here: https://github.com/google/error-prone/pull/4314
