### ISSUE TITLE
UnusedVariable check raises false positives for APIs that are intended to be used reflectively

### ISSUE THREAD

**Issue by TheNeuralBit** [google/error-prone#2668]
In Apache Beam we have a few annotations that are used reflectively, like [`TimerId`](https://beam.apache.org/releases/javadoc/2.33.0/org/apache/beam/sdk/transforms/DoFn.TimerId.html), and [`StateId`](https://beam.apache.org/releases/javadoc/2.33.0/org/apache/beam/sdk/transforms/DoFn.StateId.html). A contributor is currently working on enabling the errorprone UnusedVariable check, but to get it passing they have to suppress the warning on every usage of `TimerId` and `StateId`: https://github.com/apache/beam/pull/15742#discussion_r745201100

Can a feature be added to errorprone that enables us to suppress this warning for variables that are annotated with these annotations?

**Comment by cushon** [comment]
I'd by happy to take a PR to add those annotations here, which will disable `UnusedVariable` findings for variables with those annotations: https://github.com/google/error-prone/blob/f68b6270c2f8563ac642ecf6ff6365b09c2f4261/core/src/main/java/com/google/errorprone/bugpatterns/UnusedVariable.java#L127

That check also has a couple of flags to configure exemptions, we should add one to allow configuring additional variable annotations without having to update the hard-coded list: https://github.com/google/error-prone/blob/f68b6270c2f8563ac642ecf6ff6365b09c2f4261/core/src/main/java/com/google/errorprone/bugpatterns/UnusedVariable.java#L156
