### ISSUE TITLE
Extend Nullness enum to distinguish between NONNULL and NONNULL_LIKELY_TO_BE_BELIEVED_NULLABLE

### ISSUE THREAD

**Issue by cpovirk** [google/error-prone#271]
The goal here is basically to expand on the work started on #85. One of the challenges of getting that right is that users don't necessarily write a "direct" null check:

```
if (multimap.get(key) == null) { ... }
```

Instead, they may assign to a variable and then compare:

```
List<Foo> values = multimap.get(key);
if (values == null) { ... }
```

error-prone could still catch the latter problem, but it would require dataflow.

I'm a little concerned, though, that flagging every null check of a non-null value will be too noisy. I mean, in theory I'd like for my code not to perform these checks (and I think I just saw a CL by Eddie to eliminate a few -- thanks!), but a lot of them are going to be harmless -- certainly lots of `checkNotNull` calls, at least. Maybe `if (foo == null)` will be a higher-quality signal, especially if we exclude cases that just return or throw in the null case.

One possible way to further improve the quality of the signal is to focus the check on non-null values that we already know users like to null check -- like protocol buffer getters and Multimaps.get (#85). To make this work, we'd need to expand the `Nullness` enum to distinguish between "Yeah, it's non-null, but who cares if the user null checks it?" and "It's non-null, and if the user thinks it might be null, he probably should be checking `hasFoo` or for an empty string or collection instead."

**Comment by cushon** [comment]
Notes from the last bug triage:

- Generalizing `ProtoFieldNullComparison` and `ProtoFieldPreconditionsCheckNotNull` into a check for non-null things with `has()` methods sounds good. It would require flowing more information through the nullness analysis - we need provenance information to know that a value being null-checked came from, e.g. a proto field.

- A more general unnecessary null-check analysis would be worth evaluating as a warning.
