### ISSUE TITLE
Unhandled exceptions running ArgumentSelectionDefectChecker

### ISSUE THREAD

**Issue by TheNeuralBit** [google/error-prone#2745]
I ran into three unhandled exceptions when running the ArgumentSelectionDefectChecker on Apache Beam code.

I uploaded the stacktraces [here](https://gist.github.com/TheNeuralBit/4a0e623e5d3356b0cd68cc8bc41234dc). The RingRange.java error showed up in error-prone 2.6.0, and the others just showed up in 2.10.0.

**Comment by cushon** [comment]
It looks like it's seeing an older version of Guava:

```
     java.lang.NoSuchMethodError: 'java.util.stream.Stream com.google.common.base.Splitter.splitToStream(java.lang.CharSequence)'
```

The fix is probably to upgrade the version of Guava on the processor path for this build.

**Comment by TheNeuralBit** [comment]
Perhaps a newer version? Beam uses 31.0.1-jre, which it looks like error-prone just upgraded to: https://github.com/google/error-prone/commit/bf9331891b3f046bfc662a8ef04b88332bac6211

**Comment by cushon** [comment]
I think `splitToString` was added in 28.2.

Does the build use other annotation processors? It's possible one of them is pulling in an older version of guava.

**Comment by TheNeuralBit** [comment]
Yeah we do use other annotation processors (Auto, checkerframework). It does look like guava is being downgraded in the processor path for some projects in Beam:

```
+--- com.google.errorprone:error_prone_core:2.10.0
|    +--- com.google.errorprone:error_prone_annotation:2.10.0
|    |    \--- com.google.guava:guava:30.1-jre -> 25.1-jre (*)
|    +--- com.google.errorprone:error_prone_type_annotations:2.10.0
|    +--- com.google.errorprone:error_prone_check_api:2.10.0
|    |    +--- com.google.errorprone:error_prone_annotation:2.10.0 (*)
|    |    +--- com.google.code.findbugs:jsr305:3.0.0 -> 3.0.2
|    |    +--- org.checkerframework:dataflow-errorprone:3.15.0
|    |    +--- io.github.java-diff-utils:java-diff-utils:4.0
|    |    |    \--- org.eclipse.jgit:org.eclipse.jgit:4.4.1.201607150455-r
|    |    +--- com.google.auto.value:auto-value-annotations:1.7 -> 1.8.2
|    |    +--- com.google.errorprone:error_prone_annotations:2.10.0
|    |    +--- com.github.kevinstern:software-and-algorithms:1.0
|    |    \--- com.github.ben-manes.caffeine:caffeine:2.8.8
|    |         +--- org.checkerframework:checker-qual:3.8.0 -> 3.10.0
|    |         \--- com.google.errorprone:error_prone_annotations:2.4.0 -> 2.10.0
|    +--- org.pcollections:pcollections:2.1.2
|    +--- com.google.guava:guava:30.1-jre -> 25.1-jre (*)
```

I'll track down why that's happening. Thanks for the help!

**Comment by Stephan202** [comment]
@TheNeuralBit the "culprit" is very likely Auto; see https://github.com/google/error-prone/issues/2138#issuecomment-766314550 for some more context. (Since then Auto's dependencies on Guava have been updated, so I expect that simply upgrading Auto will also resolve the issue.)

**Comment by TheNeuralBit** [comment]
Thanks @Stephan202, I'm not well versed in gradle dependency resolution, but (with the help of your link) it looks like the Beam projects that don't fail are the ones that have some other compile/test dependency on guava 31.0.1-jre.

Bumping autoservice to 1.0.1 resolves it for all projects.

**Comment by TheNeuralBit** [comment]
It turns out we also had a couple of projects that were forcing an older guava ([BEAM-11626](https://issues.apache.org/jira/browse/BEAM-11626)) needed for transitive dependencies. Unfortunately it's most convenient to pin a dependency for _all_ configurations, including annotation processing, which is what we did.

I'm able to resolve it by modifying our build to skip the annotation processing configuration when pinning an old guava
