### ISSUE TITLE
Support @CheckReturnValue on package or class -- with ability to override

### ISSUE THREAD

**Issue by cpovirk** [google/error-prone#276]
We've occasionally discussed adding `@CheckReturnValue` to classes in Guava. (For example, see internal bugs 5770914, 9072648, 12560901, and 17205818, two of which link to example misuses.) A big part of what's stopped us is that we would want to add it to a large fraction of our methods -- certainly a majority of methods in some classes, and probably a majority overall. This is noisy. Compare the situation with `@Nonnull` parameters. Because they are so common, we have the package- and class-level `@ParametersAreNonnullByDefault`. Could we have a package- and class-level `@MethodsAreCheckReturnValueByDefault`? Actually, surprise: `@CheckReturnValue` can be applied to packages and classes already, so in theory error-prone could support it now. The trick, I suspect, will be in permitting individual methods or classes to override it. Currently there is no `@NeedNotCheckReturnValue` annotation (and IIRC there is uncertainty over whether these kinds of annotations would live -- error-prone? a separate google-annotations project?). I propose adding one someday, after which Guava can add a relatively small number of annotations to cover a large number of methods.

**Comment by kluever** [comment]
Big +1 to allowing @CheckReturnValue to be the default on a package or class level. I think the reason we have avoided adding @CRV, is because we'd need to spam it in so many places that it'd become too noisy.

I love @CRV and wish we could have it everywhere. It catches *real* bugs all the time, so I wish we could have it on by default.

**Comment by alexeagle** [comment]
Of course there's a big advantage to adding @CRV one method at a time: you
can fix the existing occurrences as you roll out each one. It's probably
hard to get a large codebase clean of ignoring return values from all the
methods in a whole package so that you can make it a compile error without
breaking anyone.

**Comment by kluever** [comment]
Sure - I'd use `@CheckReturnValue` on the often-misused-methods to incrementally clean up the code base, and then once I got the number of failures down to a reasonable amount, I'd slap it on the entire package.

However, applying it on the class-level lets us do this at a slightly bigger scale than method level, but smaller scale than package level.  If we had all 3 options, we could easily make incremental progress until we're ready to slap it on the entire package.

**Comment by cushon** [comment]
Does it still look like supporting `@CheckReturnValue` on classes and packages would be useful even without a way to suppress the error for specific methods?

Aside from Eddie's concerns and having to find a place for that annotation to live, I'm not sure what a reasonable name would be.

**Comment by kluever** [comment]
I think supporting it on the class-level would be OK w/o the inverse annotation, but I'm not sure we could get away with it for an entire package.

If we had class-level support, we could add it to all of our classes, except the ones where they had >0 methods that would need the inverse annotation. On those classes, we could just add the method-level annotation to the individual methods (not great, but not the end of the world).

So if I had to order the priority from highest to lowest, I'd order them:
a) class-level support for @CheckReturnValue
b) inverse annotation @IgnorableReturnValue (or whatever we call it)
c) package-level support for @CheckReturnValue

**Comment by cpovirk** [comment]
For naming, how about "`@CanIgnoreReturnValue`?"

Even without support for that, I think we could add the class-level annotation to:

- `Collections2`
- `Multimaps`
- `ObjectArrays`
- `Sets`
- `Tables`

Sadly, adding it to just those classes would have caught only ~1 of the many bugs reported on https://github.com/google/guava/issues/1931. That's because the more commonly abused methods seem to be on classes that are only _mostly_ `@CheckReturnValue`. We can of course still annotate their individual methods; it's just a question of noise -- and, I suppose, of remembering to do it on new methods.

We could add the class-level annotation in a couple other classes if we were willing to migrate some unusual users off certain of those classes' methods:

- `Maps`: Some people call `uniqueIndex` for its side effect of throwing an exception for duplicates. Adding `@CheckReturnValue` would catch only ~1 bug (where someone wrote `newHashMap()` instead of `return newHashMap()`, which luckily was only an optimization in that code).
- `Lists`: Some people call `newArrayList` for its side effect of iterating over the input list to see if the iterator throws exceptions. Adding `@CheckReturnValue` would catch numerous bugs (one `Lists.transform` call and many `Lists.reverse` calls). (We've just added `@CheckReturnValue` to `Lists.reverse` specifically.)

**Comment by cpovirk** [comment]
To frame things a different way: Today, our options are:

- Annotate only the methods that are likely to be misused. But I wouldn't necessarily have predicted which methods would be misused. `Lists.reverse`, sure. But `Futures.immediateFuture`? I could also believe that users would be confused by our inconsistency in annotating methods... but I doubt that that's a huge concern.

- Annotate all eligible methods. This is verbose, and it's likely that we'll forget on some new methods. (To remind us, we could probably hack up some tests that check the non-`@CheckReturnValue` methods against a whitelist or something.)

`@CanIgnoreReturnValue` would give us the best of both worlds¹. But I'd have a hard time justifying an error-prone-annotations project solely on those grounds.

¹ Well, unless we mix `@CheckReturnValue`-by-default and non-`@CheckReturnValue`-by-default *classes*, in which case users who don't know about using the annotation on a whole class might still be confused by "inconsistency." And it seems likely enough that we indeed mix them, given that users often don't care about the return values of collection methods like `add` and `remove`.

**Comment by cushon** [comment]
I'll add support for classes/packages - that part's easy, and has some value by itself.

There's been talk of creating an error-prone-annotations project for a while, so maybe this will finally provide the impetus. Naming the inverse annotation `@CanIgnoreReturnValue` sounds good to me. I want to understand @eaftan's concerns first, though.

**Comment by cushon** [comment]
Fixed in 2384e2435f19a5c370f7f76cca96e7e4c52f6637.

**Comment by cpovirk** [comment]
Would you like a separate bug for `@CanIgnoreReturnValue`?

**Comment by cushon** [comment]
> Would you like a separate bug for @CanIgnoreReturnValue?

Yes, please do.

**Comment by cpovirk** [comment]
Thanks. Filed #279.

**Comment by LemmingAvalanche** [comment]
Hi.  This mentions constructors.  I tried to use this on a constructor but it behaves the same way as Java’s annotation.  I don’t get a warning in Intellij when a constructor is called without being used.  Is that correct or am I confused?

**Comment by sdeleuze** [comment]
@LemmingAvalanche See https://youtrack.jetbrains.com/issue/IDEA-374480/Support-CheckReturnValue-on-types-constructors-and-packages.
