### ISSUE TITLE
Use of YYYY instead of yyyy in SimpleDateFormat

### ISSUE THREAD

**Issue by cpovirk** [google/error-prone#277]
via https://publicobject.com/2014/12/29/yyyy/ and https://twitter.com/dohzya/status/549402624730988544

(I assume that this also applies to the 2-digit forms, "YY" vs. "yy," though I haven't checked.)

"YYYY" is the "week year," which can end before the normal year. Callers almost certainly want "yyyy" unless they are using 'w' to include the "week of year." (I suppose I could see an argument that a bare "YYYY" might be OK, if only because it would be annoying for users if they couldn't print "YYYY" for testing purposes. If so, a reasonable conservative heuristic would be whether the user is also including "MM" or "MMM" to get the month. But perhaps it's best to flag this in all cases, especially if it is only a warning.)

I see 11 instances of YYYY/YY in Google internal code. (Search for `'new SimpleDateFormat[(]\042[^\042]*YY'`.) Only one caller appears to want it (because it also uses "ww").

http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

**Comment by cushon** [comment]
Fixed in 5ea72787ddbf4e763858a2b7221c957c0e22c955.
