### ISSUE TITLE
Is errorprone's javac still needed?

### ISSUE THREAD

**Issue by mattnelson** [google/error-prone#2783]
The javac version is defined[^1] and included[^2] in the latest releases. I thought with the switch to recommending usage as an annotation processor instead of the bootclasspath[^3] the errorprone version of javac would no longer be needed. This doesn't appear to be causing any issues. I also cloned the project and built/used it with that dependency removed without issue. The only minor issue I see with leaving it in, is downloading the jar unnecessarily and putting it on the compiler classpath.

[^1]: https://github.com/google/error-prone/blob/d7e9a8322d6aad22be13c808c16e43dbe48f6ee8/pom.xml#L35
[^2]: https://github.com/google/error-prone/search?l=Maven+POM&q=javac
[^3]: https://github.com/google/error-prone/blob/f8e33bc460be82ab22256a7ef8b979d7a2cacaba/docs/installation.md#jdk-8

**Comment by tbroyer** [comment]
ErrorProne's javac is still needed in the bootstrap classpath for Java 8, and having it as a dependency makes it easier to configure Maven projects (you can use the path to the jar and be sure it'll be there because if that declared dependency).

I otherwise agree it's not needed in the processor path, and in the Gradle plugin I explicitly exclude it (so you won't download it unnecessarily).

**Comment by mattnelson** [comment]
> ErrorProne's javac is still needed in the bootstrap classpath for Java 8

The docs were recently updated to remove all the mentions of bootclasspath > https://github.com/google/error-prone/commit/56bc34f5409c58f32959662b41217225fa05fd2c

So I think it means that javac could be removed in the next release.

> and in the Gradle plugin I explicitly exclude it

That is partially why I logged this issue. I could not find an option to apply exclusions for annotation processor paths in the maven-compiler-plugin.

**Comment by cushon** [comment]
The plan is to increase the minimum supported JDK version to 11 in the next release: https://github.com/google/error-prone/issues/2730

I had just forgotten to clean up the references to `error-prone-javac` in the `pom` files, I'll put together a change for that.
