### ISSUE TITLE
Documentation mentions JDK 16

### ISSUE THREAD

**Issue by mernst** [google/error-prone#2784]
https://errorprone.info/docs/installation mentions JDK 16.
I think one occurrence should be changed to "JDK 16+", and two occurrences should be changed to "JDK 17".
Or, because JDK 16 is no longer supported, all could be changed to "JDK 17".

**Comment by cushon** [comment]
Thanks, I'll clarify that it's JDK 16 and newer, not specifically 16.

I think I'm also going to merge the documentation about `--add-exports=` into the main examples, instead of having two examples for maven and ant.

**Comment by cushon** [comment]
0c49dc1d311b3e60f9c9717f2826401caa8b9ea1
