### ISSUE TITLE
UnicodeEscape should not apply in comments

### ISSUE THREAD

**Issue by anuraaga** [google/error-prone#2803]
Currently `UnicodeEscape` fails for values in comments that are describing a non-escaped character. This should probably be allowed as the safety issues don't seem to apply when not resulting in bytecode. The comments are to clarify what part of the code is implementing a specification (w3c trace context) which is defined using the escape literals.

https://github.com/open-telemetry/opentelemetry-java/blob/e65567d7ac09e0f739f60ac4e54961eb031cbf7c/api/all/src/main/java/io/opentelemetry/api/trace/ArrayBasedTraceStateBuilder.java#L168

**Comment by anuraaga** [comment]
By the way if UnicodeEscape is intended to apply in comments, then a different bug is for some reason I couldn't `@SuppressWarnings` it, I have a feeling the location within comments may be tricking up the suppression logic.

https://github.com/open-telemetry/opentelemetry-java/pull/4048/files#diff-b7f53d9b1b939361930a5972a2109b667ab488cd73ccf973f9fd277c5352d221R74

**Comment by graememorgan** [comment]
> the safety issues don't seem to apply when not resulting in bytecode

I don't think that's the case. You could insert Unicode escapes for "*" or "/" and really obfuscate the beginning and end of your comment.

I'm not really sure what the comment in that example is trying to achieve, but the code could be replaced with `value.charAt(value.length() - 1) == (char) 0x20` or somesuch.
