### ISSUE TITLE
One-shot static compilation method without exit

### ISSUE THREAD

**Issue by JakeWharton** [google/error-prone#284]
In integration with our tooling it would be convenient to have a one-shot static method to perform compilation. Invoking `main` results in `System.exit` being called. Normally I would just add a `compile` overload which only took a `String[]` (#283), but that conflicts with the instance method of the same signature.

This isn't a must-have, of course. I can continue invoking the builder or just pass my own wrapper around `System.err` as a second argument to the existing static method, but it'd be nice.

Some alternatives:

 * Change the static helpers to `compileForResult` (or something) to more accurately describe what they do.
 * Change the instance `compile(String[])` method to be named `run`, `execute`, etc. Not sure how set-in-stone this method is. My guess would be "very" though :)

Thoughts?

**Comment by cushon** [comment]
Renaming to `run` SGTM. It's not very set-in-stone :)

Our internal integration mostly uses the Scanner class directly.

**Comment by JakeWharton** [comment]
Ok! I'll send a PR shortly.
