### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by paulwoods222** [google/error-prone#2927]
error-prone version: 2.11.0
     BugPattern: FallThrough
     Stack Trace:
     java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because the return value of "com.sun.source.tree.CaseTree.getStatements()" is null

Java 17
 switch (onEnum) {

            case A: {
             //
                break;
            }
            case B: {
               //
                break;
            }
            case C:
                switch (AnotherEnum) {
   Throws Here?-->                 case AA: {
                       //
                        break;
                    }
                    case BB: {
                       //
                        break;
                    }
                    case CC: {
                      //
                        break;
                    }
                    case DD: {
                       
                        switch (ThirdEnum) {
                            case AAA -> {
                              
                            }
                            case BBB -> {
                                
                            }
                            case CCC -> {
                               
                            }
                            default ->
                                //
                        }

                        break;
                    }
                    default: {
                       //
                        break;
                    }
                }
                break;
            case D: {

                switch (AnotherEnum) {
                    case AA: {
                      //
                        break;
                    }
                    case BB: {
                       //
                        break;
                    }
                    default: {
                       //
                    }
                }
                break;

            }
            case E: {
               //
                break;
            }
            case F: {
            //
                break;
            }
            default:
                //
                break;
        }

**Comment by paulwoods222** [comment]
Probably fixed by https://github.com/typetools/checker-framework/commit/17dbf44f0b76ff3e7428647d8321ff22e11ffa35#diff-4d628494d4b6ab7954b6af427185f072ad43b36154808fc9ed450ee77ec66a68L2193-R2238 ?

**Comment by cushon** [comment]
Yes we need to upgrade to the latest version of dataflow, but there were a couple of API changes I didn't have time to investigate and it didn't quite make it into 2.11.0

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/d18c02f47eb57d662cc6163d7a5ddaac0bd5f11d
