### ISSUE TITLE
@ForOverride should support package private methods

### ISSUE THREAD

**Issue by lukesandberg** [google/error-prone#302]
MyClass.java:132: error: [ForOverride] Method annotated @ForOverride must have 'protected' visibility
  @ForOverride abstract int someMethod();

i don't want to have to increase the visibility of my method just so i can be sure that people don't call it.  I guess the theory is that package private methods are easier to check manually?

**Comment by eaftan** [comment]
@kevinb9n @kluever 

@ForOverride was intended to mark API methods that are there only to be overridden, and to prevent them from being called directly.  If the method doesn't have protected visibility, subclasses in other packages cannot override the method.  Is your use case that all subclasses are in the same package?  In that case package-private visibility would be OK as well.

**Comment by eaftan** [comment]
I don't see a problem with allowing package private @ForOverride methods, but I'd like to hear if Kevin or Kurt have any objections.

**Comment by eaftan** [comment]
Just talked to @kevinb9n offline, and we don't see a problem with allowing this. We think the restriction to protected was a leftover from when we were considering allowing other classes in the same package to call a @ForOverride method, but we ended up not doing that.  

I'll send a change for this.
