### ISSUE TITLE
Check for generics on calls to non-generic methods/constructors

### ISSUE THREAD

**Issue by cgdecker** [google/error-prone#307]
A recent [StackOverflow question](http://stackoverflow.com/questions/29015880/looking-for-java-1-6-workaround-to-apparent-compiler-issue) reminded me of the very strange fact that it's possible to provide (any number of!) generic type arguments to a non-generic method or constructor.

For example:

    // Like in the question
    Cache<Key, Value> cache = CacheBuilder.<Key, Value>from(spec).build();
    // Just weird
    String s = new <Number, String, NullPointerException>String(chars);

As far as I know, this has no effect whatsoever and can cause confusion when someone expects that the generics are doing something and they aren't. I don't imagine this happens too often, but it seems like it might be a reasonable thing to make an error.

**Comment by cushon** [comment]
Huh. I did not know that was allowed.

JLS &sect; 15.12.2.1 says:

> If the method invocation includes explicit type arguments, and the member is a generic method, then the number of type arguments is equal to the number of type parameters of the method.

> This clause implies that a non-generic method may be potentially applicable to an invocation that supplies explicit type arguments. Indeed, it may turn out to be applicable. In such a case, the type arguments will simply be ignored.

> This rule stems from issues of compatibility and principles of substitutability. Since interfaces or superclasses may be generified independently of their subtypes, we may override a generic method with a non-generic one. However, the overriding (non-generic) method must be applicable to calls to the generic method, including calls that explicitly pass type arguments. Otherwise the subtype would not be substitutable for its generified supertype.

This doesn't entirely make sense to me. If the static type is the generified supertype, we should require type parameters. If it's the non-generic subtype, we should disallow them. If code is refactored to switch from the supertype to the subtype (or vice versa) it seems reasonable to require additional changes.

There are ~100 instances of this internally and they all look like mistakes.
