### ISSUE TITLE
Intellij IDEA detects ~500 issues in the core module

### ISSUE THREAD

**Issue by vbauer** [google/error-prone#314]
Class structure: 1
Code style issues: 4
Control flow issues: 6
Data flow issues: 6
Declaration redundancy: 312
General: 1
J2ME issues: 11
Javadoc issues: 63
Performance issues: 11
Probable bugs: 35
Verbose or redundant code constructs: 46

**Comment by eaftan** [comment]
Thanks for the bug report, but this is not really actionable.  If there are particular bugs you think should be fixed, please file bug reports for those.  Or if there are things we should simplify, Javadoc problems, etc., feel free to send us pull requests.
