### ISSUE TITLE
Compiler flags private static methods that overload local methods as "not found"

### ISSUE THREAD

**Issue by jrh3k5** [google/error-prone#317]
I've created a project that demonstrates it [here](https://github.com/jrh3k5/errorprone-enum-static-method-demo), but, at a high level, if I have an enum that declares a private static method that overloads an instance method (same name, different arguments), the Error Prone compiler gives out a compilation error similar to the following:

```
[INFO] Compiling 1 source file to /Users/jh016266/git/jh016266/errorprone-enum-static-method-demo/target/classes
/Users/jh016266/git/jh016266/errorprone-enum-static-method-demo/src/main/java/com/github/jrh3k5/TestClass.java:8: error: no suitable method found for exampleOverloadedMethod(<anonymous TestEnum>)
                return exampleOverloadedMethod(this) + 1;
                       ^
    method TestEnum.exampleOverloadedMethod() is not applicable
      (actual and formal argument lists differ in length)
    method <anonymous com.github.jrh3k5.TestClass$TestEnum$1>.exampleOverloadedMethod() is not applicable
      (actual and formal argument lists differ in length)
```

This error does not occur with the JDK compiler.

**Comment by cushon** [comment]
Thanks for the detailed report. This behaviour isn't specific to Error Prone. The JDK8u40 javac reports the same error, but previous JDKs (I tested with JDK7u72) accept the code.

The JDK8 behaviour is correct. From [JLS &sect;15.12.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12.1), method lookup searches the current class and its superclass heirarchy before looking at any enclosing classes and their superclass hierarchies. If the search finds a method in the current class or its superclass hierarchy, then the search terminates even if that method isn't applicable.

So the fact that this code compiles prior to JDK8 is actually a bug.
