### ISSUE TITLE
Integrating error prone with Buck

### ISSUE THREAD

**Issue by tom-smalls** [google/error-prone#318]
We use BUCK (see https://github.com/LMAX-Exchange/buck) as our build tool, and I have been looking at integrating error-prone with it.

We have a a problem when it comes to replacing the javac.main.Main.main() call with new ErrorProneCompiler.Builder().build().compile(args) as it uses the JavaCompiler and CompilationTask objects in Jsr199Javac.java: https://github.com/LMAX-Exchange/buck/blob/master/src/com/facebook/buck/java/Jsr199Javac.java#L162 and https://github.com/LMAX-Exchange/buck/blob/master/src/com/facebook/buck/java/Jsr199Javac.java#L213

The call to the main method is therefore wrapped and not accessible to us.

Thanks,

Tom

**Comment by cushon** [comment]
There's an Error Prone `javax.tools.JavaCompiler` implementation here that should do what you want: https://github.com/google/error-prone/blob/master/core/src/main/java/com/google/errorprone/ErrorProneJavaCompiler.java

**Comment by tom-smalls** [comment]
Awesome, just what we needed. Thanks for getting back so quickly. We now have error-prone integrated with BUCK but need to iron out a few other issues we're seeing.

**Comment by eaftan** [comment]
Great!  Once you get the issues worked out, we'd love to have the integration as part of Error Prone.  Feel free to send us a pull request.

**Comment by tom-smalls** [comment]
I've come across an interesting issue where one of our test assertion classes fails to compile when using error prone but passes when using normal javac (from what I can tell it isn't an error prone check that is failing).

``` java
private static <T, I> Collection<ExpectationCheck<T>> getExpectationChecks(final Collection<I> inputs, final Function<I, ? extends ExpectationCheck<T>> createExpectation)
    {
        return inputs.stream().map(createExpectation).collect(Collectors.toList());
    }
```

```
Expectations.java:145: error: method map in interface java.util.stream.Stream<T> cannot be applied to given types;
        return inputs.stream().map(createExpectation).collect(Collectors.toList());
                              ^
  required: java.util.function.Function<? super I,? extends R>
  found:    createExpe[...]apply
  reason: cannot infer type-variable(s) R
    (argument mismatch; java.util.function.Function<I,capture#1 of ? extends com.lmax.testing.expectations.ExpectationCheck<T>> cannot be converted to java.util.function.Function<? super I,? extends capture#1 of ? extends com.lmax.testing.expectations.ExpectationCheck<T>>)

```

ExpectationCheck is an abstract class. I removed "? extends" to get it to compile

**Comment by cushon** [comment]
Do you have a complete repro? I can't reproduce. The following compiles for me with error prone 2.0.2:

```java
import java.util.Collection;
import java.util.function.Function;
import java.util.stream.Collectors;

abstract class ExpectationCheck<T> {
}

class Test {
  private static <T, I> Collection<ExpectationCheck<T>> getExpectationChecks(
      final Collection<I> inputs,
      final Function<I, ? extends ExpectationCheck<T>> createExpectation) {
    return inputs.stream().map(createExpectation).collect(Collectors.toList());
  }
}
```

**Comment by tom-smalls** [comment]
I am now unable to reproduce this. Let's pretend it never happened until I can find a concrete example :)

**Comment by tom-smalls** [comment]
Using error prone 2.0.2 and Java 1.8.0_45-1 I get the following compilation error from javac (this only occurs using error prone). The code below produces this error:

```
/com/lmax/testing/Expectations.java:16: error: method map in interface java.util.stream.Stream<T> cannot be applied to given types;
        return inputs.stream().map(createExpectation::apply).collect(Collectors.toList());
                              ^
  required: java.util.function.Function<? super I,? extends R>
  found:    createExpe[...]apply
  reason: cannot infer type-variable(s) R
    (argument mismatch; java.util.function.Function<I,capture#1 of ? extends com.lmax.testing.Expectations.ExpectationCheck<T>> cannot be converted to java.util.function.Function<? super I,? extends capture#1 of ? extends com.lmax.testing.Expectations.ExpectationCheck<T>>)
```

```java
import java.util.Collection;
import java.util.function.Function;
import java.util.stream.Collectors;

public class Expectations
{
    abstract class ExpectationCheck<T>
    {

    }

    private static <T, I> Collection<ExpectationCheck<T>> getExpectationChecks(final Collection<I> inputs, final Function<I, ? extends ExpectationCheck<T>> createExpectation)
    {
        return inputs.stream().map(createExpectation::apply).collect(Collectors.toList());
    }
}
```

They key difference to what was posted before is the method reference to apply inside map().

**Comment by cushon** [comment]
Thanks for the repro. I believe this is related to [JDK-8039214](https://bugs.openjdk.java.net/browse/JDK-8039214). Error Prone redistributes a copy of javac, and the version its on is a several-month-old javac9. I confirmed that example compiles cleanly with the latest javac9, so this should be fixed next time we do an update. I'm hoping to do that in the next few weeks. The main complication is that we may have to drop JDK 7 support.

If you're willing to use a work-around, adding an explicit type argument to `map` should do it:

```
return inputs.stream().<ExpectationCheck<T>>map(createExpectation::apply).collect(Collectors.toList());
```

**Comment by tom-smalls** [comment]
Dropping the `::apply` is fine as createExpectation is a function so the method reference is redundant

**Comment by cushon** [comment]
Oh, right. Most of the type inference breaking changes / bugs I'm aware of can be worked around with explicit type arguments, but dropping`::apply` is even better.

**Comment by tom-smalls** [comment]
I no longer work for LMAX, but I don't believe this is being pursued any further.

**Comment by dpursehouse** [comment]
> see https://github.com/LMAX-Exchange/buck

This doesn't seem to exist any more.  Is it mirrored somewhere else?

**Comment by tom-smalls** [comment]
The original is at https://github.com/facebook/buck I believe that most of the changes from the LMAX branch were merged into Facebook's trunk so they deleted it

**Comment by davido** [comment]
I wonder why this was closed? I opened this issue on Buck issue tracker: https://github.com/facebook/buck/issues/994. Now, that Buck supports both: `tools.javac_jar` and `tools.compiler_class_name`, we could integrate Buck and error prone. However, i don't see where `error-prone-all-in-one.jar` can be obtained?

Looking on Bazel integration, the error prone transitive dependencies are spread across multiple JARs and even source directories. See also this Bazel issue: https://github.com/bazelbuild/bazel/issues/265 and the fix: https://github.com/bazelbuild/bazel/commit/07caf827030ec275ad9845f942c14d8ed5fdd4e1.

So, it seems, that if I borrow thoses dependencies from Bazel tree (9bde9d09a83cdca2dc884d322ab50f7542c062cf)

* third_party/java/jdk/langtools/javac.jar
* third_party/error_prone/error_prone_annotations-2.0.13.jar
* third_party/error_prone/error_prone_annotation-2.0.13.jar
* third_party/error_prone/error_prone_core-2.0.13.jar
* third_party/checker_framework_dataflow/dataflow-1.8.10.jar

Now the other two missing dependencies must be compiled from the source:

```
 bazel build third_party/jformatstring:jformatstring
 cp bazel-bin/third_party/jformatstring/libjformatstring.jar <to uber JAR>

  bazel build checker_framework_javacutil
  cp bazel-bin/third_party/checker_framework_javacutil/libchecker_framework_javacutil.jar <to uber JAR>
```

After building a uber JARs with all those dependencies, and adding these lines to my `.buckconfig.local`:

```
  [tools]
    javac_jar = lib/error_prone_2.13_all_in_one.jar
    compiler_class_name = com.google.errorprone.ErrorProneJavaCompiler
```

Now, patching `gerrit-server` sub-project with this line: http://paste.openstack.org/show/592031/ and building with `buck build gerrit-server:server` we are getting error prones warning and errors: http://paste.openstack.org/show/592032 .

**Comment by davido** [comment]
Never mind, error prone for Ant is all in one ueber jar that I was looking for: https://repo1.maven.org/maven2/com/google/errorprone/error_prone_ant/2.0.15/error_prone_ant-2.0.15.jar.
