### ISSUE TITLE
BigDecimal.valueOf(doubleLiteral) and new BigDecimal(doubleLiteral) are bad

### ISSUE THREAD

**Issue by kevinb9n** [google/error-prone#321]
I think these should probably always be rewritten.

https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#BigDecimal(double)

When the literal is not a whole number, this is dangerous, and the double literal should simply be changed to a String literal.

If the literal is a whole number in the long range, like "2.0", this is not really a big problem, but we might want to just remove the .0 anyway?  Just to have as few remaining calls to this dangerous overload as possible.

What about the case where the argument is not a *literal*?  Also problematic, just less clear how to suggest a fix.

**Comment by cushon** [comment]
This was implemented in 3bda38642a22bdf52668fbb1eecbdc74492d1fae.

http://errorprone.info/bugpattern/BigDecimalLiteralDouble
