### ISSUE TITLE
Move various test helpers and matchers from core into their own module

### ISSUE THREAD

**Issue by tom-smalls** [google/error-prone#322]
I have found the various test helpers and matchers in error prone very useful when testing bug patterns. Some of the bug patterns we've created (migrating from our current internal static analysis tool) are very unique to our code base, so would not be suitable for the project, which is why we're keeping them outside of error prone.

I am proposing moving CompilationTestHelper, ErrorProneInMemoryFIleManager etc. to their own test-helper module so that they can be used outside of error prone for others to write their own bug patterns (and to be able to test them).

I did an initial implementation locally but had an issue with a cyclical dependency between modules: core -> test-helper -> core; as CompilationTestHelper contains a ErrorProneCompiler.

**Comment by tom-smalls** [comment]
Another solution could be to use the maven-jar-plugin to create a jar of the "helper" files, which can then be used as a dependency for external projects. See https://maven.apache.org/plugins/maven-jar-plugin/test-jar-mojo.html

**Comment by eaftan** [comment]
Agreed, this would be helpful for people writing custom checks.  See #62 for our initial investigation.

**Comment by tom-smalls** [comment]
I've had some success with creating the maven test jar (although you don't want to look at it's contents!!). I had to modify CompilationTestHelper and ErrorProneInMemoryFileManager so they had the ability to add a resource with a Path object rather than just a String representing a file name due to not being able to resolve the classes under test.
