### ISSUE TITLE
`CompileTimeConstantExpressionMatcher` matches but `ASTHelpers.constValue` returns `null`

### ISSUE THREAD

**Issue by XN137** [google/error-prone#3224]
For the following expression (in a static initializer block):
```
"Debug mode " + (DEBUG ? "enabled." : "disabled.")
```
where `DEBUG` is a static boolean class field.

This started failing in `errorprone-slf4j` when switching to use `error-prone` version `2.14.0` (on java 11).
See also https://github.com/KengoTODA/errorprone-slf4j/issues/193

Is this a recently introduced bug or was there never a guarantee that this order of helper calls would work?

**Comment by nick-someone** [comment]
> Is this a recently introduced bug or was there never a guarantee that this order of helper calls would work?

Correct - `CompileTimeConstantExpressionMatcher` matches more expressions than `ASTHelpers.constValue(t) != null` does (namely, in your case, ternary expressions where both halves of the ternary are themselves constants). This matcher's primary purpose is to serve the https://errorprone.info/bugpattern/CompileTimeConstant checker, ensuring that callers of a method whose parameter is annotated with `@CompileTimeConstant` pass in a value entirely under the control of the programmer (think about things like avoiding SQL injection).

One thing to think about: At compile-time, what do you think the "value" of the expression `"Debug mode " + (DEBUG ? "enabled." : "disabled.")` should be?
