### ISSUE TITLE
Provide code style for the project

### ISSUE THREAD

**Issue by tom-smalls** [google/error-prone#327]
See https://github.com/google/error-prone/pull/326 for more details. Essentially it would be useful not to ignore everything under .idea and to commit the code style you want for the project via codeStyleSettings.xml so external developers don't have to fight the IDE to not automatically reformat the code.

**Comment by cushon** [comment]
@eaftan pushed a new `codeStyleSettings.xml` to https://github.com/google/error-prone/tree/add_intellij_style, but I can't get intellij to pick up the changes even after a fresh check-out of Error Prone and reseting my local intellij configuration. It looks like the mechanism for sharing code style settings might have [changed](https://www.jetbrains.com/idea/help/exporting-and-importing-settings.html)? Any idea what the best way to do this is?

**Comment by tom-smalls** [comment]
What scheme do you selected in Settings -> Editor -> Code Style? You can set intellij to use a project style, or some other styles that are stored in ~/.IntelliJIdea14/config/codestyles/ (I'm running on Linux and Intellij 14)

**Comment by cushon** [comment]
Ok, thanks. I expected intellij to pick it up from the project's .idea directory, but copying it to the main configuration directory worked. (It's `~/Library/Preferences/IdeaIC14/codestyles/` for intellij 14 on a mac.)

I opened #327 to add the configuration.

**Comment by cushon** [comment]
The code style is checked in, and I added instructions to the wiki: https://github.com/google/error-prone/wiki/For-Developers#intellij

Thanks for suggesting this.
