### ISSUE TITLE
It's possible to mock final methods/classes with mock-maker-inline

### ISSUE THREAD

**Issue by jtraglia** [google/error-prone#3281]
@graememorgan Hi there, I like the new `CannotMockFinalMethod` check but it's throwing false positives for me. In Mockito 2 it is actually possible to mock final methods/classes, but it's a feature that must be enabled manually, via "mock-maker-inline". The project I'm working on does this for certain sub-projects. It's easy for us to disable `CannotMockFinalMethod` but I was wondering if you think there's a way to filter out those findings?

This link provides a little more information: https://stackoverflow.com/a/40018295

Thoughts?

**Comment by graememorgan** [comment]
I've disabled this (and `CannotMockFinalClass`). Should hit the next open source release.
