### ISSUE TITLE
`UnusedMethod`: Add more JPA lifecycle annotations or make annotations configurable

### ISSUE THREAD

**Issue by jnehlmeier** [google/error-prone#3297]
Currently `UnusedMethod` only ignores JPA lifecycle annotation `javax.persistence.PostLoad`.

However there are quite a few more:
- PostLoad
- PostPersist
- PostRemove
- PostUpdate
- PrePersist
- PreRemove
- PreUpdate

Also with the move to Jakarta namespace, all these annotations should be added with `javax.persistence` as well as `jakarta.persistence` package.

**Comment by reitzmichnicht** [comment]
Now with spring boot 3 available this issue is a bit annoying. Any estimate if this will be included in the next error prone release?

**Comment by Stephan202** [comment]
@rickie opened PR #3428 for this; I see that @cushon and @graememorgan worked on `UnusedMethod` before; maybe one of them can give it a push. :)

Agree this would be nice to see improved!

**Comment by rickie** [comment]
The PR https://github.com/google/error-prone/pull/3428 is now merged, so we can close this ticket 😄.
