### ISSUE TITLE
False positive in CheckedExceptionNotThrown with short-form try-with-resources

### ISSUE THREAD

**Issue by ksobolew** [google/error-prone#3321]
Say I have a method like this:

```java
    private final AutoCloseable afterClassCloser = ...;

    @AfterClass(alwaysRun = true)
    public final void close()
            throws Exception
    {
        try (afterClassCloser) {
            cleanupAndStuff();
        }
    }
```

Then `CheckedExceptionNotThrown` will report that the `Exception` is not thrown, even though it can be thrown by `afterClassCloser::close`.

If I change it to:

```java
        try (AutoCloseable ignored = afterClassCloser) {
            cleanupAndStuff();
        }
```

then there is no error.

**Comment by graememorgan** [comment]
Thanks for the report, that's a nice one! I've never seen the assignment-free try-with-resources syntax. Looks like it's "new" in Java 9.
