### ISSUE TITLE
non-matched rules are reported as patched

### ISSUE THREAD

**Issue by delanym** [google/error-prone#3349]
The plugin is reporting patches written to a file, but no file writes are occurring.

`<arg>-Xplugin:ErrorProne -XepAllErrorsAsWarnings -XepPatchChecks:DeadException -XepPatchLocation:${project.build.directory}</arg>`

These are also logged as warnings, but they result in writes to the patch file

`<arg>-Xplugin:ErrorProne -XepAllErrorsAsWarnings -XepPatchChecks:MissingOverride -XepPatchLocation:${project.build.directory}</arg>`

`<arg>-Xplugin:ErrorProne -XepAllErrorsAsWarnings -XepPatchChecks:DefaultCharset -XepPatchLocation:${project.build.directory}</arg>`

**Comment by delanym** [comment]
Today none of the patches are applying, even though they are logged e.g.
`Changes were written to /git/walla/walla-maven-plugin/target/error-prone.patch. Please inspect the file and apply with: patch -p0 -u -i error-prone.patch`

**Comment by Stephan202** [comment]
@delanym this sounds similar to #1562, which was fixed in #3236. IIUC that change hasn't been released yet.

**Comment by delanym** [comment]
@Stephan202 it looks like it hasn't been merged either??
Im not sure its the same though. Patches to DefaultCharset were working, and today they aren't. Its very strange.

**Comment by Stephan202** [comment]
> @Stephan202 it looks like it hasn't been merged either??

It was merged; see ad0289b0251293d73c5ea62a5f165bba8577b3a7, which is on `master`. (The Github PR status is misleading; that's merely an artifact of the way in which Google sync private and OSS code.)

> Im not sure its the same though. Patches to DefaultCharset were working, and today they aren't. Its very strange.

Can't help further with that, I'm afraid. (A complete reproduction case would help.)

**Comment by delanym** [comment]
Cant remember what the resolution was here, but Im using `-XepPatchLocation:IN_PLACE` which works
