### ISSUE TITLE
`ExtendsObject` error message is confusing/misleading

### ISSUE THREAD

**Issue by mernst** [google/error-prone#3363]
The `ExtendsObject` error message is:

> "`T extends Object` is redundant in normal Java, and does not work to describe `T` as non-null across compilation boundaries when the Checker Framework unless you compile users against bytecode generated by the Checker Framework javac. (If you are building this code with the Checker Framework javac, then disable this check.)"

This error message can be improved.
 * "normal Java" suggests that the Checker Framework is an incompatible variant.  The Checker Framework uses standard Java.
 * "compile users" is probably a typo.
 * The message mentions nullness, but `extends Object` is meaningful for any type system for which the top type is not the default.  Several such type systems exist.
 * Use of the "Checker Framework javac" is a red herring.  This is relevant to every project that ever uses the Checker Framework, regardless of which version of `javac` they are running and whether the Checker Framework is run on a particular execution.

**Comment by cushon** [comment]
> Use of the "Checker Framework javac" is a red herring

I think that section was referring to the behaviour of adding defaulted annotations to bytecode, e.g.:

```
class T<X> {}
```

```
  2: #14(): CLASS_TYPE_PARAMETER, param_index=0
    org.checkerframework.checker.nullness.qual.NonNull
```

To check my understanding, is point that that behaviour is coming from the Checker Framework annotation processor, and occurrs regardless of which javac version it's running on? Is there a Checker Framework manual reference with more detail on that we should cite?

**Comment by cushon** [comment]
I reworked the docs a bit in https://github.com/google/error-prone/commit/ac696c2e4c1b4536ab447c9890c35b1702389f7f

**Comment by mernst** [comment]
> To check my understanding, is point that that behaviour is coming from the Checker Framework annotation processor, and occurrs regardless of which javac version it's running on? Is there a Checker Framework manual reference with more detail on that we should cite?

Yes, that is correct.

A reference is the first paragraph of [Command line, via Checker Framework javac wrapper](https://checkerframework.org/manual/#javac-wrapper), which says:

> It is exactly the same as the OpenJDK javac compiler, with one small difference: it includes the Checker Framework jar file on its classpath.

**Comment by mernst** [comment]
Thanks for updating the message, Liam!

**Comment by mernst** [comment]
BTW, there is a stray close paren and seemingly an unnecessary line break at https://errorprone.info/bugpattern/ExtendsObject .
