### ISSUE TITLE
What is the point of CanIgnoreReturnValueSuggester?

### ISSUE THREAD

**Issue by norrisjeremy** [google/error-prone#3366]
What is the point of the new `CanIgnoreReturnValueSuggester` warning?
All it appears to be doing is adding warning clutter to builds to add an annotation to any method that happens to `return this`, which does not appear to be especially helpful.

**Comment by cushon** [comment]
It's intended for use in code bases that enable `@CheckReturnValue` enforcement by default for everything that isn't annotated with `@CanIgnoreReturnValue`, `CanIgnoreReturnValueSuggester` should probably be an opt-in check that isn't enabled by default.

**Comment by norrisjeremy** [comment]
Yes, I would strongly agree that it should not be enabled by default, because all it is doing right now is forcing us to either add an annotation to our code base (either `@CanIgnoreReturnValue` or `@SuppressWarnings("CanIgnoreReturnValueSuggester")` or add a `Xep:CanIgnoreReturnValueSuggester:OFF` setting to our builds, neither of which is especially helpful since this new warning doesn't appear to be triggered by any actual bug in our code base.

**Comment by cpovirk** [comment]
(Agreed with both of you. If anyone sees this thread and gets interested in "CheckReturnValue by default," you can follow along at https://github.com/google/error-prone/issues/3003.)

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/92fe3ed0b17bee3ae5a8ea240c23ec49d65cf2d7
