### ISSUE TITLE
Support running separately from Maven compiler plugin

### ISSUE THREAD

**Issue by electrum** [google/error-prone#337]
It would be preferable to run these inspections separately from compilation, in the same manner as other checkers such as Checkstyle, FindBugs, etc. This would easily allow skipping the checks, running in a different phase, etc.

Also consider that if every such checker wanted to use the compiler plugin, you could only run one checker.

**Comment by Stephan202** [comment]
:+1:

> Also consider that if every such checker wanted to use the compiler plugin, you could only run one checker.

Case in point: [rkunze/maven-checkerframework-javac](https://github.com/rkunze/maven-checkerframework-javac).

**Comment by adriancole** [comment]
this is helpful in maven as it doesn't seem possible to change the plugin dependencies of the maven-compiler-plugin per source tree. For example, I'm primarily concerned with error-prone in the main tree, and due to some unknown reasons, our test tree fails outright when using java 9 and errorprone together.

**Comment by cushon** [comment]
Error Prone is fundamentally a compiler plugin, so there's no way to run it standalone separately from compilation. It is possible to run it in different phases, e.g. by only enabling it during compilation for CI builds or something.

> consider that if every such checker wanted to use the compiler plugin, you could only run one checker

With the current `-Xplugin:` integration, it's possible to run Error Prone together with other javac plugins in the same compilation.
