### ISSUE TITLE
Calling equals() on a reference of exact static type Iterable, Collection, Queue or Multimap

### ISSUE THREAD

**Issue by kevinb9n** [google/error-prone#340]
Need to do some research here into when this might be safe. But these are four common container types that do not have well-defined equals() behavior. Calling equals() without specifically knowing what subtype you have is dangerous, and leads to the types of situations where you end up with an assertion failure saying "not true that XYZ equals XYZ" where the XYZ string is exactly the same in both cases. Users love those.

**Comment by cushon** [comment]
This happened in bfdd94d744e211bcc2a96655f7f9553372b08916: http://errorprone.info/bugpattern/UndefinedEquals
