### ISSUE TITLE
Should @ForOverride foo() permit super.foo() calls?

### ISSUE THREAD

**Issue by cpovirk** [google/error-prone#342]
Guava has this situation:

```
class AbstractFuture {
  // @ForOverride?
  void done() {}
}

// There are multiple classes like the following:
class AggregateFuture extends AbstractFuture {
  @Override final void done() {
    super.done();

    runningState = null;
  }
}
```

We would like to apply `@ForOverride` to `done()`. But we can't because of the `super.done()` call[_]. We don't really *need_ that call, but it makes me feel safer to have it there. (I would also want it if we had multiple levels of `done()` overrides down the hierarchy... though I suppose we could have `done()` call a `reallyDone()` method.) Another option is for us to make `done()` `abstract` so that we "know" we don't need the `super.done()` call. But we still don't really "know" that unless we look at the superclass. Plus, it requires every subclass to override `done()`, even though most don't need to.

Possibilities for changes that might help us:
- Allow `super.done()`
- Allow `super.done()` if the calling method is itself annotated `@ForOverride` (but this would be weird in our case, where `done()` is sometimes `final`)

[*] Error:

```
error: [ForOverride] Method annotated @ForOverride must not be invoked directly (except by the declaring class, com.google.common.util.concurrent.AbstractFuture<V>)
    super.done();
              ^
```

**Comment by cpovirk** [comment]
https://github.com/google/guava/blob/8d6c68415db141d7e44e7132f0ed39c571d47468/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L772
https://github.com/google/guava/blob/bcaed940f6bfb8ab24e86269c4e4e0d7cce5eea6/guava/src/com/google/common/util/concurrent/AggregateFuture.java#L49

**Comment by cushon** [comment]
What about only allowing super.done() inside an override of done?

**Comment by cpovirk** [comment]
That sounds good to me.

**Comment by guptasaloni** [comment]
Its better to make abstract the superclass

**Comment by lukesandberg** [comment]
I believe this was fixed by https://github.com/google/error-prone/commit/a4b603d633b5becebce6e410e090a0f7fb6b456f

close?

**Comment by eaftan** [comment]
Thanks @lukesandberg
