### ISSUE TITLE
CheckedExceptionNotThrown probably should not trigger on overrides

### ISSUE THREAD

**Issue by ksobolew** [google/error-prone#3425]
This is not strictly a bug, more like a request for your opinion.

Say there is an interface and the interface has a method which declares a checked exception:

```java
public interface StuffDoer {
    void doStuff() throws IOException;
}
```

Then, there is an implementation of that interface:

```java
public class SimpleStuffDoer implement StuffDoer {
    public void doStuff() throws IOException {
        System.out.println("Did the stuff");
    }
}
```

Note that the implementation does not in fact throw `IOException`, and this will trigger the `CheckedExceptionNotThrown` check. There is an argument to be made that this is not the right thing to do:

* The `throws` declaration, even though redundant, is conforming to the interface's contract
* The implementation can of course relax the interface's contract, but it should not be forced to do so
* Code which relies on `SimpleStuffDoer` not throwing would be really surprised if someone said "we should not rely on concrete types and code to the interface instead" and changed the variable type to "StuffDoer" and now it no longer compiles because it does not handle `IOException`

On the other hand there is an argument to be made to the opposite:

* The more redundant code we can remove the better
* If none of the implementations throw this exception, we can remove the declaration from the interface

But the counter-argument is:

* The `throws` may be redundant now, but it's more future-proof, as it's way harder to add a `throws` later on when it starts to be needed

What's your opinion on this?

**Comment by graememorgan** [comment]
`CheckedExceptionNotThrown` won't (or at least, shouldn't!) fire in that case. It only fires on methods that can't be overridden. It would if the class were `final`.

**Comment by ksobolew** [comment]
> It would if the class were `final`.

Indeed it doesn't! My belief, though, is that it shouldn't trigger in that case either. The issue is about the method here and now, and the fact that it can't be overridden is not relevant.

**Comment by graememorgan** [comment]
I see. I think there are cases where you may want to preserve an unthrown exception there, but I think they're the minority. The cases I can think of are things like "I'm about to add the exception in the next release".

Even then, I think the case is dubious. If you declare an exception that isn't ever actually thrown, a lot of people are just going to `catch (UnthrownException e) { throw new IllegalStateException(e, "impossible"); }`, and then you're in a worse situation overall.

I'd suggest suppressing (with a comment explaining why the exception is useful to declare) for those cases. :)

> The `throws` may be redundant now, but it's more future-proof, as it's way harder to add a throws later on when it starts to be needed

(I'd note that this is an argument for declaring every method as `throws Exception`, or equivalently to removing the notion of checked exceptions from Java, which I think is something you'd find a lot of support for!)

**Comment by ksobolew** [comment]
> (I'd note that this is an argument for declaring every method as `throws Exception`, or equivalently to removing the notion of checked exceptions from Java, which I think is something you'd find a lot of support for!)

Yeah, I've heard that argument before :) The difference here is that the exception is "pre-declared" by the interface, which the current method overrides, so it's already "allowed" in a sense.
