### ISSUE TITLE
In this code they created a variable and entered it at the end of it with plus/minus sign 
What it is doing . (In this case the rowstart++)

### ISSUE THREAD

**Issue by S1xnin9** [google/error-prone#3473]
![IMG_20221008_232505469.jpg](https://user-images.githubusercontent.com/115029214/194720962-b4b5f21e-be18-44c3-a305-02dd4144ef13.jpg)

**Comment by panditsneha** [comment]
" rowStart++ " is same as " rowStart = rowStart +1 " . It is incrementing the value by 1.

**Comment by S1xnin9** [comment]
> " rowStart++ " is same as " rowStart = rowStart +1 " . It is incrementing the value by 1.

Ooh so it is doing the same thing as 'col++'
In for loop?
