### ISSUE TITLE
Errorprone compiler >2.0.1 seems to fail to figure out complex generics

### ISSUE THREAD

**Issue by TomDmitriev** [google/error-prone#348]
I have a class which looks something like this

    public class GroupedBy<T extends Identifiable, V> {
        private final Map<T, List<V>> values;

        public GroupedBy(Map<? extends T, ? extends List<? extends V>> values) {
            this.values = Collections.unmodifiableMap(
                    values.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey,
                           e -> ImmutableList.copyOf(e.getValue()))));
        }

        // methods...
    }

Which gets compiled fine using errorprone 2.0.1. However, if I use a newer version I have to rewrite the constructor to look like this:

        public GroupedBy(Map<? extends T, ? extends List<? extends V>> values) {
            this.values = Collections.unmodifiableMap(
                    values.entrySet().stream().collect(Collectors.<Map.Entry<? extends T, ? extends List<? extends V>>,
                            T, List<V>>toMap(e -> e.getKey(),
                            e -> ImmutableList.copyOf(e.getValue())
                     )));
        }

Which obviously looks uglier than the previous version. Otherwise I get the error below. Why does it happen? Is this an error-prone bug?

error: incompatible types: cannot infer type-variable(s) CAP#1,T#1,K,U
        this.values = Collections.unmodifiableMap(
                                                 ^
    (argument mismatch; Function<Entry<CAP#2,CAP#3>,CAP#2> cannot be converted to Function<? super Entry<CAP#2,CAP#3>,? extends CAP#2>)
  where T#1,K,U,T#2,V are type-variables:
    T#1 extends Object declared in method <T#1,K,U>toMap(Function<? super T#1,? extends K>,Function<? super T#1,? extends U>)
    K extends Object declared in method <T#1,K,U>toMap(Function<? super T#1,? extends K>,Function<? super T#1,? extends U>)
    U extends Object declared in method <T#1,K,U>toMap(Function<? super T#1,? extends K>,Function<? super T#1,? extends U>)
    T#2 extends Identifiable declared in class GroupedBy
    V extends Object declared in class GroupedBy
  where CAP#1,CAP#2,CAP#3 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends T#2 from capture of ? extends T#2
    CAP#3 extends List<? extends V> from capture of ? extends List<? extends V>

**Comment by cushon** [comment]
We're using javac9, which doesn't always match the type inference behaviour of earlier versions. Our copy of javac9 is ~6 months old, so this could be a bug that's been fixed upstream. It could also be a deliberate change.

Would you be willing to downlaod a JDK 9 early access build from here: https://jdk9.java.net/download/, and see if you project builds with JDK 9 without using Error Prone? If it does, this should be fixed next time we update our javac.

**Comment by cushon** [comment]
Also, I suspect this is in some way related to [JDK-8033718](https://bugs.openjdk.java.net/browse/JDK-8033718).

**Comment by cushon** [comment]
This is fixed in 2.0.7.
