### ISSUE TITLE
ASTHelpersSuggestions does not flag call to `packge()` on `com.sun.tools.javac.code.Symbol.ClassSymbol`

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#3482]
I noticed that calls to `packge()` were not flagged by the new `ASTHelpersSuggestions` check when the static type of the receiver is `com.sun.tools.javac.code.Symbol.ClassSymbol`, which just inherits the `packge()` method from `Symbol`.  I think this is because the check matches on the exact class `Symbol`:

https://github.com/google/error-prone/blob/80650f545a4c51453b2a2df7b893411ae1732b2b/core/src/main/java/com/google/errorprone/bugpatterns/ASTHelpersSuggestions.java#L43-L46

Was this intentional?

**Comment by graememorgan** [comment]
I've sent a PR to fix this internally, so I'll optimistically mark this as fixed in the next release.
