### ISSUE TITLE
Code running with single quotes but not with double quotes ,why?(in the firstnlast function with 'a')

### ISSUE THREAD

**Issue by S1xnin9** [google/error-prone#3492]
https://github.com/Java-Techie-jt/devops-automation/issues/10

**Comment by tbroyer** [comment]
Please stop spamming GitHub repository issues with generic programming questions.

Issues are for reporting bugs or ask for enhancements for specific projects, not for generic off-topic discussions.

It's great that you want to learn programming, but GitHub issues are not the place to ask your questions. StackOverflow.com would be a better fit for those.

You're doing yourself a disservice by spamming random GitHub projects with your questions. All you'll get is being blocked/banned from repositories, possibly even from GitHub as a whole.

**Comment by S1xnin9** [comment]
> Please stop spamming GitHub repository issues with generic programming questions.
> 
> Issues are for reporting bugs or ask for enhancements for specific projects, not for generic off-topic discussions.
> 
> It's great that you want to learn programming, but GitHub issues are not the place to ask your questions. StackOverflow.com would be a better fit for those.
> 
> You're doing yourself a disservice by spamming random GitHub projects with your questions. All you'll get is being blocked/banned from repositories, possibly even from GitHub as a whole.

Okh sir , i am sorry i didn't know about it
