### ISSUE TITLE
UnnecessaryParentheses misses

### ISSUE THREAD

**Issue by delanym** [google/error-prone#3585]
The UnnecessaryParentheses bugpattern doesn't find these excess parentheses, which checkstyle does:

``` diff
-      if ((jumpingDecorator instanceof IGopherDecorator) ||
-          (jumpingDecorator instanceof IBunnyDecorator)) {
+      if (jumpingDecorator instanceof IGopherDecorator ||
+          jumpingDecorator instanceof IBunnyDecorator) {
```
or
``` diff
-      int low = (b & 0x0F);
+      int low = b & 0x0F;
```

**Comment by delanym** [comment]
https://errorprone.info/bugpattern/OperatorPrecedence
Hmmmm....this applies to my second example, but not the first

**Comment by cushon** [comment]
The check deliberately only suggests removing grouping parenthesis in cases where almost everyone agrees they don't help readability, because of https://google.github.io/styleguide/javaguide.html#s4.7-grouping-parentheses

**Comment by delanym** [comment]
Sounds more like DisagreeableParentheses/UnwantedParentheses. If i want to know what the compiler considers unnecessary I cant rely on this rule.

**Comment by graememorgan** [comment]
The meaning of "unnecessary" here is to readers, not the compiler.
