### ISSUE TITLE
Cant suppress CatchAndPrintStackTrace

### ISSUE THREAD

**Issue by delanym** [google/error-prone#3601]
Suppression via annotation does not work for this bugpattern

``` java
try {
  msg = descriptorMsgFactory.fromExternal(new FileInputStream(file));
} catch (@SuppressWarnings("CatchAndPrintStackTrace") FileNotFoundException e) {
  e.printStackTrace();
}
``` 

> DescriptorRetriever.java:[1095,13] [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace

**Comment by rickie** [comment]
The `@SuppressWarnings("CatchAndPrintStackTrace")` is placed incorrectly.

Try to move the suppression to the enclosing method, that will correctly suppress this.
I verified this locally 😄. 

So it should look roughly like this, based on the provided example:
```
@SuppressWarnings("CatchAndPrintStackTrace")
public void enclosingMethod() {
  try {
    msg = descriptorMsgFactory.fromExternal(new FileInputStream(file));
  } catch (@SuppressWarnings("CatchAndPrintStackTrace") FileNotFoundException e) {
    e.printStackTrace(); 
  }
}
```

Let me know if it works for you.

**Comment by delanym** [comment]
Yes that works thanks. On the static initializer blocks i can also annotate the class.
