### ISSUE TITLE
Inner class can be static

### ISSUE THREAD

**Issue by kevinb9n** [google/error-prone#361]
Inner classes (non-static nested classes) are, unless they appear in a static context, nefarious sources of memory leaks.

Rough suggestions:
- Whenever a non-local named class could have had `static` added, it **should** have `static` added.
- Whenever a local named class in a non-static context does not reference instance state, recommend it be moved to a non-local named class and made static. (It's sad that Java doesn't permit `static` to simply be added where it is.)
- Whenever an anonymous class in a non-static context doesn't reference instance state, this is equally bad but the fix is more severe -- if the containing method can't be made static, a static helper method has to be extracted.
  - Since this is invasive, it may be worth only issuing the warning if the containing instance has any fields, or even if it has any non-primitive fields (since otherwise, the memory leak risk is minimal).

**Comment by lowasser** [comment]
Note that in Java 8, the compiler determines whether a lambda can become implicitly static or not and implements it statically if possible.  This may simplify some of the shenanigans with anonymous classes in instance methods.

**Comment by eaftan** [comment]
I agree that this is worth flagging since it's so easy to introduce memory leaks.

> Whenever a non-local named class could have had static added, it should have static added.

I believe the [ClassCanBeStatic](http://errorprone.info/bugpattern/ClassCanBeStatic) check does this.  It's currently disabled but I don't remember why.  My intern from summer 2013 wrote it; he probably ran out of time on the cleanup.  We could use the same code to handle case #2.  #3 is harder to deal with because of the complexity of the fix.

**Comment by cushon** [comment]
I've been productionizing ClassCanBeStatic.

I don't think anything about this changes in 8, the handling of lambdas that don't capture the enclosing instance isn't applied to classes.

**Comment by cushon** [comment]
ClassCanBeStatic now works reliably for member classes.

I have reservations about suggesting rewriting anonymous/local classes as static member classes. In many cases they can be converted to lambdas, and if they can't the rewrite is not great for readability.

**Comment by cushon** [comment]
> I have reservations about suggesting rewriting anonymous/local classes as static member classes. In many cases they can be converted to lambdas, and if they can't the rewrite is not great for readability.

Four years on, it's likely that a future version of the language will lift some of the restrictions on making nested classes static: https://mail.openjdk.java.net/pipermail/amber-spec-experts/2020-January/001904.html
