### ISSUE TITLE
Version 2.17.0 release notes contain broken link

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#3637]
The [release notes for version 2.17.0](https://github.com/google/error-prone/releases/tag/v2.17.0) contain a [link](https://errorprone.info/bugpattern/ImpossibleNullComparison) to the [`ImpossibleNullComparison`](https://github.com/google/error-prone/blob/3aba0927a25e03c0eb38767097d7ee8385b95f2a/core/src/main/java/com/google/errorprone/bugpatterns/ImpossibleNullComparison.java) check, which yields a _404 File not found_ error. IIUC the release notes should link to [ProtoFieldNullComparison](https://errorprone.info/bugpattern/ProtoFieldNullComparison) instead.

**Comment by cushon** [comment]
Thanks, I fixed the link.

`ImpossibleNullComparison` is supposed to be the canonical name, but the name and altName was swapped after the check was renamed so existing flags worked, this inspired 48bbef0e51c2f5098efe6a2587fafc0ebc31bca5. At this point I can swap the name and altName back.
