### ISSUE TITLE
Unclear where to place @SuppressWarnings("TopLevel")

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#364]
Please document where to place `@SuppressWarnings("TopLevel")` in order to suppress the [TopLevel warning](http://errorprone.info/bugpattern/TopLevel). The warning message points at the package declaration in the file, where it cannot be placed.

It also tried to annotate the package in `package-info.java`, where `@SuppressWarnings` is forbidden, and the classes in the file for which the warning is generated, but this seems to have no effect.

**Comment by cushon** [comment]
I think someone reported this internally also - as you discovered, it can't be suppressed with `@SuppressWarnings`. The best option for now is to pass the flag `-Xep:TopLevel:OFF`.

Just out of curiosity, why can't the sources be moved to a path that matches the package declaration?

**Comment by PhilippWendler** [comment]
They can be moved, though in my case I prefer not to.

It is one small class with 5 subclasses. The superclass has the name of the file, the subclasses only exist to implement specific marker interfaces and are empty except for a constructor that calls the super constructor, no other code is in them. Thus they do not really warrant their own file and are better grouped with the superclass. Moving them to separate files would also clutter the package directory, and moving them to a separate package is no option because they are not public and should not be.

It is ok for me to pass the compiler option, though actually the warning is nice, it has let us find a different instance of multiple top-level classes that we actually want to avoid. I think annotating the top-level class(es) in the file would make sense to surpress the warning.

In any case, the documentation should be updated.

**Comment by cushon** [comment]
Ah, right. I'll update the documentation. The section in http://errorprone.info/bugpattern/TopLevel about suppression is auto-generated, and assumes there's always going to be an enclosing element.

And I think we can also make the check respect `@SuppressWarnings` if it's applied to the class.

For your example, can you use nested static classes instead of declaring the subclasses at the top level?

```
class Foo {
  private static class Bar extends Foo {}
}
```

**Comment by PhilippWendler** [comment]
Yes, I could used nested static classes. Maybe that is actually a good idea in my case, as it further reduces visibility (which might not always be wanted, but for me it is good). Thanks.
