### ISSUE TITLE
Constant computation overflows

### ISSUE THREAD

**Issue by kevinb9n** [google/error-prone#365]
For example, the expression "3 * 1000 * 1000 * 1000".  Such expressions are commonly done (misguidedly) for time-based math.

**Comment by cpovirk** [comment]
Here's [an example on StackOverflow](https://stackoverflow.com/q/30739030/28465).

But the reason I'm posting here now is that we almost introduced this bug all over Google code when switching from a `long` constant to an "equivalent" `int` constant: [CL 110841897](http://go/etgxl) (internal link)
