### ISSUE TITLE
does Error Prone v2.0.6 require Java 1.8?

### ISSUE THREAD

**Issue by jmason** [google/error-prone#369]
Hi all --

Last night, our builds have started failing with the following error:

```
09:55:36 :ServiceInterfaces:compileJava FAILED
09:55:36 
09:55:36 FAILURE: Build failed with an exception.
09:55:36 
09:55:36 * What went wrong:
09:55:36 Execution failed for task ':ServiceInterfaces:compileJava'.
09:55:36 > javax/tools/DiagnosticListener : Unsupported major.minor version 52.0
09:55:36 
09:55:36 * Try:
09:55:36 Run with --info or --debug option to get more log output.
09:55:36 
09:55:36 * Exception is:
09:55:36 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ServiceInterfaces:compileJava'.
09:55:36 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
09:55:36 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
[.....]
09:55:36 Caused by: java.lang.UnsupportedClassVersionError: javax/tools/DiagnosticListener : Unsupported major.minor version 52.0
09:55:36 	at java.lang.ClassLoader.defineClass1(Native Method)
09:55:36 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
09:55:36 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
09:55:36 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
09:55:36 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
09:55:36 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
09:55:36 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
09:55:36 	at java.security.AccessController.doPrivileged(Native Method)
09:55:36 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
09:55:36 	at net.ltgt.gradle.errorprone.ErrorProneCompiler$SelfFirstClassLoader.loadClass(ErrorProneCompiler.java:106)
09:55:36 	at net.ltgt.gradle.errorprone.ErrorProneCompiler$SelfFirstClassLoader.loadClass(ErrorProneCompiler.java:97)
09:55:36 	at java.lang.Class.getDeclaredMethods0(Native Method)
09:55:36 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
09:55:36 	at java.lang.Class.getMethod0(Class.java:2774)
09:55:36 	at java.lang.Class.getMethod(Class.java:1663)
09:55:36 	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:56)
09:55:36 	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:25)
09:55:36 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
09:55:36 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
09:55:36 	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
09:55:36 	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
09:55:36 	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
09:55:36 	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
09:55:36 	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:137)
09:55:36 	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:91)
09:55:36 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:55:36 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
09:55:36 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:55:36 	at java.lang.reflect.Method.invoke(Method.java:606)
09:55:36 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
09:55:36 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
09:55:36 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
09:55:36 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
09:55:36 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
09:55:36 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
09:55:36 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
09:55:36 	... 60 more
```

On investigating, it appears that this started happening shortly after the release of v2.0.6.  I also note the following commit in master: https://github.com/google/error-prone/commit/425b9c167800332da711299e7a7ca8211f728889

'Turn down travis JDK7 build
We only support JDK8 as of 884eec7.'

Is this for the internal build of the Error Prone JAR, or for users as well?  Because if the latter, that should be documented, and arguably requires a major version bump IMO.   If the former, however, I guess the build might need to use '-target 1.7' or equivalent so that it correctly produces 1.7-compatible class files.

PS: aside from that, thanks for Error Prone!  It's really helped our code quality and we appreciate it! ;)

**Comment by eaftan** [comment]
You're right, 2.0.6 requires users to run JDK 8, and we overlooked that when putting together the release notes.  Error Prone relies on javac internals, so we are tied to the same version of javac that we use inside Google, and we republish a versioned copy of javac for Error Prone (https://github.com/google/error-prone-javac/tree/1.9.0-dev-r2973-2).  Inside Google we actually don't use a released copy of javac, but build it from from head from the upstream OpenJDK repo.  We recently updated our version of javac to one built at r2973.  This is a snapshot of upstream javac 9.

javac requires JDK N-1 to run, that is, javac 9 requires JDK 8 to run.  Thus the update to a new javac requires Error Prone users to run on JDK 8.  

You're right that we should have bumped the version number by at least a minor version.  We'll do that for the next release.  And I'll update the release notes as well.

**Comment by jmason** [comment]
ok -- we'll version-lock on 2.0.5 until we get around to the JDK 8 upgrade tech debt, in that case.  cheers!

**Comment by lowasser** [comment]
For what it's worth -- I believe Error Prone is just tied to the *compiler* version, not the language version you're actually using?

**Comment by cushon** [comment]
Right, if you're able to run JDK8 on your dev machine but still need to use the Java 7 language and deploy to JDK7, you can use the latest version of Error Prone. Just make sure `-source` / `-target` / `-bootclasspath` is set to target Java 7.

**Comment by phinehasz** [comment]
> Right, if you're able to run JDK8 on your dev machine but still need to use the Java 7 language and deploy to JDK7, you can use the latest version of Error Prone. Just make sure `-source` / `-target` / `-bootclasspath` is set to target Java 7.

I want to set to target Java 7 , how can I modify my pom.xml? I just know 
`source>7</source>
                    <target>7</target>`
But I do not know how to set bootclasspath, and set what here? I cannot find in error-prone info & wiki any more. I am a amateur
