### ISSUE TITLE
Check that @Override annotation is used in all appropriate places

### ISSUE THREAD

**Issue by cushon** [google/error-prone#37]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=37) created by **eaftan@google.com** on 2012-08-28 at 09:42 PM_

---

Check that any method that overrides another method is annotated with @﻿Override.  Perhaps this shouldn't be an error but rather a warning.

**Comment by cushon** [comment]
Sounds good. The style guide says `@Override` should always be used, unless the parent method is `@Deprecated`.

**Comment by nglorioso** [comment]
This is in the current checker as MissingOverride
