### ISSUE TITLE
Forbid type parameters from being used as name qualifiers (!!)

### ISSUE THREAD

**Issue by kevinb9n** [google/error-prone#371]
It is beyond horrible that Java allows this:

```
static <T extends Foo> T populate(T.Builder builder) {
```

This is apparently treated exactly as if "Foo.Builder" were written, but anyone reading this code without a deep understanding of the language spec may assume that it does something much more special.

I can imagine no good reason to do this and it would be "nice" if it were made an error.  I don't necessarily have a persuasive argument at hand that it is *worth* adding this check, but I thought I'd file it for preliminary thought/discussion...

**Comment by dpryden** [comment]
+1 from me, for what it's worth.

**Comment by kevinb9n** [comment]
We just saw this in the wild again, so I recant my previous statement that this is probably not worth checking for.

**Comment by cushon** [comment]
fixed by a6b6154dcae830f7a83888bc676b345dd57f7d21
