### ISSUE TITLE
ErrorProneJavacPlugin unsupport jdk8?

### ISSUE THREAD

**Issue by cocodroid** [google/error-prone#3729]
when compile:

Error:java: java.lang.UnsupportedClassVersionError: com/google/errorprone/ErrorProneJavacPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by tbroyer** [comment]
Yes, since ErrorProne 2.11.0: https://github.com/google/error-prone/releases/tag/v2.11.0

> Error Prone now requires JDK 11 or newer

Also the first line of https://errorprone.info/docs/installation

> Please note that Error Prone must be run on JDK 11 or newer. (It can still be used to build Java 8 code by setting the appropriate `-source` / `-target` / `-bootclasspath` flags.)

**Comment by cocodroid** [comment]
@tbroyer can you support a config' example? thanks.
