### ISSUE TITLE
Internal usage of guava and caffeine `Cache` seems inconsistent

### ISSUE THREAD

**Issue by XN137** [google/error-prone#3759]
In https://github.com/google/error-prone/commit/e1acde927336e52bfcde8343979feff7ed84630a caffeine was added to the build:
```
This adds a new dependency on Caffeine; I considered using a Guava
Cache since we already depend on Guava, but Caffeine's version is 3
times as fast for this use case.
```

however on `master` a guava cache is also used in a few places:
https://github.com/google/error-prone/blob/1c3c09f5c286989f76eb545613c9ce91dac4acad/check_api/src/main/java/com/google/errorprone/dataflow/nullnesspropagation/inference/NullnessQualifierInference.java#L22-L24
https://github.com/google/error-prone/blob/1c3c09f5c286989f76eb545613c9ce91dac4acad/check_api/src/main/java/com/google/errorprone/dataflow/DataFlow.java#L21-L23

so i was wondering:
is this intentional or would there be value in unifying this?

- using caffeine could (allegedly) give a performance boost
- dropping caffeine would remove the extra dependency

**Comment by cushon** [comment]
We are slowly moving towards caffeine, PRs to migrate those usages of `common.cache` are welcome

**Comment by Sineaggi** [comment]
@cushon I've god a pr that should fix existing usages of `common.cache` here https://github.com/google/error-prone/pull/3796
