### ISSUE TITLE
Should `ASTHelpers.getSymbol(Tree)` be annotated with `@Nullable` ?

### ISSUE THREAD

**Issue by XN137** [google/error-prone#3760]
according to the method javadoc it can return `null` in multiple cases:
https://github.com/google/error-prone/blob/1c3c09f5c286989f76eb545613c9ce91dac4acad/check_api/src/main/java/com/google/errorprone/util/ASTHelpers.java#L244-L250

one of them being that it calls `getDeclaredSymbol` which is marked `@Nullable` already:
https://github.com/google/error-prone/blob/1c3c09f5c286989f76eb545613c9ce91dac4acad/check_api/src/main/java/com/google/errorprone/util/ASTHelpers.java#L219-L224

this seems kind of inconsistent.

there are of course multiple current usage spots where from the context + outer checks it is clear that it will not return `null` for example around `AssignmentTree.getVariable()` here:
https://github.com/google/error-prone/blob/1c3c09f5c286989f76eb545613c9ce91dac4acad/core/src/main/java/com/google/errorprone/bugpatterns/FieldCanBeLocal.java#L262-L269

but if the goal of the `@Nullable` annotation is to systematically force proper null handling maybe the annotation should be added.

WDYT ?
if it is an intentional decision, maybe there should be a comment about it to make it look less inconsistent.

**Comment by graememorgan** [comment]
Yes, I think so. I wonder if I/we accidentally deleted that at some point.

**Comment by XN137** [comment]
thanks for the quick feedback

closing since fixed by https://github.com/google/error-prone/commit/e08edcddf51fad0e5552e34986256aef1023d651
