### ISSUE TITLE
ArrayToString only warns for explicit toString calls not implicit ones (e.g. System.out.println(anArray))

### ISSUE THREAD

**Issue by MatrixFrog** [google/error-prone#380]
It would be awesome if it warned for calls like `System.out.println(anArray))` or `"" + anArray` which cause the Array's `toString` to be called even though there isn't a direct call to `anArray.toString()` in the source.

**Comment by cushon** [comment]
Detecting implicit toString calls in concatentation should be easy. `System.out.println` is harder - we could special case it, but preventing the general problem of calling toString on an object if the instance is an array is hard.

**Comment by cushon** [comment]
We already have checks for [concatenation](http://errorprone.info/bugpattern/ArrayToStringConcatenation) and [compound assignment](http://errorprone.info/bugpattern/ArrayToStringCompoundAssignment). I'm adding support for common print methods and will fold everything into ArrayToString.
