### ISSUE TITLE
How to use this compiler in Android Studio 2.0 Preview 4

### ISSUE THREAD

**Issue by rhonyabdullah** [google/error-prone#382]
I was install this plugin and try to use this plugin by following this [link](https://plugins.jetbrains.com/plugin/7349?pr=androidstudio) but when i go to "File | Settings | Compiler" i didn't see any  'Java Compiler' tab which mean i can't choose the 'Javac with error-prone', anybody can help ? or this is unavailable for Android Studio 2.0 Prev 4 ?

**Comment by chalup** [comment]
See https://github.com/chalup/gradle-android-studio-edit-issue for the
basic setup.

**Comment by rhonyabdullah** [comment]
Oh thank you !
