### ISSUE TITLE
Use of alternative names when flagging checks on/off causes problems when checks share a name

### ISSUE THREAD

**Issue by AlexLandau** [google/error-prone#3831]
The change at https://github.com/google/error-prone/commit/48bbef0e51c2f5098efe6a2587fafc0ebc31bca5 (first published in 2.17.0) made it so if a check (e.g. UtilizeFoo) has an alternative name specified (e.g. UseFoo), you can modify its severity in the compiler plugin arguments with something like -Xep:UseFoo:ERROR. So far, so good.

Unfortunately, we’ve run into some really annoying consequences of this in situations where one check (e.g. ImmutableEnumChecker or [StrictUnusedVariable](https://github.com/palantir/gradle-baseline/blob/1ee4197524b3cc71a3a9e5b95ca2dbdbecf3e1f9/baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/StrictUnusedVariable.java)) has an alternative name that is also the name of another check (e.g. Immutable or UnusedVariable).

This typically happens where if a more lenient check (UnusedVariable) is disabled, then we also want to disable the stricter version of the check (StrictUnusedVariable). But let’s say we’re in a situation where -XepDisableAllChecks is used (or none of the checks are at the level we want by default), and we want to turn on only the more lenient version of the check. Then what?

* If you pass in -Xep:UnusedVariable:ERROR, then both checks are set to ERROR.
* If you pass in the arguments -Xep:StrictUnusedVariable:OFF and -Xep:UnusedVariable:ERROR in either order, then UnusedVariable is turned on, and StrictUnusedVariable will be either on or off, depending on the vagaries of [an unordered HashMap](https://github.com/google/error-prone/blob/baba0c5d945f78aa7530091c28022cf202fe821c/check_api/src/main/java/com/google/errorprone/ErrorProneOptions.java#L262). Whichever argument is processed last [in ScannerSupplier#applyOverrides](https://github.com/google/error-prone/blob/7f9ce8bbcf0275a713fa335f9a2c1ab43bc13b22/check_api/src/main/java/com/google/errorprone/scanner/ScannerSupplier.java#L182-L228) will take precedence.

Some options for fixing this:

1. Change the HashMap into a LinkedHashMap so the arguments are processed in order (at least when each check name is listed only once) — this still means “-Xep:StrictUnusedVariable:OFF -Xep:UnusedVariable:ERROR” will have a surprising effect, but at least there is some way to specify the correct behavior.
2. If a -Xep argument matches a check’s canonical name, don’t modify checks for which it is an alternate name. This fixes the surprising behavior while maintaining some options for alternative names that affect groups of checks. (This should be paired with the LinkedHashMap fix for the less-common cases where it would still be relevant.)
3. Revert the behavior change.

**Comment by cushon** [comment]
Thanks for the report!

I agree that, at minimum, the logic here should be using an ordered map so the last flag passed 'wins'.

Do you see any downsides for (1), or would that work well enough for your use-case?

**Comment by AlexLandau** [comment]
Based on my testing, (1) is enough for us to work around the issue (though we will have to be more careful about it than if (2) or (3) were done).

**Comment by AlexLandau** [comment]
We've upgraded to 2.19.1 and the change to make the behavior consistent is working.
