### ISSUE TITLE
How can refaster be used from error-prone?

### ISSUE THREAD

**Issue by JnRouvignac** [google/error-prone#384]
Hello,

I have found that this [commit](https://github.com/google/error-prone/commit/01f713649844a4cc331d8055d7a1e2f693e2e8b0) moved [refaster](https://github.com/google/Refaster) code to error-prone code base.
Is it possible to use refaster with error-prone? And how is it possible?

Thanks!

**Comment by lowasser** [comment]
The code is in, but there's not yet any way to use it.  That's a work in progress.

**Comment by JnRouvignac** [comment]
That's a pity. Good to know somebody is working on it though!

Is this effort publicly visible?
Will you update the current issue once this effort will be completed?

**Comment by eaftan** [comment]
Typically we do development internally and then periodically (~once per week) sync our internal changes with Github.  So the code will be visible within a week of when we finish the work.  We'll do our best to remember to update this issue when it's ready.

To set expectations, I don't think this is going to happen this quarter.  @lowasser would know better.

**Comment by alexeagle** [comment]
Interesting, I just presented Error Prone at an angular meetup (because I want to show the power of compiler checks and do it in TypeScript) and one questioner came up afterwards specifically asking about searching code using an example. I showed him refaster in the repo but couldn't find any example. Glad to know it's in progress.

**Comment by JnRouvignac** [comment]
@lowasser @eaftan Has Google position changed over the last year? Was there work performed towards solving this issue?

**Comment by eaftan** [comment]
Sorry for not updating this bug.  @nglorioso did this.  Instructions are here: http://errorprone.info/docs/refaster

**Comment by JnRouvignac** [comment]
Thanks for the update!
