### ISSUE TITLE
Example for setting up in gradle project

### ISSUE THREAD

**Issue by gowtham3105** [google/error-prone#3870]
Setting up the project in a  gradle project is causing a lot of errors, just would be helpful if we can get an example

**Comment by tbroyer** [comment]
You should have all that's needed in https://github.com/tbroyer/gradle-errorprone-plugin#readme

I'd [configure](https://github.com/tbroyer/gradle-errorprone-plugin#configuration) `disableWarningsInGeneratedCode.set(true)` and/or `excludedPaths.set(".*/build/generated/.*")` (or similar), particularly if you're adding it in an existing project.
