### ISSUE TITLE
Mention Bazel on the Installation page

### ISSUE THREAD

**Issue by ulfjack** [google/error-prone#389]
Bazel has Errorprone enabled by default, and this should be mentioned somewhere.

**Comment by cushon** [comment]
Will do, thanks. The docs haven't received a lot of attention recently, and they mostly predate Bazel being open source.

**Comment by alexeagle** [comment]
Looks like this was done in https://github.com/google/error-prone/commit/5f65e9653add2965423d8c2e98dedd820b4fc325
