### ISSUE TITLE
java7 forked ant: classpath problems?

### ISSUE THREAD

**Issue by cal101** [google/error-prone#398]
Hi!

I wanted to try error prone on some project using ant integration for forked javac as done in the example:

```
<componentdef name="errorprone" classname="com.google.errorprone.ErrorProneExternalCompilerAdapter"
          classpath="../../lib/error_prone_ant-2.0.5.jar"/>
```

I changed to 2.0.5 because we compile this project with java 7 and that seems to me the last version supporting java7.
The project uses an older version of guava.

In the javc element I added

```
<errorprone/>
```

I tried to compile but got compile errors that make me believe that the newer version of guava that is included in the error prone jar is used on compile classpath instead of the older project version.

**Comment by eaftan** [comment]
You should be able to use the latest version of Error Prone and still *target* Java 7 via "-source 7 -target 7"; you just have to run on a Java 8 VM.  

Could you try updating to the latest version and seeing if this bug is still here?  It's certainly possible we're not setting up the classpath correctly.  Also, could you include the compile errors you are seeing?

**Comment by cal101** [comment]
We are using javac fork to de-couple the build tool java version from the compile version.
Because error prone 2.0.8 was compiled with java 8 I had to change the ant java to java8, too.

Is there some way to get a standalone "javac" with error-prone included to decouple the runtimes of build tool and compiler?

Using error prone 2.0.8 I got the same compile error as above:

```
error: constructor Stopwatch in class Stopwatch cannot be applied to given types;
    [javac]         Stopwatch stopwatch = new Stopwatch().start();
    [javac]                               ^
    [javac]   required: Ticker
    [javac]   found: no arguments
    [javac]   reason: actual and formal argument lists differ in length
```

The guava version that the project uses in it's classpath has the following constructor defined:

```
public Stopwatch() {
    this(Ticker.systemTicker());
  }
```

I checked the classpath and I didn't find another guava version so it seems that's definition comes from error prone.
