### ISSUE TITLE
Replace newInstance() with getConstructor().newInstance()

### ISSUE THREAD

**Issue by kevinb9n** [google/error-prone#407]
Class.newInstance() is in discussion to be deprecated in Java 9, and for good reason -- it allows magical mystery checked exceptions to be thrown out of nowhere!

When replacing calls with getConstructor().newInstance(), there are additional exception types thrown (the best approach is just to catch ReflectiveOperationException rather than all four individually), including ITE which wraps any thrown checked exception, solving the problem above.

**Comment by cushon** [comment]
Implemented in 900e1087f75e9985a6849614c5daaedc46009b61

It includes fixes to add `ReflectiveOperationException` to the enclosing catch blocks, or else the enclosing method's throws clause.
