### ISSUE TITLE
CollectionIncompatibleType could handle assertThat(...).doesNotContain(...), etc.

### ISSUE THREAD

**Issue by cpovirk** [google/error-prone#409]
(These are part of Truth.)

The "does not" methods are probably the most interesting, since bad arguments will silently succeed. But of course, if we can handle then, we can easily handle "does contain," too, turning failed tests into compile errors.
- `MapSubject.doesNotContainEntry`
- `MapSubject.doesNotContainKey`
- ditto `MultimapSubject`

I call this case out specifically because it requires looking at not the type of the receiver object but the type of the argument to the previous call in the fluent chain.

[@kevinb9n in case this has any bearing on `@TypeCompatibleWith`]

**Comment by kevinb9n** [comment]
Quite possible that this is too hard to represent with @TypeCompatibleWith and would require hardcoding...

**Comment by cpovirk** [comment]
This appears to have happened for stuff, e.g., https://github.com/google/error-prone/blob/03dc33879a9b3fdefbcea4c0082365abd5fe4a42/core/src/main/java/com/google/errorprone/bugpatterns/collectionincompatibletype/TruthIncompatibleType.java#L97
