### ISSUE TITLE
Identify uses of c.g.c.base.Function where j.u.f.Function is required (or vice versa)

### ISSUE THREAD

**Issue by cpovirk** [google/error-prone#410]
Normally, you can use a `c.g.c.base.Function` where a `j.u.f.Function` is required. (Or at least that will be the case once Guava begins to require Java 8 and can make its extend the JDK's.) But that's not true when you're overriding a function.

And you can't use a `j.u.f.Function` where a `c.g.c.base.Function` is required. In this case, though, the thing to fix is likely often the `c.g.c.base.Function`-accepting method.

Users can do this all themselves, of course. But javac has extremely unhelpful ways of saying "You're using the wrong `Function`." Error Prone could do better. It could suggest fixes in many cases, but the main important thing is just to have a sane error message.

(All this goes for `Predicate` and `Supplier`, too. A similar but somewhat different case is `Optional`.)

Examples:

---

Parameter is `c.g.c.base.Function`, not `j.u.f.Function`, and I'm trying to `@Override`:

```
java/com/google/common/labs/collect/FluentFunction.java:170: error: method does not override or implement a method from a supertype
  @Override
  ^
```

Error Prone could suggest changing the `Function` I'm using.

---

Parameter is `c.g.c.base.Function`, not `j.u.f.Function`, and I'm trying to pass a `j.u.f.Function`:

```
java/com/google/common/labs/collect/FluentFunction.java:174: error: constructor CompositeFunction in class CompositeFunction<F#2,T#2,R#2> cannot be applied to given types;
    return new CompositeFunction<R, F, T>(before, this);
           ^
  required: com.google.common.base.Function<? super R#1,? extends F#1>,java.util.function.Function<? super F#1,? extends T#1>
  found:    java.util.function.Function<CAP#1,CAP#2>,FluentFunction<F#1,T#1>
  reason: argument mismatch; java.util.function.Function<CAP#1,CAP#2> cannot be converted to com.google.common.base.Function<? super R#1,? extends F#1>
  where R#1,F#1,T#1,F#2,T#2,R#2 are type-variables:
    R#1 extends Object declared in method <R#1>compose(java.util.function.Function<? super R#1,? extends F#1>)
    F#1 extends Object declared in class FluentFunction
    T#1 extends Object declared in class FluentFunction
    F#2 extends Object declared in class CompositeFunction
    T#2 extends Object declared in class CompositeFunction
    R#2 extends Object declared in class CompositeFunction
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object super: R#1 from capture of ? super R#1
    CAP#2 extends F#1 from capture of ? extends F#1
1 error
```

Error Prone could suggest `before::apply`, although, in this case, I actually wanted to fix the method I'm calling. (I suppose it could do that, too, but only if the method is in the same file. The change from `c.g.c.base.Function` to `j.u.f.Function` should mostly be safe(?), though it's not binary compatible.)

**Comment by cpovirk** [comment]
I guess I have no idea if Error Prone even gets to run in the case of a javac error. If so, feel free to consider this a suggestion to improve javac's error message in this case if that's practical.

**Comment by kevinb9n** [comment]
(This check applies to Guava 21.0 and higher.)

**Comment by cpovirk** [comment]
This would have to happen in javac.
