### ISSUE TITLE
ImmutableEnumChecker in Enum where an attribute is a Record type which is immutatble

### ISSUE THREAD

**Issue by gigantic2** [google/error-prone#4122]

**Comment by graememorgan** [comment]
I'm extrapolating a bit from your description, but is your complaint that Kotlin records are immutable, and so shouldn't be flagged by ImmutableEnumChecker?

Kotlin records are not _deeply_ immutable, only _shallowly_. ImmutableEnumChecker is looking for _deep_ immutability.
