### ISSUE TITLE
All checks should treat `String#formatted` the same as `String#format`

### ISSUE THREAD

**Issue by ksobolew** [google/error-prone#4170]
I'm reporting this mostly for `StringFormatWithLiteral`, which does not trigger on `String#formatted` when it would trigger if it was `String#format` instead. But I seem to remember that this also holds true for other checkers. If not, I would suggest making this uniform across all checks and treat `String#format` and `String#formatted` the same way always.

**Comment by graememorgan** [comment]
We've taken a pass through these and updated them, but please let us know if you find any checks we missed!

**Comment by ksobolew** [comment]
Will do, thank you!
