### ISSUE TITLE
CheckReturnValue should allow custom annotations

### ISSUE THREAD

**Issue by andrewgaul** [google/error-prone#422]
Currently `CheckReturnValue` only works with `javax.annotation.CheckReturnValue`.  It should also allow for custom annotations with the same name to warn about APIs like assertj which have their own annotation joel-costigliola/assertj-core#695.

**Comment by vanniktech** [comment]
How about just simply checking for the simple name, `CheckReturnValue`? Then the package would not matter at all even `com.foo.bar.abc.CheckReturnValue` would be caught.
