### ISSUE TITLE
[Feature request] Isolating running BugCheckers from Java Compiler API

### ISSUE THREAD

**Issue by elkkhan** [google/error-prone#4247]
Hi all,
I'm developing an IDE plugin for ErrorProne and after analysing sources from both error-prone and the IDE SDK, it looks like it's a little challenging to use error prone as a "checker" in external projects. This is mainly because of how ErrorProne is architected - it's tightly coupled with Java Compiler API and from what I can see there are no interfaces that abstract the Java Compiler API away - use of ASTs and `TaskListener`s throughout the project make it hard to apply errorprone checks to non-AST abstractions of java code.

I'm mainly creating this issue in hopes of getting some opinions from maintainers on whether it would be worth changing the codebase in a way that ASTs and Java Compiler APIs are abstracted away.
This would mainly include refactoring `ErrorProneAnalyzer`, `ErrorProneScanner` and any classes they interact with.

As a disclaimer, I may be way off with this - I still don't completely understand how Error Prone works internally.

I understand this would be a huge change - an alternative for me would be to use and "embedded" compiler also built on top of Java Compiler API (something like [google-compile-testing](https://github.com/google/compile-testing)), but the main feature I'm planning to develop in the plugin is on-the-fly checks which the IDE has great support for - and I'm a little sceptical about performance implications of running this "embedded" compiler each time a file is changed.

Since this would be a very big piece of work, this "feature request" issue is not really a feature request but more of a thread.
If what I'm proposing sounds feasible, I'm happy to fork the repo and work on it and contribute a PR if/once it's done.

Let me know your thoughts,
Thanks!

**Comment by elkkhan** [comment]
Worth to note that I do understand that an AST is still required for bug checkers to work and error-prone can't simply operate on `.java` files, but what I'm trying to figure out is whether there's a way of "adapting" between ASTs - say, IntelliJ PSI -> Java AST in my case

**Comment by cushon** [comment]
Hello!

Thanks for raising this issue. I agree this would be nice to support, and I also agree it would be a huge change.

We have done some preliminary investigations into creating an API that abstracts over all of the information Error Prone access from the Java compiler, and that could be implemented by different compilers (e.g. one each for Javac, and IntelliJ, and Eclipse). I think it would be possible to do that, but the surface area of the APIs that need to be adapted is very large, so it would be a major API design project.

Which IDE are you working on a plugin for?

**Comment by elkkhan** [comment]
Hi @cushon, thanks for the reply! 

I'm working on a plugin for IntelliJ, so the other side of the bridge would be [IntelliJ PSI](https://plugins.jetbrains.com/docs/intellij/psi.html)

I agree that it's a very major piece of work. After opening this issue, I gave this more thought and I believe a more feasible approach for me would be implementing this using the "embedded compiler" approach i mentioned in the original post. What do you think?
I still need to profile this to see whether it introduces a major overhead - so just shooting in the dark with this.

**Comment by cushon** [comment]
The 'embedded compiler' approach you describe sounds like it could work, and potentially be much simpler, so that sounds worth investigating to me.

Have you seen https://plugins.jetbrains.com/plugin/7349-error-prone-compiler, or do you want something more tightly integrated that can interoperate with PSI for your use-case?

**Comment by elkkhan** [comment]
Thanks a lot for you input, i'll take that route then.

Yes, I've seen this plugin but I have something more integrated in mind - I'm planning to implement most of/all feature set of ErrorProne in a way that it can be managed through the plugin, such as:
- Running the checks from the IDE on a file/module/project/package etc.
- On the fly (as you type) checks that show up as errors/warnings in the editor
- Ability to apply the suggested fixes as intelliJ quick-fixes
- Configuring BugPatterns (turn on/off, group, change severity, add new ones etc.)
- As a bonus, some kind of an integration with Refaster, although I didn't give this one much thought so it's a bit far fetched for now
