### ISSUE TITLE
Some BugPattern docs are missing code examples

### ISSUE THREAD

**Issue by elkkhan** [google/error-prone#4248]
>Each bug pattern includes code examples of both positive and negative cases; these examples are used in our regression test suite.

this statement from the website BugPatterns section doesn't hold for some BugPatterns - [example 1](https://errorprone.info/bugpattern/DeadException), [example 2](https://errorprone.info/bugpattern/DiscardedPostfixExpression)

**Comment by cushon** [comment]
Thanks for pointing that out. We have moved away from including postive and negative examples for all checks, those docs should be updated to reflect that.

**Comment by elkkhan** [comment]
@cushon thanks for the response, can you take a look at the attached PR pls?
