### ISSUE TITLE
Debug test in error-prone

### ISSUE THREAD

**Issue by sergiofigueras** [google/error-prone#428]
Hello guys,

I've checked out error-prone-parent and it goes ok when I run a `mvn clean install`.

But the fact is that I'm trying to extend a BugChecker and start to create my own BugChecker. So, for this, I'm trying to debug a test inside of it using IntelliJ.

But I just can't do it. When I try to run a single test, I got problems like these:

<img width="822" alt="captura de tela 2016-07-13 as 13 00 29" src="https://cloud.githubusercontent.com/assets/1733227/16810316/d394a392-48f9-11e6-93d8-44261ce113c3.png">

So far to resolve this issue, I've tried to add the -Xbootclasspath errorprone-javac argument in VM, Test argument, but the problem was not resolved.

What I'm missing, guys?

Thanks.

**Comment by cushon** [comment]
IntelliJ might be putting the JDK's javac first on the classpath. Can you try opening `Project Structure > Modules > error_prone_core > Dependencies` and moving `com.google.errorprone:javac:1.9.0-dev-r2973-2` to the top?

**Comment by sergiofigueras** [comment]
Thanks Cushon! :) So, I've changed the order and now it is giving me another errors, ex:

<img width="1106" alt="captura de tela 2016-07-13 as 14 31 39" src="https://cloud.githubusercontent.com/assets/1733227/16813118/946cfa68-4906-11e6-9ac8-82d59019779d.png">

Also, I checked that are some classes that are in wrong packages, ex:

AnyOfTemplateExample is in com.google.errorprone.refaster.testdata.input, but it's declared in com.google.errorprone.refaster.testdata .

Is it ok? Why are those errors occurring?

**Comment by cushon** [comment]
You probably want to exclude everything in `.../testdata/...` from the build path.

**Comment by sergiofigueras** [comment]
Thanks, Cushon! 👍

**Comment by JakeWharton** [comment]
This would make a great addition to the wiki on building in IntelliJ: https://github.com/google/error-prone/wiki/For-Developers#intellij
