### ISSUE TITLE
Errorprone 2.0.10 version

### ISSUE THREAD

**Issue by sergiofigueras** [google/error-prone#429]
Hello guys,

Do you imagine when the 2.0.10 version will be rolled out?

Thanks

**Comment by cushon** [comment]
@eaftan I think we're planning to do a release in the next few days.

**Comment by eaftan** [comment]
Yes, hopefully today or Friday.  @captain5050 is taking care of it.

**Comment by cushon** [comment]
2.0.10 was [released](https://groups.google.com/d/topic/error-prone-discuss/EkYntFTL_bQ/discussion).
