### ISSUE TITLE
Problem running maven sample plugin

### ISSUE THREAD

**Issue by sergiofigueras** [google/error-prone#430]
Hello guys,

I'm trying to execute the maven sample plugin (https://github.com/google/error-prone/tree/master/examples/plugin/maven), but it's not working. I just got the sources, then compiled the sample_plugin, and then I executed com.google.errorprone.sample.Hello without any error being displayed.

Is there any special configuration?

**Comment by cushon** [comment]
Here's how I tested that example:

```
$ cd examples/plugin/maven
$ mvn package
...
Hello.java:24: error: [MyCustomCheck] String formatting inside print method
    System.err.print(String.format("Hello: %s\n", Arrays.toString(args)));
                    ^
    (see example.com/bugpattern/MyCustomCheck)
  Did you mean 'System.err.printf("Hello: %s\n", Arrays.toString(args));'?
1 error
```
What maven commands are you running?

**Comment by sergiofigueras** [comment]
Ok Cushon, got it working. :)

The problem was that I've created a concrete BugChecker (DefaultBugChecker extends BugChecker) and I added @AutoService(DefaultBugChecker.class)

But then I've changed to @AutoService(BugChecker.class) and got it working. Thanks!

**Comment by cushon** [comment]
Great! If you seen any places where things were unclear or poorly documented, feel free to suggest improvements or send a pull request.
