### ISSUE TITLE
ObjectEqualsForPrimitives should not suggest to convert boxed equals on double or float values

### ISSUE THREAD

**Issue by findepi** [google/error-prone#4390]
https://errorprone.info/bugpattern/ObjectEqualsForPrimitives check is described as "performance" related, so if I follow it, I would not expect the semantics to change. 
Currently, ObjectEqualsForPrimitives applies to all primitives and enums. 
However, double and float values should be exempted from the check:

```java
double a = Double.NaN;
double b = Double.NaN;

System.out.println(Objects.equals(a, b)); // true; flagged by ObjectEqualsForPrimitives check
System.out.println(a == b); // false
```

In current master of https://github.com/trinodb/trino, the ObjectEqualsForPrimitives triggers typically in equals() implementations. While most double/float values are unlikely to be NaN, this is not something and equals() implementation should be concerned about. 

It's probably worth noting that equals generated for Java record classes also compares NaN values as equal (as if `Objects.equals` was used)

**Comment by ksobolew** [comment]
Is `Double.compare(a, b) == 0` a valid substitute? No boxing, but perhaps a more expensive operation.

**Comment by findepi** [comment]
@ksobolew you're right.
So the check is probably valid also for float/double, but it maybe its message could be tailored down to prevent people like me from improving the code incorrectly.

**Comment by findepi** [comment]
the request here is invalid.
the idea to improve error message logged as new issue -- https://github.com/google/error-prone/issues/4392
