### ISSUE TITLE
Disable @CheckReturnValue checking if the previous statement is ExpectedException.expect

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#446]
Similar to #385, I think it would be great relax the check for unused return values in the following code:

```
@Rule public ExpectedException thrown = ExpectedException.none();

@Test test() {
  ...
  thrown.expect(SomeException.class);
  Foo.foo();
}
```

**Comment by eaftan** [comment]
(For our own tracking) We have an internal bug for this: b/27481112

**Comment by cushon** [comment]
this happened in e0abc47ab95cd0c3cbf2b7b963321095e02eaef1
