### ISSUE TITLE
[2.29.1] JPMS Module metadata was removed

### ISSUE THREAD

**Issue by ben-manes** [google/error-prone#4480]
I tried upgrading to 2.29.0 / 2.29.1 and it fails due to
```console
> Task :caffeine:compileJava FAILED
/Users/ben/projects/caffeine/caffeine/src/main/java/module-info.java:6: error: module not found: com.google.errorprone.annotations
  requires static com.google.errorprone.annotations;
```

I tried to follow the previous [validation steps](https://github.com/google/error-prone/pull/4311#issuecomment-1990316489):

```bash
# 2.28.0: module-info, not in manifest
$ wget -q https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.28.0/error_prone_annotations-2.28.0.jar
$ unzip -q error_prone_annotations-2.28.0.jar META-INF/MANIFEST.MF
$ grep Automatic-Module-Name META-INF/MANIFEST.MF
$ unzip -q error_prone_annotations-2.28.0.jar META-INF/versions/9/module-info.class
$ javap -v META-INF/versions/9/module-info.class | grep "open module"
open module com.google.errorprone.annotations@2.28.0

# 2.29.1: no module definition
$ wget -q https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.29.1/error_prone_annotations-2.29.1.jar
$ unzip -q error_prone_annotations-2.29.1.jar META-INF/MANIFEST.MF
$ grep Automatic-Module-Name META-INF/MANIFEST.MF
$ unzip -q error_prone_annotations-2.29.1.jar META-INF/versions/9/module-info.class
caution: filename not matched:  META-INF/versions/9/module-info.class
```

The `module-info.java` file was removed in [Handle static members in inner classes in *CanBeStatic checks](https://github.com/google/error-prone/pull/4426) (https://github.com/google/error-prone/commit/39609bf269465e2a1204aa3039fbd6ea66a9b067) which seems unrelated.

**Comment by cpovirk** [comment]
Well, that's weird.

As best I can tell from poking around a little, there may have been some change in a service that Copybara delegates to. I have a repro command that I'll share with the Copybara team after I get back from an appointment.

**Comment by cushon** [comment]
Thanks Chris! You got farther than I did investigating, please loop me in when you share the repro.

**Comment by cpovirk** [comment]
https://github.com/google/error-prone/pull/4482 has restored the file. Over to @cushon for a release.

**Comment by cushon** [comment]
I released the fix in https://github.com/google/error-prone/releases/tag/v2.29.2
