### ISSUE TITLE
Remove @CheckReturnValue error in last line of assertThrows/expectThrows

### ISSUE THREAD

**Issue by cpovirk** [google/error-prone#452]
Coming in JUnit 4.13: https://github.com/junit-team/junit4/pull/1154

**Comment by eaftan** [comment]
Created internal bug b/31151913 so we don't lose track of this.

**Comment by cpovirk** [comment]
Fixed by https://github.com/google/error-prone/commit/f9ea34b52ace79c5f3e1d39fd0f1ade2eba9b06a
