### ISSUE TITLE
Mark java.util.Optional<T> as well-known immutable container

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#454]
The class `WellKnownMutability` contains an entry only for Guava's Optional in `KNOWN_IMMUTABLE`, but not for the JDK's Optional. This means that the `ImmutableChecker` will not allow marking classes as `@Immutable` with fields of type `java.util.Optional`.

**Comment by PhilippWendler** [comment]
In fact, there are also a few other classes I would suggest to add, e.g., `BigInteger`, and I expect maybe more might come up in the future. What is your desired way of proposing such additions? File a separate issue for each group of them, or collect them all in one ticket? Or do you prefer a pull request adding lines to `WellKnownMutability`?

Are proposals to add further Guava classes welcome (e.g., `UnsignedInteger`), or do you plan on adding Error-Prone's `@Immutable` to them directly?

**Comment by Stephan202** [comment]
Some applicable types configured in [MutabilityDetector](https://github.com/MutabilityDetector/MutabilityDetector/):
* [JDK](https://github.com/MutabilityDetector/MutabilityDetector/blob/master/src/main/java/org/mutabilitydetector/config/JdkConfiguration.java)
* [Guava](https://github.com/MutabilityDetector/MutabilityDetector/blob/master/src/main/java/org/mutabilitydetector/config/GuavaConfiguration.java)

**Comment by PhilippWendler** [comment]
Any answer for my question in my previous comment on how to report such requests?

Currently I would like to see `BigInteger`, `File`, `Path, `URL`, and `URI` added.

**Comment by cushon** [comment]
I'd be happy to take a pull request for those.

We may start adding `@Immutable` to more guava classes, but using `WellKnownMutability` as a stop-gap is OK too.
