### ISSUE TITLE
Documentation of JDK version is outdated

### ISSUE THREAD

**Issue by mernst** [google/error-prone#4570]
https://errorprone.info/docs/installation says, "Please note that Error Prone must be run on JDK 11 or newer."  That should be updated to "JDK 17 or newer."

**Comment by gemmellr** [comment]
There are other fixups that could be made, e.g there are references to running on older JDKs like JDK 9 and JDK 16, seems like at least some of those could be cleaned up given ErrorProne 2.32.0 no longer runs on anything less than 17.

**Comment by cushon** [comment]
Thanks, I'll take a pass over the installation docs to update those references

**Comment by cushon** [comment]
I made an update in https://github.com/google/error-prone/commit/d09f60b6a66c9714b6c7da19fb9c3bc1c2292ab1, feel free to let me know if you see any other references to JDK 11 I missed
