### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin

### ISSUE THREAD

**Issue by Luis-Pascoal** [google/error-prone#4601]
error-prone version: 2.10.0
     BugPattern: InvalidParam
     Stack Trace:
     java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.DCTree$DCDocComment com.sun.tools.javac.tree.DocCommentTable.getCommentTree(com.sun.tools.javac.tree.JCTree)'

**Comment by cushon** [comment]
2.10.0 is an older release, can you try using the latest version of Error Prone (currently 2.33.0) and see if that fixes the issue?

**Comment by cushon** [comment]
This was fixed in Error Prone 2.28.0 by https://github.com/google/error-prone/commit/2dde25434696cc2f87e76b64bf60d8875da36a09
