### ISSUE TITLE
unhandled exception was thrown by the Error Prone static analysis plugin

### ISSUE THREAD

**Issue by GowthamGthm** [google/error-prone#4607]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project Gthm: Compilation failure  
[ERROR] /E:/MyCode/JAVA/MAP-STRUCT/map-struct/src/main/java/com/gthm/libraries/mapstruct/dto/AddressEntityDto.java: An unhandled exception was thrown by the Error Prone static analysis plugin.
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]   
[ERROR]      error-prone version: 2.33.0
[ERROR]      BugPattern: (see stack trace)
[ERROR]      Stack Trace:
[ERROR]      java.lang.IllegalAccessError: class com.google.errorprone.VisitorState$SharedState (in unnamed module @0x68ef01a5) cannot access class 
com.sun.tools.javac.comp.Modules (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.comp to unnamed module @0x68ef01a5
[ERROR]         at com.google.errorprone.VisitorState$SharedState.<init>(VisitorState.java:753)
[ERROR]         at com.google.errorprone.VisitorState.<init>(VisitorState.java:205)
[ERROR]         at com.google.errorprone.VisitorState.createConfiguredForCompilation(VisitorState.java:126)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScannerTransformer.createVisitorState(ErrorProneScannerTransformer.java:54)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
[ERROR]         at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:227)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:133)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1443)

**Comment by GowthamGthm** [comment]
My plugins is as given below - 

<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>

			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>17</source>
					<target>17</target>
					<compilerArgs>
						<arg>-XDcompilePolicy=simple</arg>
						<arg>-Xplugin:ErrorProne</arg>
						<arg>--add-opens</arg>
						<arg>jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
					</compilerArgs>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>${lombok-mapstruct-binding.version}</version>
						</path>
						<path>
							<groupId>com.google.errorprone</groupId>
							<artifactId>error_prone_core</artifactId>
							<version>2.33.0</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>

**Comment by tbroyer** [comment]
> [ERROR] java.lang.IllegalAccessError: class com.google.errorprone.VisitorState$SharedState (in unnamed module @0x68ef01a5) cannot access class
> com.sun.tools.javac.comp.Modules (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.comp to unnamed module @0x68ef01a5

You're missing JVM arguments: https://errorprone.info/docs/installation
