### ISSUE TITLE
Compiler flag to ignore generated code is undocumented

### ISSUE THREAD

**Issue by vprithvi** [google/error-prone#463]
The compiler flag `-XepDisableWarningsInGeneratedCode` isn't in the official [documentation](http://errorprone.info/docs/flags)

The [release instructions](https://github.com/google/error-prone/wiki/Releasing) doesn't specify how one adds documentation for command line flags. It seems to be a manual process.

**Comment by Stephan202** [comment]
Cool, didn't know about this flag. Cursory inspection indicates that generated code is identified by the presence of the `@Generated` annotation. I've just tested this; works well. I can now re-enable a bug pattern to which some of our `wsimport`/`xjc`-generated code does not comply. Nice :)

**Comment by JamesMcMahon** [comment]
Very useful flag that isn't documented at all. I'd love to see this rectified.

**Comment by storix** [comment]
Even with this flag I'm still getting warnings regarding Dagger's generated code.

**Comment by jaredsburrows** [comment]
I am also seeing issues with Databinding.

**Comment by tbroyer** [comment]
This has been added in https://github.com/google/error-prone/commit/9f9f23adeb9dfaa3e1f877d9be8b56d9c824194d a few days ago.

**Comment by jaredsburrows** [comment]
@tbroyer Hows does it work? Are we forced to write a custom patch?

**Comment by tbroyer** [comment]
@jaredsburrows Not sure I understand your question, but `-XepDisableWarningsInGeneratedCode` will disable/remove/ignore warnings (not errors!) in code annotated with `@Generated`: https://github.com/google/error-prone/issues/329#issuecomment-117318164

**Comment by jaredsburrows** [comment]
You said in your previous comment:
> This has been added in 9f9f23a a few days ago.
The `-XepDisableWarningsInGeneratedCode` argument has been in error prone for some time right? https://github.com/google/error-prone/blame/master/check_api/src/main/java/com/google/errorprone/ErrorProneOptions.java#L56

**Comment by tbroyer** [comment]
This issue is about the flag's documentation. http://errorprone.info/docs/flags
The flag itself has been added in 2.0.6.

**Comment by xenoterracide** [comment]
just encountered this due in part to the immutables library, and I too am noticing there is not a corresponding flag to ignore ERROR which I have some of, because I set `MissingOverride` and `Var` to error so that they fail the test, of course I don't care if generated code does this. could open a new bug to add that flag.

**Comment by msridhar** [comment]
@xenoterracide you can now disable EP on generated code entirely if desired with the `-XepExcludedPaths` flag.  It's documented [here](http://errorprone.info/docs/flags)

**Comment by vorburger** [comment]
@xenoterracide you may also be interested in https://github.com/google/error-prone/issues/808
