### ISSUE TITLE
Most recent travis commit hook broke public pages

### ISSUE THREAD

**Issue by nglorioso** [google/error-prone#464]
https://github.com/google/error-prone/commit/3dace74bba6ad16f83d6157231d76fcf3124b0fc

Not sure what happened here, but there were a few modest changes to the formatting of Javadoc, however all of the bugpatterns/ files disappeared

**Comment by cushon** [comment]
Looks like something timed out:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project error_prone_parent: SiteToolException: The site descriptor cannot be resolved from the repository: ArtifactResolutionException: Unable to locate site descriptor: Could not transfer artifact org.sonatype.oss:oss-parent:xml:site_en:7 from/to sonatype-apache (https://repository.apache.org/releases/): Connect to repository.apache.org:443 [repository.apache.org/207.244.88.143] failed: Connection timed out
```

I regenerated the docs manually, and attempted to make the script not ignore errors.

**Comment by cushon** [comment]
The latest commit is back to normal: cc26f91fbbf9522d905b5f4327f3e054d526a31b, and ffeedb603224f1e7c99c4a79d10c4fd8e8e94e41 should prevent it from deleting everything if the build times out again.
