### ISSUE TITLE
BugPattern pages on website are all missing

### ISSUE THREAD

**Issue by cheister** [google/error-prone#465]
It looks like none of the BugPattern links are working on the public website.  They all return 404 for me.

e.g. 
http://errorprone.info/bugpattern/BadAnnotationImplementation 
and 
http://errorprone.info/bugpattern/DefaultCharset
are 404s

**Comment by nglorioso** [comment]
Thanks for the report! It looks like I missed a few things while trying to rejigger the documentation generation in c2747d07c35bdd937ea43b693ab9344efa05c5cb

This is fixed at origin/master now (b5c1cd195e8633443cb94ec0838676a22598a123).
