### ISSUE TITLE
error-prone build failure on Windows/Appveyor

### ISSUE THREAD

**Issue by abbccdda** [google/error-prone#467]
Hey there,
I freshly checked out code, and tried to build it in Appveyor, but failed with this log:
https://ci.appveyor.com/project/abbccdda/error-prone/build/1.0.6

I used a Win10 virtual machine to build it, but failed with different error:
![image](https://cloud.githubusercontent.com/assets/5845561/19252224/8c16d78e-8ef8-11e6-86d8-134ca4da5d67.png)

I'm not sure you guys are aware of any build failure on Windows, if you know about this issue, could you point me to some solutions for this? Thanks a lot!

**Comment by eaftan** [comment]
Thanks for pointing this out. I set up an AppVeyor build last week, and @cushon fixed a bunch of platform-specific bugs.  We're now passing on Windows:
https://ci.appveyor.com/project/eaftan/error-prone-jbi6j/build/1.0.3
