### ISSUE TITLE
new errorprone's annotation CheckReturnValue for CheckReturnValue

### ISSUE THREAD

**Issue by romani** [google/error-prone#475]
reason is at - https://github.com/google/guava/issues/2629

rule - http://errorprone.info/bugpattern/CheckReturnValue

Guava team want to use errorprone, so it should to use annotations that errorprone understand for both - triggering validation and suppression.
In other case there is conflict with other tools - IntelijIdea inspections.

Or may be you be able to persuade to use guava team jdk standard ways to suppress validation that will help us to file issue on IntelijIdea to respect SuppressWarning annotation. I doubt that IntelijIdea will agree on new dependency to errorprone's annotation.

**Comment by cpovirk** [comment]
Update from the Guava bug: IntelliJ will be supporting `@CanIgnoreReturnValue`: https://youtrack.jetbrains.com/issue/IDEA-158576

(I'm also unsure whether a custom Error Prone annotation named `@CheckReturnValue` would be ignored by IntelliJ. If we do want to do anything like that, we should see.)
