### ISSUE TITLE
recognize java.time types as immutable

### ISSUE THREAD

**Issue by michaelhixson** [google/error-prone#477]
I see you have a [whitelist](https://github.com/google/error-prone/blob/b47de27e8e9d577d498ca1366dd1eb62d83752ef/core/src/main/java/com/google/errorprone/bugpatterns/threadsafety/WellKnownMutability.java) for known-immutable types recognized by the `@Immutable` annotation / bug pattern.  Would you consider adding the immutable `java.time` types to that list?

I have lots of types that should be `@Immutable`, but maybe half of them have a `LocalDateTime` or something similar that trips up error prone.  I could add a bunch of `@SuppressWarnings` but it would be cool if I didn't have to.

**Comment by cushon** [comment]
> Would you consider adding the immutable java.time types to that list?

Definitely. Any interest in putting together a PR?

**Comment by michaelhixson** [comment]
Will do.
