### ISSUE TITLE
Should `FilesLinesLeak` warn about streams returned from a method?

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#489]
Just gave the new `FilesLinesLeak` bug pattern a spin. It triggered one warning in our code base. The following code is an abstraction of the logic that triggered the issue:
```java
public final class Dummy {
    public void performOperationA(final Path source) throws IOException {
        try (final Stream<Item> items = getItemStream(source)) {
            // Do something interesting with the items.
            items.forEach(System.out::println);
        } catch (final UncheckedIOException e) {
            throw e.getCause();
        }
    }

    private Stream<Item> getItemStream(final Path source) throws IOException {
        return Files.lines(source, StandardCharsets.UTF_8).map(Item::new);
        // ^ This line triggers the warning.
    }

    private static final class Item {
        private final String data;

        Item(final String data) {
            this.data = data;
        }
    }
}
```

(Imagine that we have several `#performOperationX` methods, and that `#getItemStream` does something slightly more complex. Also imagine that some of the `#performOperationX` methods are `void` while others aren't, so moving their logic into a closure passed onto `#getItemStream` isn't very elegant either. The point being: assume it makes sense to define a method which returns the `Stream` produced by `Files.lines` without closing it.)

I think this case is quite similar to the definition of a method which returns an `(Auto)Closeable`. So I was wondering whether perhaps `FilesLinesLeak` shouldn't warn about this scenario. (If Error Prone could do complete flow analysis I suppose it could add a warning at transitive call sites, if applicable, but that seems to much to ask.)

On the other hand: users are in general probably not used to closing `Stream`s, so perhaps the false-positive is a reasonable trade-off given that it can be suppressed with `@SuppressWarnings("FilesLinesLeak")`.  So... WDYT?

**Comment by cushon** [comment]
How about requiring the method to be annotated with [`@MustBeClosed`](https://github.com/google/error-prone/blob/d82da813306b03925ba09dc2f8766408e98c06d9/annotations/src/main/java/com/google/errorprone/annotations/MustBeClosed.java#L37)?

The enforcement for `@MustBeClosed` doesn't actually handle returning the result of one annotated method from anther one yet, but that's going to be fixed soon.

**Comment by Stephan202** [comment]
I see `@MustBeClosed` was introduced "just now". Cool :). Yes, requiring that the `Stream` is either closed or is returned with an `@MustBeClosed` annotation would do the trick :+1:.

(One use case not yet covered then is when one creates the `Stream` and passes it onto another method which will close it, but that seems like a very rare use case. I don't recall seeing that pattern. And unless the invoked method performs the stream processing asynchronously, it's better to close the stream in an outer scope with `try-with-resources` anyway.)

A bit offtopic: How advanced do you plan to make the flow analysis for `@MustBeClosed` and similar features eventually? I mean, looking at the Checker Framework, this is a decidedly nontrivial task. Also, do you plan to support/enforce `javax.annotation.WillClose`? That would be a generalization over requiring that a `@MustBeClosed` resource is declared using `try-with-resources`.

**Comment by eaftan** [comment]
@Stephan202 We agree that solving this generally is nontrivial, and I'm not sure how far we want to go with it.  For now we're forcing people to use try-with-resources, but the naming gives us flexibility to implement something fancier if needed.  We're trying this internally and will see how much pushback we get.
