### ISSUE TITLE
Code compiled with error-prone 2.0.15 is compiled against Guava 20

### ISSUE THREAD

**Issue by pstibrany** [google/error-prone#492]
We have code which is using older version of Guava library (17). We use error-prone to compile it. Since updating to error-prone 2.0.15, we are running into this exception: java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator; 

It turns out that this method has been added in Guava 20: https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Sets.java#L667 (`iterator` method has been there before but has been inherited from super-class, with different return type)

While our project doesn't use Guava 20, latest error-prone does, which leads us to believe that our code has been compiled against this version. :-(

Expected: compile against jar files provided in our code, not against internal error-prone dependency.

**Comment by cushon** [comment]
Are you seeing the crash in Error Prone, or when you run code that was compiled by Error Prone?

And do you have a repro?

**Comment by pstibrany** [comment]
I see the crash in the code compiled by error-prone, when running it with old Guava on the classpath. This very same code with same guava jar works fine when compiled with error-prone 2.0.14. I will try to make a small self-contained example tomorrow if needed. 

-peter

**Comment by cushon** [comment]
Which build system are you using?

**Comment by pstibrany** [comment]
Ant, and error-prone javac task for ant.

**Comment by pstibrany** [comment]
I've created small test case in https://github.com/pstibrany/error-prone-issue-492.git

**Comment by martinlechner1** [comment]
I can confirm this issue with gradle.

**Comment by spodkowinski** [comment]
Version 2.0.15 will cause some guava related type interference errors when to project is compiled with a older guava version. Switching to 2.0.14 will solve most of them, but the created bytecode differs from artifacts compiled without the ant adapter.

**Comment by tbroyer** [comment]
Is this a dupe of #482 ?

**Comment by cushon** [comment]
I think so.
