### ISSUE TITLE
Feature Request: Skip certain files

### ISSUE THREAD

**Issue by vanniktech** [google/error-prone#511]
There are some auto generated files that should not be processed by Error Prone. So far I haven't found a way to tell Error Prone that. So it would be nice to be able to do that.

One example is the `R` class in android.

**Comment by vanniktech** [comment]
Closing in favor of #648 which has more information and ideas.

**Comment by mernst** [comment]
For others who stumble across this feature request, Error Prone now has a [`-XepExcludedPaths` command-line flag](https://errorprone.info/docs/flags).
