### ISSUE TITLE
InvalidPathException due to colon using the XepPatchLocation option on Windows

### ISSUE THREAD

**Issue by garyhodgson** [google/error-prone#514]
Hi.  I was attempting to use XepPatchLocation option as given in the [maven example](https://github.com/google/error-prone/blob/master/examples/maven/pom.xml#L71) and ran against the following Exception, seemingly due to the colons in Windows paths:

```
java.util.concurrent.ExecutionException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /T:/workspace/....
```

(error_prone_core version 2.0.16-SNAPSHOT)

**Comment by eaftan** [comment]
@nglorioso can take a look at this next week when he's back from vacation.

**Comment by tonylai16** [comment]
Not sure if this has been fixed or not but I found It is related to this [question](http://stackoverflow.com/questions/9834776/java-nio-file-path-issue).
After removing the leading slash, the patch file has successfully been created in windows 7.

**Comment by garyhodgson** [comment]
So I took a look at the code and as @tonylai16 rightly suggests the cause of the problem is the sourcePath URI being interpreted with a leading slash in the constructor of [DescriptionBasedDiff](https://github.com/google/error-prone/blob/0a471cdbb117f9ff0d8aea7ddbc3bfef272fbe3d/check_api/src/main/java/com/google/errorprone/apply/DescriptionBasedDiff.java#L59)

I tried to Do The Right Thing&trade; as per this [StackOverflow answer](http://stackoverflow.com/a/17870390) by using the following code: 

    this.sourcePath = Paths.get(compilationUnit.getSourceFile().toUri()).toFile().getAbsolutePath();

But this doesn't handle relative paths.  Attempting to add logic to handle this...
  
    this.sourcePath = (sourceFileUri.isAbsolute())? Paths.get(sourceFileUri).toFile().getAbsolutePath() : sourceFileUri.getPath();

only resulted in more failing unit tests due to jimfs not supporting the `toFile` method.

In the end I reverted to my original hacky way of doing it:

    this.sourcePath = compilationUnit.getSourceFile().toUri().getPath().replaceFirst("^/(.:/)", "$1");


I'll happily submit a pull request if you're happy with accepting such a hacky way of doing it.

**Comment by eaftan** [comment]
@nglorioso Can you PTAL?

**Comment by garyhodgson** [comment]
Is there any news on this issue?  Currently I have to manually patch each release of error-prone with the quick fix outlined above.  I'm guessing this feature is not often used/tested on a windows machine?

**Comment by Bananeweizen** [comment]
@garyhodgson I suggest to submit a PR with the change. I'm very interested in that fix myself as a Windows user, and I guess PRs get a bit more attention that "just issues". :)

**Comment by eaftan** [comment]
Yes, please send a PR.  To be perfectly honest, none of the us develop on Windows so we do make mistakes with Windows support sometime.

**Comment by cushon** [comment]
@garyhodgson did you try `.toAbsolutePath().toString()` instead of `.toFile().getAbsolutePath()`? It shouldn't be necessary to convert to a `File` to get the absolute path as a string, and that would work with non-default filesystems (e.g. JimFS).

**Comment by garyhodgson** [comment]
Thanks @cushon, your suggestion does indeed work and the resulting code is less hacky.  I'll resubmit the PR.
