### ISSUE TITLE
Significant compile-time regression vs. 2.0.15

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#522]
We are observing a significant (~2X) compile-time regression using the latest Error Prone from git master vs. 2.0.15.  We strongly suspect that the updated version of `javac` (`9-dev-r3297-1` vs. `1.9.0-dev-r2973-2`) is the cause of the problem.  Unfortunately I don't have a small test case I can share at this point to make it easy to reproduce (working on it).  Posting this issue in case anyone else has noticed this regression and has a workaround, a pointer to an upstream JDK 9 issue, etc.

**Comment by cushon** [comment]
It might be [JDK-8171294](https://bugs.openjdk.java.net/browse/JDK-8171294). Do the affected compilations have long classpaths?

**Comment by msridhar** [comment]
Yes, the classpath can be quite long!  Looks like the issue arose recently too.  Is there a plan to pull the fix for this issue into error-prone-javac?

**Comment by cushon** [comment]
Yes, I'll backport the fix into the next release.

**Comment by msridhar** [comment]
Wonderful, thanks!

**Comment by kageiit** [comment]
Can we get a fix for #375 as part of the next release as well? :)

**Comment by msridhar** [comment]
For some additional context here, we are running Error Prone 2.0.15, but we had to pull in the more recent javac (to get the fix for [JDK-8059976](https://bugs.openjdk.java.net/browse/JDK-8059976)) and then patch it to address #375.  Now, we are stuck with the compile time regression described here, and we can't go back to the previous javac as we need the aformentioned fixes.  So, when this fix gets backported, it'll make a big difference for our build times.

Just so we can get an idea, is there a rough ETA on when this fix might get backported?  Thanks!

**Comment by cushon** [comment]
I backported the fix, and am working on a release: google/error-prone-javac@3c696b83205bf0f95ebf0402f394076bd27386e1

**Comment by msridhar** [comment]
Thanks so much!  We'll be testing the new release as soon as it's available.

**Comment by cushon** [comment]
@msridhar - the latest snapshot includes the fix: https://oss.sonatype.org/content/repositories/snapshots/com/google/errorprone/error_prone_ant/2.0.16-SNAPSHOT/

**Comment by msridhar** [comment]
We tested the snapshot build and we are seeing some good performance improvements.  (We still have some additional slowness inside Dagger, compared to running on 2.0.15.  Not exactly sure why, but Dagger pulls in google-java-format, which in turn pulls in the version of error-prone-javac with the performance issue, so that might be the cause.)  Thanks again!

**Comment by kageiit** [comment]
Seems like a bunch of google tools like google-java-format and dagger transitively depend on the old jar with the slow compilation problem i.e javac-9-dev-r3297-1-shaded.

It would be great to get those updated to javac-9-dev-r3297-2-shaded once its released

**Comment by cushon** [comment]
@msridhar thanks for confirming! I'll get the release started.

@kageiit `google-java-format` only depends on javac for parsing, it doesn't do any compilation. It shouldn't by affected by this.

**Comment by cushon** [comment]
The fix has been released in 2.0.16.
