### ISSUE TITLE
Feature request: add support for passing command-line arguments to BugCheckers

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#524]
I've been working on a plugin check for Error Prone, implemented as described here:

http://errorprone.info/docs/plugins

For my checker, it would be great if I could pass in configuration flags via the command line.  I can work pass flags using JVM system properties or `-XD`, but those options are a bit hackish.  An officially sanctioned way to pass flags to a checker would be great.

**Comment by msridhar** [comment]
Note that as part of this feature we may need a new way to initialize checkers.  I think right now plugin checkers are created via a zero-argument constructor.

**Comment by cushon** [comment]
previously: https://groups.google.com/d/topic/error-prone-discuss/aDsIo2LEhr8/discussion

@eaftan pointed out in the thread that this would help with #512.

**Comment by epmjohnston** [comment]
New Error Prone command line args are in the latest snapshot and ready to use! Check out the documentation at http://errorprone.info/docs/flags

**Comment by msridhar** [comment]
Thanks @epmjohnston!  We'll be trying these soon.
