### ISSUE TITLE
Will the Patching option be available on plugin checks?

### ISSUE THREAD

**Issue by tonymlai** [google/error-prone#526]
I realize the patching option is only available on refaster refactorer and builtin checks currently
while plugin checks have no patching option. ([BaseErrorProneCompiler](https://github.com/google/error-prone/blob/600e6d6777474d7b88f3e05c3398719f1655e31c/check_api/src/main/java/com/google/errorprone/BaseErrorProneCompiler.java)Line212 no RefactoringCollection involved)
Will the patching option be available for plugin checks in the future?
Thanks!

**Comment by Stephan202** [comment]
@tonymlai, things might have changed in the past year, but I can confirm that Error Prone currently does support patching using custom plugins :). Just specify `-XepPatchChecks:YourCheckerName`.

**Comment by eaftan** [comment]
Yes, this was a duplicate issue of #609, which was fixed.  Sorry for not catching this.
