### ISSUE TITLE
Regression in annotation processor performance due to JDK-8153229

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#529]
This relates to the performance regression observed in #522.  We saw some good performance improvement due to getting the fix for  [JDK-8171294](https://bugs.openjdk.java.net/browse/JDK-8171294) but still see a significant regression in compile time on Error Prone 2.0.16 as compared to Error Prone 2.0.15.  Digging more, it seems like the underlying problem is [JDK-8153229](https://bugs.openjdk.java.net/browse/JDK-8153229), which gets exposed by heavy annotation processor use.  The issue has been fixed upstream; see google/error-prone-javac@d025db9b1da41b8236fa9bdbaff2eb135f37076c.

When possible, could this commit be backported to error-prone-javac?  My apologies for not finding this issue before the 2.0.16 release; I had assumed that the fix for [JDK-8171294](https://bugs.openjdk.java.net/browse/JDK-8171294) would solve our problems.

**Comment by cushon** [comment]
Sure, thanks for doing the investigation.

Can you verify that the backport for JDK-8153229 is sufficient? Here's an archive containing an `error-prone-javac` that includes the fix, and a snapshot build of Error Prone based on that javac: https://github.com/google/error-prone/files/778933/i529.zip

**Comment by msridhar** [comment]
I will try to verify the fix tonight and report back.

**Comment by msridhar** [comment]
Verified!  This fix reduces an annotation-processor-heavy build time from ~50s to ~23s, which is roughly the build time we were seeing before with Error Prone 2.0.15.  (It was up to ~80s before the fix for #522.)

**Comment by kageiit** [comment]
Seems like 2.0.16 did not make it into maven central yet. https://mvnrepository.com/artifact/com.google.errorprone/error_prone_ant

Maybe the fix can be part of 2.0.16 upon release?

**Comment by JakeWharton** [comment]
It's already there http://search.maven.org/#search%7Cga%7C1%7Cerror_prone_ant

mvnrepository.com is some third-party, super slow website. Don't use it.

**Comment by cushon** [comment]
I cut a javac release with the fix, and will push another error prone release soon.

**Comment by davido** [comment]
@cushon Thanks. We are waiting to include native EP support in buck build tool: [1]. EP documentation should be extended to reflect Buck native support.

* [1] https://github.com/facebook/buck/pull/1047

**Comment by cushon** [comment]
@davido thanks, I'd be happy to take a PR to update the docs once that lands.
