### ISSUE TITLE
`MissingDefault` vs `UnnecessaryDefaultInEnumSwitch`

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#545]
The error message for [`MissingDefault`](http://errorprone.info/bugpattern/MissingDefault) reads:

>  The Google Java Style Guide requires each switch statement includes a default statement group, even if it contains no code.

The linked-to [Google Java Style Guide §4.8.4.3](https://google.github.io/styleguide/javaguide.html#s4.8.4-switch) has similar terminology. But with the introduction of [`UnnecessaryDefaultInEnumSwitch`](http://errorprone.info/bugpattern/UnnecessaryDefaultInEnumSwitch) the default statement may be omitted for enum switches which enumerate all elements.

So I suppose the documentation and error message for `MissingDefault` should be updated to refer to _non-exhaustive_ switch statements. If the reference to the Google Java Style Guide is to be retained, then that document should be updated too. If desired I'll also file a ticket with [google/styleguide](https://github.com/google/styleguide/), but would like to hear the view of the Error Prone team first.

**Comment by cushon** [comment]
The external version of the style guide is slightly out of date. §4.8.4.3 has been updated to make an exception for exhaustive enum switches.

I pushed the latest version of the Error Prone docs, which clarify that MissingDefault and MissingCasesInEnumSwitch don't require exhaustive enum switches to have a default.
