### ISSUE TITLE
Raw Class is considered mutable?

### ISSUE THREAD

**Issue by hzsweers** [google/error-prone#549]
I have a final `Class` instance field in an enum, and found that error-prone does not consider it Immutable. I can't quite wrap my head around as to why though, as I don't see any mutative APIs.

**Comment by cushon** [comment]
The check does consider `Class<T>` to be immutable:

```
enum E {
  ;
  final Class<?> clazz = E.class;
}
```

do you have a repro?

**Comment by hzsweers** [comment]
Ahh interesting, I've found it. This is the repro case

```java
enum E {
  ;
  final Class clazz = E.class;
}
```

Remove the wildcard
