### ISSUE TITLE
Remove alternate name of Immutable for ImmutableEnumChecker

### ISSUE THREAD

**Issue by paulduffin** [google/error-prone#554]
Setting -Xep:Immutable:<level> affects both the Immutable and ImmutableEnumChecker because the latter has an alternate name of Immutable. That was very confusing. While I understand the necessity for maintaining compatibility of old names across a couple of releases it would be helpful if they were cleaned up quite quickly.

Maybe you could mark them as deprecated in some way so that using them would cause a warning to be logged and then remove the old name after a couple of releases.

**Comment by eaftan** [comment]
In this case, I think this was an accidental collision of names.  Previously, we required command-line options to use the canonical name of the check, but we allowed @SuppressWarnings to use altnames as well.  In 431e2782ea0fe11ba76c8eb1306c6564ffb3ba37 we changed the command-line flag behavior to accept altnames as well, to help with the GuardedBy cleanup and make it consistent with the @SuppressWarnings behavior.

I think we should go back to the old behavior of only accepting canonical names.  I'll take a look and see how much pain this causes internally.

**Comment by paulduffin** [comment]
Why can't you just remove the clashing altname?

**Comment by eaftan** [comment]
The altname is also used for @SuppressWarnings.  We did intend for @SuppressWarnings("Immutable") to suppress ImmutableEnumChecker.  I also think it's surprising that you can suppress from the command line by altname, and I took this as an opportunity to clean that up.
