### ISSUE TITLE
Provide a javac compatible script for running Error Prone

### ISSUE THREAD

**Issue by paulduffin** [google/error-prone#557]
While there seems to be good support for switching the java compiler over to use Error Prone in say Maven or Gradle there is nothing similar for replacing direct calls to javac. This is helpful for general scripts as well as say Makefile based builds such as that for Android.

Part of the problem with switching from javac to Error Prone is that javac has two groups of options, those that are meant for the runtime (prefixed with -J) and those meant for javac itself. Trying to run Error Prone directly using java means that the options have to be separated out, those that start with -J need to have the -J removed and be before the class on the command line so it is passed to java and the rest need to be after the class on the command line.

e.g.
   javac <compiler options> -J-Xmx1024M <more compiler options>
needs to be replaced with:
  java -Xmx1024M --classpath ... com.google.errorprone.ErrorProneCompiler <compiler options> <more compiler options>

An error-prone-javac script could handle all that automatically.

**Comment by cushon** [comment]
There's some half-hearted documentation here: http://errorprone.info/docs/installation#command-line

Do you have any suggestions for how to do this in a way that is portable?

**Comment by paulduffin** [comment]
I was thinking something bash based would be useful for Android development
as it uses Makefiles and does not need to work on Windows.

**Comment by cushon** [comment]
The newer `-Xplugin`-based command line usage instructions are fairly portable, and that's what the android build is currently using: https://android.googlesource.com/platform/build/soong/+/master/java/java.go#913
