### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by mattnelson** [google/error-prone#560]
The last set of release notes was for 2.0.15[1]. Have they moved to another location or has the process[2] been changed?

[1] https://groups.google.com/forum/#!topic/error-prone-announce/JoWOs_OCwIQ
[2] https://github.com/google/error-prone/wiki/Releasing#tell-the-world

**Comment by cushon** [comment]
Same location and process, the process just wasn't followed very carefully. I'll mail release notes for 2.0.16-2.0.18 soon.

**Comment by cushon** [comment]
https://groups.google.com/d/topic/error-prone-discuss/2OChjKCBq6o/discussion
