### ISSUE TITLE
test_helpers depends on SNAPSHOT build of junit

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#570]
The test_helpers module [depends on](https://github.com/google/error-prone/blob/650d0ee558b277497b60890fa8425d723ed8c1f6/test_helpers/pom.xml#L89) the `4.13-SNAPSHOT` version of junit.  For us this causes instability in our build system, as `SNAPSHOT` builds can get updated unpredictably.  Is there a strong need to depend on the snapshot build?  (Looks like junit 4 hasn't had a release in a while, so there may well be.)  If not, maybe this dependence can be changed to a release build?

**Comment by nglorioso** [comment]
We are using 4.13-SNAPSHOT in our tests for JUnit4's assertThrows/expectThrows. That version is used elsewhere in the errorprone project.

Out of curiosity, are you depending on test_helpers in non-test code? Is this blocking release builds for you?

**Comment by cushon** [comment]
Are you depending on `test_helpers` to test custom checks?

`assertThrows`/`expectThrows` are only used by tests in `core` and `check_api`, and not in `test_helpers`, so depending on `4.12` should be OK.

**Comment by kageiit** [comment]
@nglorioso we use the [buck](https://github.com/facebook/buck) build system with [okbuck](https://github.com/uber/okbuck). okbuck pulls in the greatest version of any dependency for usage in the buck files. This means whenever the snapshot changes, the jar changes and leads to a cache invalidation of all test rules.

Regardless of whether it is production/test code, it is very dangerous to depend on a snapshot for a hermetic build standpoint. The same VCS tag when built on two times can have a different result (if there are bugs in the snapshot jar for example) and is definitely not ideal.
