### ISSUE TITLE
Open-source enforcement for `@DoNotMock`

### ISSUE THREAD

**Issue by cushon** [google/error-prone#572]
see: https://groups.google.com/d/topic/error-prone-discuss/ZlqF85kcB_w/discussion

This probably needs a customizable whitelisting mechanism to be useful, similar to #512.

**Comment by kageiit** [comment]
Any update on this? Really excited to be able to start using this :)

**Comment by msridhar** [comment]
A ping on this one; it keeps coming up for us.  I think the whitelisting could be achieved via the new command-line arguments functionality?

**Comment by amalloy** [comment]
This was done in db307bcc71c80f79ee83227fa180cbf1a5d04380. Sorry it didn't occur to me to close this issue at the time.
