### ISSUE TITLE
intellij error-prone plugin is out of date

### ISSUE THREAD

**Issue by bramp** [google/error-prone#577]
The last release of the Intellij error-prone plugin was 28.06.2016 and is missing many of the checks that the latest version from Maven has.

**Comment by greggdonovan** [comment]
Synchronizing the IntelliJ updates with the normal error-prone releases would be really nice, if possible.

**Comment by cushon** [comment]
We don't maintain the IntelliJ plugin, but it is has been receiving regular updates lately: https://plugins.jetbrains.com/plugin/7349-error-prone-compiler/versions
