### ISSUE TITLE
Lower severity of LiteralClassName to SUGGESTION

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/error-prone#579]
Consider the following pattern:
```
Class<?> clz = null;
try {
  clz = Class.forName("SomethingOptional");
} catch (ClassNotFoundException e) {
  // log that the class was not found
}
```
ErrorProne would flag that this should be warned about, even though it may depend on runtime dependencies.  There aren't any [examples of this being dangerous](http://errorprone.info/bugpattern/LiteralClassName) and hardly any explanation as to how this could lead to an error happening.

Can this be lowered in severity?

**Comment by lowasser** [comment]
I'm under the impression EP only complains about this if the class is literally on the classpath already at compile time?

**Comment by carl-mastrangelo** [comment]
In our code, we selectively try and load a class, falling back to a safe default if it isn't present.  We don't know if it is or is not on the classpath from the code; that's that we are trying to find out.  Even if it is present at compile time, not everyone may run with our dependencies.  The code in question is specific to Linux, but our library needs to be buildable / useable on windows.  Whether or not the class is present on the classpath at compile time isn't relevant, since we don't know what classpath other people are going to use.

**Comment by cushon** [comment]
If it's available at compile-time, you may as well use the class literal. You'll get the same `NoClassDefFoundError` if it isn't on the runtime classpath.

And making the check a suggestion sounds reasonable, since it isn't a correctness issue.
