### ISSUE TITLE
Cannot enable a plugin check when passing -XepDisableAllChecks

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#591]
In some scenarios we'd like to be able to pass `-XepDisableAllChecks` and have our plugin checks (passed on the processor path) still run.  There doesn't seem to be any way to do this now.  If I try something like `-XepDisableAllChecks -Xep:PluginCheck1:ERROR` then Error Prone fails saying "PluginCheck1 is not a valid checker name".  By default, the [relevant code](https://github.com/google/error-prone/blob/de639a1ef4d962b984741ed346f0519c85eb6122/check_api/src/main/java/com/google/errorprone/ErrorProneAnalyzer.java#L73) loads plugins before applying the options, so all plugin checks get disabled.  

Perhaps a better default would be to first apply the overrides and then load the plugin checks in `ErrorProneAnalyzer`?  I think plugin checks can be reasonably disabled by just removing the jars from the processor path.  Eventually, it would be nice to have `-XepDisableAllChecks -Xep:PluginCheck1:ERROR` also work for enabling individual plugin checks.

**Comment by eaftan** [comment]
@epmjohnston Can you PTAL?

**Comment by epmjohnston** [comment]
You *should* already be able to turn plugin checks on and off with `-Xep:CheckName:SEVERITY`. Could you please provide the `@Bugpattern` annotation for the plugin check you're using? Are you sure that the name you're passing in the argument is exactly the same?

**Comment by epmjohnston** [comment]
@msridhar Closing this now, but please reopen and send some more details if you're still having problems.

**Comment by msridhar** [comment]
@epmjohnston I think you're right and this is a problem on our end.  Sorry about that.  If I re-discover a problem I will post here.  Thanks!
