### ISSUE TITLE
Warn when throwing an exception without propagating the cause

### ISSUE THREAD

**Issue by gaul** [google/error-prone#597]
I have encountered several situations where libraries write code like:

```java
try {
    ...
} catch (IOException ioe) {
    throw new MyException();
}
```

without propagating `ioe` as the cause to the exception constructor.  This obscures the root cause.  Could error-prone detect these situations and flag an error?

**Comment by kevinb9n** [comment]
I think the deeper question is why our UnusedAnalyzer isn't part of EP.

**Comment by graememorgan** [comment]
Thanks for the suggestion @gaul. This is now implemented as UnusedException, which is not yet enabled by default.
