### ISSUE TITLE
error: An unhandled exception was thrown by the Error Prone static analysis plugin.

### ISSUE THREAD

**Issue by prajwal-y** [google/error-prone#600]
private final boolean success;
    [javac]                           ^
    [javac]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]   
    [javac]      error-prone version: 2.0.15
    [javac]      Stack Trace:
    [javac]      java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
    [javac]   	at com.google.errorprone.fixes.Replacement.create(Replacement.java:37)
    [javac]   	at com.google.errorprone.fixes.SuggestedFix$InsertionFix.getReplacement(SuggestedFix.java:330)
    [javac]   	at com.google.errorprone.fixes.SuggestedFix.getReplacements(SuggestedFix.java:91)
    [javac]   	at com.google.errorprone.fixes.AppliedFix$Applier.apply(AppliedFix.java:66)
    [javac]   	at com.google.errorprone.JavacErrorDescriptionListener.lambda$new$0(JavacErrorDescriptionListener.java:61)
    [javac]   	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    [javac]   	at java.util.Iterator.forEachRemaining(Iterator.java:116)
    [javac]   	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    [javac]   	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    [javac]   	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    [javac]   	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    [javac]   	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    [javac]   	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    [javac]   	at com.google.errorprone.JavacErrorDescriptionListener.onDescribed(JavacErrorDescriptionListener.java:75)
    [javac]   	at com.google.errorprone.VisitorState.reportMatch(VisitorState.java:159)
    [javac]   	at com.google.errorprone.scanner.Scanner.reportMatch(Scanner.java:160)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:937)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:144)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
    [javac]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
    [javac]   	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:635)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    [javac]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
    [javac]   	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
    [javac]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
    [javac]   	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:113)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1303)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1247)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:858)
    [javac]   	at com.sun.tools.javac.main.Main.compile(Main.java:253)
    [javac]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:214)
    [javac]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:106)
    [javac]   	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
    [javac]   	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:38)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:35)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter.execute(ErrorProneAntCompilerAdapter.java:71)
    [javac]   	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1395)
    [javac]   	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1121)
    [javac]   	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   	at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    [javac]   	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   	at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:402)
    [javac]   	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   	at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   	at org.apache.tools.ant.Target.execute(Target.java:435)
    [javac]   	at org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac]   	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    [javac]   	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    [javac]   	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    [javac]   	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    [javac]   	at org.apache.tools.ant.Main.runBuild(Main.java:857)
    [javac]   	at org.apache.tools.ant.Main.startAnt(Main.java:236)
    [javac]   	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
    [javac]   	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
    [javac] 1 error

**Comment by cushon** [comment]
> error-prone version: 2.0.15

That is an old release, can you try using a new version of Error Prone?

**Comment by cushon** [comment]
Please re-open if you're still seeing this issue with the latest release.
