### ISSUE TITLE
ErrorProneJavacPlugin does not seem to support refactoring

### ISSUE THREAD

**Issue by kageiit** [google/error-prone#609]
Looking at the implementation https://github.com/google/error-prone/blob/master/core/src/main/java/com/google/errorprone/ErrorProneJavacPlugin.java#L35

It seems like refactoring support is missing as done in https://github.com/google/error-prone/blob/master/check_api/src/main/java/com/google/errorprone/BaseErrorProneJavaCompiler.java#L98

The refactoring logic could potentially be moved into the analyzer and look for other task event types instead of skipping like https://github.com/google/error-prone/blob/master/check_api/src/main/java/com/google/errorprone/ErrorProneAnalyzer.java#L118

Or it could be a completely new task listener to perform the refactoring after compilation has completed

**Comment by cushon** [comment]
23aef7214362db03e1e08c8c9b8a2e206f959404 was half-baked, I'm still working on this.

**Comment by jbduncan** [comment]
Hmm, what does "refactoring" mean in this context? It's not really clear to me.

**Comment by cushon** [comment]
Things should be in better shape after 30b8fae682e2a43866e3265b2b0b738b72651b8e.

@jbduncan http://errorprone.info/docs/patching

**Comment by jbduncan** [comment]
Thanks @cushon! :+1:
