### ISSUE TITLE
Warn if a newer version of error-prone is available

### ISSUE THREAD

**Issue by cushon** [google/error-prone#61]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=61) created by **aeagle22206** on 2012-11-29 at 08:42 PM_

---

With both ant and Maven, users will generally pick the current version when they add error-prone to their build, and will never know that a newer version is available.
(Unlike with libraries, they'll never lack a new feature which prompts them to upgrade; they just silently miss out on new checks)
We should figure out some way to get our new releases deployed out to users.

**Comment by eaftan** [comment]
We can't think of a way to do this without phoning home, and we don't think users would want their compiler doing that  Also, in the external world I assume people are used to having to manually update their dependencies.  We're going to pass on this for now.
