### ISSUE TITLE
Bug pattern suggestion: flag implicit long -> float casts

### ISSUE THREAD

**Issue by pstibrany** [google/error-prone#618]
I'd like to propose a new bug pattern, that tripped me recently.

When calling Math.round function with long value, Math.round(float) is called (and not Math.round(double) as I expected), which essentially cuts-off higher part of long value. There are more details here: http://stackoverflow.com/questions/1293819/why-does-java-implicitly-without-cast-convert-a-long-to-a-float

It would be great if error-prone could detect this implicit cast from long to float, and show an error.

**Comment by acr31** [comment]
Nice bug! We're going to have a look and see how often we can see this occurring.

**Comment by cushon** [comment]
This finally happened: https://github.com/google/error-prone/commit/8033bea6d7ef1a9d0fdc06def34d5d6a65ef508e
