### ISSUE TITLE
Export CompilationTestHelper for external developers to use in tests

### ISSUE THREAD

**Issue by cushon** [google/error-prone#62]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=62) created by **mdempsky@google.com** on 2012-11-30 at 11:46 PM_

---

CompilationTestHelper is nice for writing concise tests for custom checkers, and it's painful to write tests without it.  CompilationTestHelper and DiagnosticTestHelper should be made separately available for custom checkers to use in their own test suites.

However, this is slightly tricky to implement since error_prone_core's test code depend on the testhelpers, and the testhelpers depend on error_prone_core's main code and also junit/hamcrest.  They can't simply be moved into main because then error_prone_core's junit/hamcrest dependencies need to be promoted to standard dependencies rather than test dependencies.

I tried moving them into a separate error_prone_testhelpers module, but either Maven isn't smart enough to understand that error_prone_core:test -&gt; error_prone_testhelpers:main -&gt; error_prone_core:main isn't a dependency cycle or I'm not writing the pom.xml correctly (which is also likely).

**Comment by cushon** [comment]
This should be part of #192

**Comment by tom-smalls** [comment]
As stated in #322 I've had some success with creating a test jar using the maven-jar-plugin. I'll hopefully post some working code later today.

**Comment by tom-smalls** [comment]
The commit demonstrates creating a jar that contains the test helpers used in error prone when writing tests for custom bug patterns. As mentioned in the other issue, I had to create two new methods for adding the test sources using the Path object as the other methods that tried to load them from resources just didn't work for us.

893ad13194a3ef96cbfad031a5924b39c3d119f0

**Comment by cushon** [comment]
There's a separate `error_prone_test_helpers` artifact now.
