### ISSUE TITLE
[Feature Request] - Support Groovy/Kotlin

### ISSUE THREAD

**Issue by jaredsburrows** [google/error-prone#623]
Can we add support for other JVM languages such as Groovy and Kotlin?

Related: https://github.com/tbroyer/gradle-errorprone-plugin/issues/41#issuecomment-299673777

**Comment by lowasser** [comment]
Error Prone really depends on being able to parse *Java source code.*  It depends almost entirely on looking at Java syntax trees, from Java source.  This seems like it'd have to be an entirely new project.

**Comment by jaredsburrows** [comment]
@lowasser Yes. I am just throwing this idea out there to see what the community thinks.

**Comment by kolotyluk** [comment]
I would really love to see error-prone for Kotlin as well. I am looking at using Kotlin/Spek for automated testing, so it would be nice to run error-prone on the test code before running the actual tests.

**Comment by kolotyluk** [comment]
Given that Google is using more Kotlin on Android, it seems like error-prone for Kotlin would be valuable there too...

**Comment by lowasser** [comment]
Google is building its static analysis for Java and Kotlin on [Android Lint](http://tools.android.com/tips/lint) (even for non-Android code).

**Comment by Ahmed-Abdelhak** [comment]
still no updates for kotlin support ?
