### ISSUE TITLE
Support Maven Toolchains

### ISSUE THREAD

**Issue by anthonyvdotbe** [google/error-prone#626]
[Maven Toolchains](http://maven.apache.org/guides/mini/guide-using-toolchains.html) allow to run Maven itself in a different JRE than the JDK that is used for compiling/testing/running the project. [JavacCompilerWithErrorProne](https://github.com/codehaus-plexus/plexus-compiler/blob/master/plexus-compilers/plexus-compiler-javac-errorprone/src/main/java/org/codehaus/plexus/compiler/javac/errorprone/JavacCompilerWithErrorProne.java) will need to be updated to pass the correct executable, but [ErrorProneCompiler](https://github.com/google/error-prone/blob/master/core/src/main/java/com/google/errorprone/ErrorProneCompiler.java) needs to provide support for that.

**Comment by cushon** [comment]
The recommended way to use Error Prone with maven is the `-Xplugin` integration documented at http://errorprone.info/docs/installation.
