### ISSUE TITLE
MissingFail not detecting test cases

### ISSUE THREAD

**Issue by NightlyNexus** [google/error-prone#627]
I have exactly this one test in a test class.
```java
public final class FooTest {
  @Test public void foo() {
    try {
      List<String> s = Collections.emptyList();
      s.add("");
    } catch (UnsupportedOperationException expected) {
      assertThat(expected).hasCauseThat().isNull();
    }
  }
}
```
Error Prone is not complaining about the missing `fail()` call.
When I annotate the class with `@RunWith(BlockJUnit4ClassRunner.class)`, Error Prone does correctly complain.
Error Prone 2.0.19 and Truth 0.32.

This seems like a bug in `MissingFail`'s detection.

**Comment by eaftan** [comment]
We require that the class be annotated with @RunWith to consider it a JUnit4 test, because of the way we run tests inside Google.  We could probably be more lenient and consider any class that does not extend TestCase but contains a JUnit4 annotation to be a JUnit4 test.

**Comment by NightlyNexus** [comment]
That lenience would be nice, as many, including myself, probably have hidden erroneous tests without the runwith annotation.

Thank you. I appreciate the consideration!
