### ISSUE TITLE
Should StaticOrDefaultInterfaceMethod be removed?

### ISSUE THREAD

**Issue by hzsweers** [google/error-prone#629]
With desugar being added to the toolchain, I think this check should be left to the android lint tools (unless error prone has a way of knowing if desugar is being used). Thoughts?

**Comment by eaftan** [comment]
We'll remove it once Desugar's default and static interface method support is released, a.k.a. not in a preview.  For now, if you're testing default and static interface method support, please disable the check with `-Xep:StaticOrDefaultInterfaceMethod:OFF`.

(Our team also works on Desugar.)

**Comment by dotdoom** [comment]
Looks like it's out of preview and released now (https://developer.android.com/studio/write/java8-support.html says `Default and static interface methods` Compatible minSdkVersion is "Any").

**Comment by hzsweers** [comment]
It might be worth keeping this as an optional check. Static and default methods cause a full recompilation when used as far as I understand

**Comment by eaftan** [comment]
I'm OK to keep it as an optional check, for people who don't use Desugar or decide not to use default and static interface methods for one reason or another.  Currently it is disabled, so you would only get it if you intentionally enable it.
