### ISSUE TITLE
NPE on 2.0.20 when checking BigInteger conversion

### ISSUE THREAD

**Issue by Leprechaunius** [google/error-prone#651]
I have run the 2.0.20 (snapshot, but built from the same commit as the release) on our corporate project and got the following error. The 2.0.19 errorprone runs fine on the project.
Unfortunately I can't provide a lot of details as this is a closed source and I would violate the NDA :( But, maybe someone can provide some insight, or maybe I will manage to create a reproducible example in the future.

The code snippet where the NPE is thrown :

>       Long id = null;
>       Object[] values = (Object[]) query.getSingleResult();
>       if (values[0] instanceof BigInteger) {
>         id = ((BigInteger) values[0]).longValue(); //line 168
>       } else if (values[0] instanceof Long) {
>         id = (Long) values[0];
>       }

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project product.aaa.impl: Compilation failure
> [ERROR] C:\prjs\product\product.base.plugin\product.base\product.aaa\product.aaa.impl\src\main\java\com\company\product\aaa\impl\business\service\UserServiceImpl.java:[168,15] An unhandled exception was thrown by the Error Prone static analysis plugin.
> [ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
> [ERROR]
> [ERROR]      error-prone version: 2.0.20-SNAPSHOT
> [ERROR]      Stack Trace:
> [ERROR]      java.lang.NullPointerException
> [ERROR]         at com.google.errorprone.bugpatterns.InstanceOfAndCastMatchWrongType$TreeScannerInstanceOfWrongType.visitInstanceOf(InstanceOfAndCastMatchWrongType.java:185)
> [ERROR]         at com.google.errorprone.bugpatterns.InstanceOfAndCastMatchWrongType$TreeScannerInstanceOfWrongType.visitInstanceOf(InstanceOfAndCastMatchWrongType.java:147)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCInstanceOf.accept(JCTree.java:2051)
> [ERROR]         at com.sun.source.util.TreeScanner.scan(TreeScanner.java:86)
> [ERROR]         at com.google.errorprone.bugpatterns.InstanceOfAndCastMatchWrongType$CastingMatcher.matches(InstanceOfAndCastMatchWrongType.java:103)
> [ERROR]         at com.google.errorprone.bugpatterns.InstanceOfAndCastMatchWrongType.matchTypeCast(InstanceOfAndCastMatchWrongType.java:68)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitTypeCast(ErrorProneScanner.java:1090)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitTypeCast(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:2022)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.visitParenthesized(TreeScanner.java:572)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitParenthesized(ErrorProneScanner.java:991)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitParenthesized(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1849)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.visitMemberSelect(TreeScanner.java:680)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:878)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2112)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
> [ERROR]         at com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:508)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:913)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1644)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
> [ERROR]         at com.sun.source.util.TreeScanner.visitAssignment(TreeScanner.java:585)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitAssignment(ErrorProneScanner.java:500)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitAssignment(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1878)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:433)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:713)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1454)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
> [ERROR]         at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
> [ERROR]         at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:419)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:758)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
> [ERROR]         at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
> [ERROR]         at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
> [ERROR]         at com.sun.source.util.TreeScanner.visitTry(TreeScanner.java:374)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitTry(ErrorProneScanner.java:1081)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitTry(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1322)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
> [ERROR]         at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
> [ERROR]         at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
> [ERROR]         at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:898)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
> [ERROR]         at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
> [ERROR]         at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:590)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
> [ERROR]         at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
> [ERROR]         at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
> [ERROR]         at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:605)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
> [ERROR]         at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
> [ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
> [ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
> [ERROR]         at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:41)
> [ERROR]         at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
> [ERROR]         at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
> [ERROR]         at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1425)
> [ERROR]         at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1374)
> [ERROR]         at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
> [ERROR]         at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
> [ERROR]         at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
> [ERROR]         at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
> [ERROR]         at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
> [ERROR]         at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:137)
> [ERROR]         at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
> [ERROR]         at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:118)
> [ERROR]         at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:222)
> [ERROR]         at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
> [ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
> [ERROR]         at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
> [ERROR]         at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)
> [ERROR]         at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)
> [ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
> [ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
> [ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
> [ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> [ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> [ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
> [ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
> [ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
> [ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
> [ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
> [ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
> [ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
> [ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> [ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> [ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> [ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

Built on Oracle JDK 1.8.0_102 x64, Maven 3.5.0

**Comment by eaftan** [comment]
Thanks for the bug report, I'll take a look.
