### ISSUE TITLE
(nitpick) '2.0.20' tag should be 'v2.0.20'?

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#652]
If you look at the git tags, nearly all release tags start with a 'v', e.g., 'v2.0.19'.  However, 2.0.20 got tagged just as '2.0.20'.  Just a minor nitpick, but fixing should be easy.

**Comment by eaftan** [comment]
Thanks for the catch, I just fixed this: https://github.com/google/error-prone/releases/tag/v2.0.20

**Comment by eaftan** [comment]
(Also fixed the other case where we forgot the 'v' prefix)
