### ISSUE TITLE
Check for empty classes.

### ISSUE THREAD

**Issue by NightlyNexus** [google/error-prone#654]
Empty classes that directly extend Object (like `class FooType {}` and `class BarType implements Runnable {}`) have no meaning.
I can't think of a use case for them. (Correct me if I'm wrong.)
They are stateless and should be represented as constant values.

It'd be cool if Error Prone could check for such misused types.

**Comment by lowasser** [comment]
I have totally used these a few times in ways I don't think could be done any other way.

The main one that comes to mind is that I was testing memory consumption of collection data structures.  So I had a `class Element {}` where I could produce as many as I'd like, they'd retain the default reference equality and hashCode implementation so they were all distinct, but I didn't want to include the memory overhead of the elements themselves in the total measurement, so the memory tester stopped walking the object tree if it found an `instanceof Element`.

**Comment by NightlyNexus** [comment]
That makes sense, yep. It'd be too much boilerplate at the least to do that otherwise.
Thanks, I'll remember that!
