### ISSUE TITLE
False positive CheckReturnValue method calling another CheckReturnValue method

### ISSUE THREAD

**Issue by vanniktech** [google/error-prone#661]
After updating to `2.0.20` I'm seeing this weird error that I believe to be a false positive.

```
error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
        return Observable.fromIterable(invitationModelList).subscribe(invitationModelItem -> resendSingleInvitation(invitationModelItem, callbackSuccess, callbackError, true), throwable -> CallbackUtil.checkAndCall(callbackError, new FamilonetException(throwable)), () -> CallbackUtil.checkAndCall(callbackSuccess));
                                                                                                                   ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean 'return Observable.fromIterable(invitationModelList).subscribe(, throwable -> CallbackUtil.checkAndCall(callbackError, new FamilonetException(throwable)), () -> CallbackUtil.checkAndCall(callbackSuccess));'?
```

This is the relevant java code:

```java
@Override @CheckReturnValue public Disposable resendAllInvitations List<InvitationModel> invitationModelList,
    @Nullable ICallback callbackSuccess, @Nullable ICallbackWithParam<FamilonetException> callbackError) {
  return Observable.fromIterable(invitationModelList)
      .subscribe(invitationModelItem -> resendSingleInvitation(invitationModelItem, callbackSuccess, callbackError, true),
          throwable -> CallbackUtil.checkAndCall(callbackError, new FamilonetException(throwable)),
          () -> CallbackUtil.checkAndCall(callbackSuccess));
}
```

The signature of `resendSingleInvitation` looks like this:

```java
@Override @CheckReturnValue public Disposable resendSingleInvitation(@NonNull InvitationModel invitationModel, @Nullable ICallback callbackSuccess, @Nullable ICallbackWithParam<FamilonetException> callbackError, boolean shouldSendSms) {
  // Some code.
}
```

From my perspective this looks good and should not raise any errors.

**Comment by lowasser** [comment]
What is `ICallback`?

**Comment by vanniktech** [comment]
```java
@FunctionalInterface
public interface ICallback {
  void call();
}
```

**Comment by lowasser** [comment]
This looks WAI, then.

The point of `@CheckReturnValue` is that something has to be done with the return value, but right now it's in a `void` method.  Error Prone would normally ban the single line

     resendSingleInvitation(...);

...because nothing is done with the `Disposable` return type; that's the point of `@CheckReturnValue`.

Just the same, it'd ban

    (arguments) -> {
      resendSingleInvitation(...);
    }

...because still, nothing is done with the `Disposable` return type.  And the above lambda, which will be banned, is equivalent to your single line lambda

    (arguments) -> resendSingleInvitation(...)

...because, again, nothing is done with the result.

**Comment by vanniktech** [comment]
Oh okay now I understand it. Thanks. I got confused by the suggestion that produces invalid code.

**Comment by lowasser** [comment]
It does like the suggested fix needs work for this case, though?

**Comment by vanniktech** [comment]
That's true yeah.

**Comment by vanniktech** [comment]
@lowasser has there been any effort in trying to make the suggested fix work?
