### ISSUE TITLE
Switch labels fall-through annotation

### ISSUE THREAD

**Issue by cushon** [google/error-prone#68]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=68) created by **supertri@google.com** on 2013-01-09 at 06:56 PM_

---

Clang now (or soon will) warns about potential bugs from fallthrough in switch statements. To tell Clang that the fallthrough is intended, you can use the 'FALLTHROUGH_INTENDED' annotation.

case A: // No annotation required
case B:
&nbsp;&nbsp;&nbsp;DoSomething();
&nbsp;&nbsp;&nbsp;---
case C:
&nbsp;&nbsp;&nbsp;DoSomething();
&nbsp;&nbsp;&nbsp;FALLTHROUGH_INTENDED;  // Annotation required
case D:
&nbsp;&nbsp;&nbsp;DoSomethingElse();

Perhaps we can do a similar thing for java (though figuring out how to specify the annotations is an issue).

**Comment by cushon** [comment]
Now that end positions are on by default this should be feasible.

**Comment by PhilippWendler** [comment]
If this gets added, please also recognize `//$FALL-THROUGH$`, which is what Eclipse uses.

**Comment by cushon** [comment]
Thanks, recognizing `//$FALL-THROUGH$` sounds good.

I belatedly remembered that there's another blocker for this. We need control flow information to detect fall-through, and javac doesn't expose it. We might be able to use the checker-framework's implementation, though.

**Comment by cushon** [comment]
This happened: http://errorprone.info/bugpattern/FallThrough

> We need control flow information

It turns out this only requires knowing whether or not the case definitely completes per [JLS 14.21](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.21), which is a significantly easier problem.
