### ISSUE TITLE
custom flag as compiler argument is not accessible from BugChecker

### ISSUE THREAD

**Issue by dganesh5** [google/error-prone#680]
tried passing additional key value pair to Custom BugChecker following the instructions from this doc : http://errorprone.info/docs/flags

Tried setting this in pom 

   ``     <compilerArgs>
        	 <arg>-XepOpt:mvnBuildDirectory=${project.build.directory}</arg>
        </compilerArgs>``

And access using below code in MyCustomChecker 
``public MyCustomChecker(ErrorProneFlags flags) {
	    this.pwd = flags.get("mvnBuildDirectory").toString(); 
	  }``

upon running this, I get an java.util.ServiceConfigurationError.
java.util.ServiceConfigurationError: com.google.errorprone.bugpatterns.BugChecker: Provider com.abc.errorprone.MyCustomChecker could not be instantiated

**Comment by nglorioso** [comment]
Ah, sorry about that!

Due to the requirements of ServiceLoader, the object must still have a no-arg constructor. However, if you have another constructor with ErrorProneFlags as a parameter, it will be picked up.

See #691
