### ISSUE TITLE
Nested indices warning

### ISSUE THREAD

**Issue by lshadler** [google/error-prone#688]
A simple parse command could detect if there is an overlap in nested for loop definitions like so:
```java
for(int i = 0; i < 10; ++i){
   for(int j = 0; i < 10; ++i){
        // do stuff
   }
}
```
Note the `i` declaration in the inner loop. Please let me know if this has been implemented already or will cross a different error. I would flag this as a warning, and if possible, would like to develop it if it would be useful.

Cheers!

**Comment by eaftan** [comment]
Thanks for the suggestion. This looks like http://errorprone.info/bugpattern/LoopConditionChecker.  You can see the test cases in https://github.com/google/error-prone/blob/28c7efa0bfd91bc6795e3ff240fb7a3d23c09752/core/src/test/java/com/google/errorprone/bugpatterns/LoopConditionCheckerTest.java.
