### ISSUE TITLE
Update Checker Framework dataflow dependency

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#696]
We are planning to open source one of our Error Prone plugin checks soon.  One remaining issue is that Error Prone depends on a very old version of the Checker Framework dataflow library (1.8.10, released 30-Jan-2015). Our plugin check cannot support Java 8 lambdas with this older version. 
 Also, the older version also has race conditions / memory leaks that can cause serious problems in build systems using a daemon process; see typetools/checker-framework#1108.

We have updated EP to use version 2.1.13 of the Checker Framework in an internal fork.  (The change is very straightforward; happy to put up a PR if it's helpful.)  I can confirm that the EP regression tests pass, and we haven't observed any problems over several weeks of usage.

Would it be possible to bump the Checker Framework dataflow dependency in the main EP repository soon?  Let me know if I can help in any way.  Thanks!

**Comment by jbduncan** [comment]
I'm not on the error-prone team (or a Googler for that matter), but seeing an open sourced Error Prone plugin check from people outside of Google sounds interesting to me, so I +1 this.

**Comment by msridhar** [comment]
Thanks @wmdietl and @cushon!  Would it be possible to tag a new EP release with this change soonish, so we can bump our dependence and test?

**Comment by cushon** [comment]
I'm working on another release, thanks for your patience.

**Comment by msridhar** [comment]
Fixed in 2.1.0
