### ISSUE TITLE
Let unused variable be an error

### ISSUE THREAD

**Issue by CecilWesterhof** [google/error-prone#701]
I think a good extension would be to let unused variables be an error.

**Comment by eaftan** [comment]
Having them as an error would block development when you are using Error Prone as your development compiler, as we do inside Google.  It would make a good warning though, and you could configure your CI to promote it to an error and block submit if you have an unused variable.

**Comment by agrieve** [comment]
How would it block development? Is there a scenario in which unused variables are ever desired?

**Comment by justinuang** [comment]
What is the recommended way to configure our CI? From what I can tell, there isn't a rule in error-prone or the default jdk compiler to detect it, and I want to avoid adding findbugs just for this.

**Comment by eaftan** [comment]
@agrieve It's pretty common to have unused variables while you are coding.  For example, you might comment out the only use of a variable while debugging.  I agree it would be useful in a CI or code review bot though.

@justinuang This isn't a rule in Error Prone, and we don't have plans to make it one.  The only suggestion I can make is to find some other tool that does it.  PMD does it and might be easier to integrate than Findbugs.

**Comment by graememorgan** [comment]
We now have support for Unused analysis in ErrorProne (under a bugpattern named Unused). It's disabled by default while we evaluate the performance cost of running it in ErrorProne, but you're welcome to enable it and give it a spin!
