### ISSUE TITLE
Is it possible to use error prone to nullness checking

### ISSUE THREAD

**Issue by m-titov** [google/error-prone#703]
Hi.
Since error prone based on checker framework is it possible to use org.checkerframework.checker.nullness.NullnessChecker or in some other way ckeck nullness and how?

**Comment by jbduncan** [comment]
@m-titov I could be wrong, but I don't believe that error-prone _is_ based on the Checker Framework. The error-prone team can likely clarify on this.

**Comment by eaftan** [comment]
@m-titov Error Prone is not based on the Checker Framework, though we do use its dataflow analysis framework.  We don't have a nullness checker and recommend the Checker Framework if you do need one.

**Comment by m-titov** [comment]
Ok. Thanks.
