### ISSUE TITLE
Refaster execution documentation outdated

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#713]
The post-v2.019 [command line usage instructions](http://errorprone.info/docs/installation#command-line) should also be ported to the [Refaster documentation](http://errorprone.info/docs/refaster#running-the-refaster-refactoring), for otherwise users will be met with the issue described in #653.

On JDK 8 I can get Refaster 2.1.0 to run using:
```sh
java -Xbootclasspath/p:error_prone_refaster-2.1.0.jar:javac-9-dev-r4023-3.jar com.google.errorprone.refaster.RefasterRuleCompiler ...
```

I can open a PR to update the documentation accordingly, but perhaps JDK 9 instructions should be added as well?

**Comment by eaftan** [comment]
We'd love it if you could send a PR.

**Comment by Stephan202** [comment]
So, it appears that http://errorprone.info/docs/refaster isn't generated from from the contents of this repository. Couldn't find another source either. Anyway, a minimal fix would be to change the first part of that section as follows:

<pre>
# Running the Refaster refactoring

TIP: These instructions are valid as of Error Prone 2.1.0, and are subject to change.

Use the Error Prone javac JAR and the Error Prone Refaster JAR to compile the Refaster template:

```sh
wget http://repo1.maven.org/maven2/com/google/errorprone/javac/9-dev-r4023-3/javac-9-dev-r4023-3.jar
wget http://repo1.maven.org/maven2/com/google/errorprone/error_prone_refaster/2.1.0/error_prone_refaster-2.1.0.jar

java -Xbootclasspath/p:error_prone_refaster-2.1.0.jar:javac-9-dev-r4023-3.jar \
  com.google.errorprone.refaster.RefasterRuleCompiler \
  StringIsEmpty.java --out `pwd`/myrule.refaster
```
</pre>

**Comment by msridhar** [comment]
You need to do a PR against the `gh-pages` branch.  E.g., see #691

**Comment by Stephan202** [comment]
Thanks @msridhar! Clearly Google didn't index that branch :). Will open a PR shortly.
