### ISSUE TITLE
error-prone doesn't follow relocated dependencies

### ISSUE THREAD

**Issue by madrob** [google/error-prone#716]
I'm working on integrating error-prone into the compile for Apache HBase, and we're running into a strange false positive, I think.

Steps to reproduce:
```
git clone https://github.com/apache/hbase
cd hbase
mvn clean package -PerrorProne
```

Output error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project hbase-common: Compilation failure
[ERROR] /Users/mdrob/IdeaProjects/hbase/hbase-common/src/main/java/org/apache/hadoop/hbase/io/crypto/Context.java:[89,31] [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
[ERROR]     (see http://errorprone.info/bugpattern/CheckReturnValue)
[ERROR]   Did you mean to remove this line?
```

That line is a call to a relocated Guava 22 `Preconditions.checkNotNull` which is annotated `@CanIgnoreReturnValue` - this can be verified in the [artifact](https://repo1.maven.org/maven2/org/apache/hbase/thirdparty/hbase-shaded-miscellaneous/1.0.0/hbase-shaded-miscellaneous-1.0.0.jar) (No source release available yet, unfortunately!)

There may be older versions of guava on the dependency classpath, but this class specifically uses `import org.apache.hadoop.hbase.shaded.com.google.common.base.Preconditions;`

I don't yet have a smaller reproducible case. Before I start down that path, do we think the problem is most likely in error-prone, the plexus compiler, our configuration of the plugins, a combination of these, or something else entirely?

**Comment by cushon** [comment]
It looks like the annotation was also shaded `org/apache/hadoop/hbase/shaded/com/google/errorprone/annotations/CanIgnoreReturnValue`.

The Error Prone check expects the unshaded `CanIgnoreReturnValue`, it doesn't recognize other annotations with that simple name.

**Comment by madrob** [comment]
Is it palatable to update the check based on simple name instead of fully qualified name? Not sure if this would cause other problems though.

I'll look at excluding the annotation from relocation as well.

**Comment by madrob** [comment]
There's already some work done to support simple name annotation for including which methods to check, just not excluding them. Adding them should hopefully be straightforward. See #435

**Comment by cushon** [comment]
Is not repackaging the annotation an option?

**Comment by madrob** [comment]
We were able to fix the issue the first time by not repackaging the annotation, but then ran into it again when we used a separate dependency that does it's own repacking. Theoretically, we could file an issue against that dependency to do the same thing we did and skip the repackaging, but it seems simpler to fix this in the core rather than asking everybody to work around the issue.
