### ISSUE TITLE
Building error_prone with Bazel

### ISSUE THREAD

**Issue by nicktrav** [google/error-prone#731]
It appears that even though `error-prone` is set up to build with Bazel (I see a WORKSPACE file in the top-level dir and some other BUILD files), it seems to be using a older API (or maybe this is a leftover from Blaze?).

Consider the following code:

```bash
$ bazel build //...
ERROR: /Users/nickt/Development/error-prone/WORKSPACE:1:1: //external:javac: no such attribute 'group_id' in 'maven_jar' rule.
ERROR: /Users/nickt/Development/error-prone/WORKSPACE:1:1: //external:javac: no such attribute 'artifact_id' in 'maven_jar' rule.
ERROR: /Users/nickt/Development/error-prone/WORKSPACE:1:1: //external:javac: no such attribute 'version' in 'maven_jar' rule.
ERROR: /Users/nickt/Development/error-prone/WORKSPACE:13:1: //external:guava: no such attribute 'group_id' in 'maven_jar' rule.
ERROR: /Users/nickt/Development/error-prone/WORKSPACE:13:1: //external:guava: no such attribute 'artifact_id' in 'maven_jar' rule.
ERROR: /Users/nickt/Development/error-prone/WORKSPACE:13:1: //external:guava: no such attribute 'version' in 'maven_jar' rule.
ERROR: /Users/nickt/Development/error-prone/WORKSPACE:25:1: //external:guava: no such attribute 'group_id' in 'maven_jar' rule.
... snip ...
```

The WORKSPACE dep issues are easily fixed by using the API mentioned [here](https://docs.bazel.build/versions/master/be/workspace.html#maven_jar), but this uncovers a bunch of other issues, namely that many of the targets are not specified in the existing BUILD files.

I encountered a number of other curly issues getting `check_api/` to build, namely the reliance on the java9 tools.jar and unreleased version of Junit that I couldn't find on Maven Central.

I have a fix for some of the packages that I'd be happy to share, but I'm not sure if there's a specific Bazel / Blaze style that should be adhered to (i.e. closely mirror the pom.xml files as much as possible), whether tests should be run from Bazel as part of CI, etc ...

Is it expected that `error-prone` _should_ be able to be built with Bazel?

Relevant Bazel information:

```bash
$ bazel version
Build label: 0.5.3-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Aug 6 12:54:10 2017 (1502024050)
Build timestamp: 1502024050
Build timestamp as int: 1502024050
```

**Comment by cushon** [comment]
> Is it expected that error-prone should be able to be built with Bazel?

Not currently. That `WORKSPACE` was an experiment, and it hasn't been updated in a long time so the syntax is out of sync with recent Bazel versions.

I think we'd like to migrate from maven to Bazel eventually (maintaining two build systems in parallel is less appealing), but we're waiting for bazelbuild/bazel#1372 to happen first.

**Comment by jbduncan** [comment]
@cushon It would probably also be worth waiting until Bazel runs sufficiently well on Windows, which may imply waiting for release 1.0 or 1.1 LTS. Otherwise, people who run Windows (myself included) will have troubles building error-prone, as Bazel currently has a lot of issues running on that OS.

**Comment by eaftan** [comment]
@jbduncan Good point about Bazel Windows support as well.
