### ISSUE TITLE
errorprone added to war, even if dependencies scoped are 'runtime'

### ISSUE THREAD

**Issue by roche2limit** [google/error-prone#739]
errorprone adds its libraries to war archive,
 even if dependencies scoped are 'runtime'.

Context with a profile:
        
        <profile>
                <id>errorprone</id>
                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <version>3.6.1</version>
                            <configuration>
                                <compilerId>javac-with-errorprone</compilerId>
                                <forceJavacCompilerUse>true</forceJavacCompilerUse>
                                
                                <source>7</source>
                                <target>7</target>
                                
                            </configuration>
                            <dependencies>
                                <dependency>
                                    <groupId>org.codehaus.plexus</groupId>
                                    <artifactId>plexus-compiler-javac-errorprone</artifactId>
                                    <version>2.8.2</version>
                                    <scope>runtime</scope>
                                </dependency>
                                
                                <dependency>
                                    <groupId>com.google.errorprone</groupId>
                                    <artifactId>error_prone_core</artifactId>
                                    <version>2.1.1</version>
                                    <scope>runtime</scope>
                                </dependency>
                            </dependencies>
                        </plugin>
                    </plugins>
                </build>
            </profile>

**Comment by Stephan202** [comment]
Can you add the relevant XML tags (maybe add triple backticks around the code snippet)? Right now it's unclear what your config looks like. (I assume `plexus-compiler-javac-errorprone` and `error_prone_core` are declared as _plugin_ dependencies, but not sure.)

**Comment by roche2limit** [comment]
Sorry current browser was a so old broken version.
 

        <profile>
                <id>errorprone</id>
                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-compiler-plugin</artifactId>
                            <version>3.7.0</version>
                            <configuration>
                                <compilerId>javac-with-errorprone</compilerId>
                                <forceJavacCompilerUse>true</forceJavacCompilerUse>
                                
                                <source>7</source>
                                <target>7</target>
                                
                            </configuration>
                            <dependencies>
                                <dependency>
                                    <groupId>org.codehaus.plexus</groupId>
                                    <artifactId>plexus-compiler-javac-errorprone</artifactId>
                                    <version>2.8.2</version>
                                    <scope>runtime</scope>
                                </dependency>
                                
                                <dependency>
                                    <groupId>com.google.errorprone</groupId>
                                    <artifactId>error_prone_core</artifactId>
                                    <version>2.1.1</version>
                                    <scope>runtime</scope>
                                </dependency>
                            </dependencies>
                        </plugin>
                    </plugins>
                </build>
            </profile>

**Comment by Stephan202** [comment]
Can you remove `<scope>runtime</scope>` and see whether that helps? Afaik the scope has no impact inside plugin dependency listings. (Since, after all, those dependencies only impact plugin execution; there is no other scope.)

I'd also recommend running `mvn dependency:tree` and checking whether Error Prone is listed. I suspect the dependencies end up in your WAR file some other way.

**Comment by roche2limit** [comment]
ok my fault, found the error (another dependencies declaration), tx.
