### ISSUE TITLE
Prevent foo=+bar

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#742]
Today I found a bug in our source code where a developer had written several statements that looked like the following:
```
foo =+ bar;
```
The intention of the code was `foo += bar;`.

Could a check for this be added to error-prone?
Equivalently, one could think about adding the same check for `=-`, though of course here exists the difficulty that this could be an intended case of assigning a negative value. Maybe make it dependent on whitespace, e.g., forbid `=-bar` and `=- bar` but allow `= -bar` (if error-prone's policy is that whitespace may be relevant for a check and it is technically possible).

**Comment by Stephan202** [comment]
Does Error-Prone actually have access to this information? I thought it hooks into the post-compilation phase. If so; what you're describing sounds like a nice addition for [Checkstyle](https://github.com/checkstyle/checkstyle/).

**Comment by nglorioso** [comment]
We can detect an assignment where the RHS is a unary `+`, then use the start position of that `+`, and scan backwards in the source looking for `=` in the previous position.  (see https://github.com/google/error-prone/blob/d41033b827bf4abd486d0d1af23a4814495fbb3f/core/src/main/java/com/google/errorprone/bugpatterns/FallThrough.java#L70 for where to start)

**Comment by msridhar** [comment]
For unary plus, it might be good to flag any case where the operand is of type `int`, in which case the operation does nothing as far as I understand (based on [this SO answer](https://stackoverflow.com/a/2624541/1126796)).  Could be a complementary check to syntactically searching for `=+`

**Comment by Stephan202** [comment]
Thanks @nglorioso, very helpful!

**Comment by eaftan** [comment]
We looked in our internal codebase and found *no* instances of this pattern.  We're not convinced this is worth the effort.

**Comment by cushon** [comment]
It's also less confusing if it's formatted as `foo = +bar;`. gcheckstyle can be configured to warn about that, and that's the formatting `google-java-format` will emit.
