### ISSUE TITLE
Is error prone multi threaded?

### ISSUE THREAD

**Issue by stephanenicolas** [google/error-prone#748]
Or maybe, is it even possible to compile concurrently a given source set ?

**Comment by lowasser** [comment]
Error Prone is built on top of javac, which is not a concurrent compiler.

**Comment by eaftan** [comment]
@lowasser  is right, javac is not multithreaded, so Error Prone is not either.  I did try multithreading Error Prone check execution at one point, but check execution can trigger symbol completion in javac, and symbol completion is not thread safe, so the whole thing came crashing down.

**Comment by stephanenicolas** [comment]
Thx for the answer guys. So, if my understanding is correct. Error prone delegates the actual compilation to javac ? (error-prone cannot generate a byte code that is different from javac?)

**Comment by eaftan** [comment]
It's true that we delegate to javac and so produce the same bytecode javac does, but there's some subtlety to it.  We repackage our own copy of javac that is pinned to a particular revision of the development version of javac (see https://github.com/google/error-prone/blob/master/pom.xml#L37).  That javac may produce different bytecode than whatever javac you have installed with your JDK.  For example, the javac we use emits improved bytecode for try-with-resources (https://bugs.openjdk.java.net/browse/JDK-7020499) which other tools may not have seen before, if they haven't tested with Java 9 yet.

**Comment by stephanenicolas** [comment]
Thx @eaftan !
