### ISSUE TITLE
Allow use in maven in combination with groovy compiler

### ISSUE THREAD

**Issue by J0s3f** [google/error-prone#749]
We recently started to write some new tests using Spock. This means, we had to change the compiler to the groovy-eclipse-compiler in the maven pom.xml
It seems that enabling errorprone would mean to use a different compiler, which means groovy files wouldn't compile.

Is there any way to use both in combination?

The maven config looks like this currently:

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<compilerId>groovy-eclipse-compiler</compilerId>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.groovy</groupId>
						<artifactId>groovy-eclipse-compiler</artifactId>
						<version>${groovy-eclipse-compiler.version}</version>
					</dependency>
					<dependency>
						<groupId>org.codehaus.groovy</groupId>
						<artifactId>groovy-eclipse-batch</artifactId>
						<version>${groovy-eclipse-batch.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.codehaus.groovy</groupId>
				<artifactId>groovy-eclipse-compiler</artifactId>
				<version>${groovy-eclipse-compiler.version}</version>
				<extensions>true</extensions>
			</plugin>

To make that clear, I don't mean that errorprone should check the Groovy code in any way. It should just check the Java code while allowing the Groovy tests to still work.

Is there any way to do this?

**Comment by nglorioso** [comment]
Looking at: https://stackoverflow.com/questions/1213897/different-maven-compiler-versions-for-test-and-main

It sounds like you can override the maven-compiler-plugin for the test compiler independently, by wrapping the test-specific configuration in an `<executions>`-level config.

I think you'd need both dependencies in the plugin, but just a different compilerId in either `configuration` stanza.

**Comment by J0s3f** [comment]
This sort of works.
This has the downside that not test code isn't checked using error-prone.

For people using Groovy in their projects (not only tests) this doesn't work at all, so a better solution would be appreciated.

**Comment by cushon** [comment]
This should be possible now with the `-Xplugin` integration documented in http://errorprone.info/docs/installation#maven.
