### ISSUE TITLE
[Question] Get type of instance object when using MethodInvocationTreeMatcher

### ISSUE THREAD

**Issue by zero-88** [google/error-prone#757]
Hi all,
I have a question about get type of instance object when using MethodInvocationTreeMatcher
For example: I have class A
```java
List<String> list = new ArrayList<>();
list .add("xx");
```
When writing new checker:
```java
public class NewChecker extends BugChecker implements MethodInvocationTreeMatcher {
    @Override
    public Description matchMethodInvocation(MethodInvocationTree tree, VisitorState state) {
        //How can I detect type of instance object in which method is called. 
        //In here, tree is list.add, and expected type is ArrayList
    }
}
```

I used 
```java
  Element method = TreeInfo.symbol((JCTree) expressionTree);
  TypeElement invokedClass = (TypeElement) method.getEnclosingElement();
```
But it always return List.
Anybody has hint or trick?
Thanks in advance,
Zero

**Comment by msridhar** [comment]
AFAIK ErrorProne / javac only gives you easy access to the declared types of variables.  You would have to perform your own extra analysis to determine that `list` is only assigned an `ArrayList` object.

**Comment by lowasser** [comment]
Yes, EP won't get you any better information -- because the _compiler_ doesn't keep any better information.  After all, it could be

    List<String> list = arbitrarilyComplicatedPieceOfCodeHere();
    list .add("xx");

**Comment by zero-88** [comment]
Thank guy.
I see the point. Because _compiler_ just compile .java to .class, so basically it keeps information as text file. We only access exact type of object in jvm. Only way is keep tracing a variable after initialize or assign value, but it will be huge effort.
For scenario: declaring interface instead of class and interface has many class implements then I just want to set a rule checker for specific child class. 
How ErrorProne handle this scenario? Does it have any case like that?
