### ISSUE TITLE
Check for boxed primitive type constructor usage.

### ISSUE THREAD

**Issue by NightlyNexus** [google/error-prone#760]
`new Integer(5)` is wasteful because `Integer.valueOf(5)` can pull from the cache.
Also, a check for `Boolean yes = true` or the like instead of `Boolean.TRUE` would be neat.

The only case I can think of for `new Boolean(true)` or `new Integer(5)` would be to avoid an equals, maybe?

**Comment by JakeWharton** [comment]
People do this for a lock object too. Definitely not recommended.

**Comment by eaftan** [comment]
We have http://errorprone.info/bugpattern/BoxedPrimitiveConstructor for this, and it should be on as a warning by default.

**Comment by NightlyNexus** [comment]
Ah, thank you. I'll bump that to an error in my project.
Sorry about missing that one!
