### ISSUE TITLE
LinkedList accessed through via index

### ISSUE THREAD

**Issue by zero-88** [google/error-prone#762]
java.util.LinkedList accessed through via index.
Reason: This is bad performance since random access via index on a linked list is O(n)
List methods to check:
- add(int i, Object obj)
- get(int i)
- remove(int i)
- set(int i, Object obj)

**Comment by zero-88** [comment]
@nglorioso @lowasser ping on this.
Please help me review this issue.
Thanks

**Comment by cushon** [comment]
Thanks for the PR, someone will take a look at this next week.

**Comment by cpovirk** [comment]
As @ronshapiro points out in #763, it's hard to identify that a `List` is a `LinkedList` unless that's its static type. You might get more bang for your buck for flagging all creations of `LinkedList`. My understand is that, unless you are doing something very strange, `LinkedList` is slower than `ArrayList`, `ArrayDeque`, or both.

**Comment by zero-88** [comment]
Hi @cpovirk @ronshapiro 
Sorry about checking for `matchInstanceOf` when initialize `LinkedList`. I intended to check define `LinkedList` by `List` interface. But it seems impossible.
Use `addFirst` instead of `myLinkedList.add(0, item)`, and similar with other methods: `remove`, `get`...
Because when using index with LinkedList, this class recomputes list item and make worst performance. You can see method in `LinkedList`:
```
/**
     * Returns the (non-null) Node at the specified element index.
     */
    Node<E> node(int index) {
        // assert isElementIndex(index);

        if (index < (size >> 1)) {
            Node<E> x = first;
            for (int i = 0; i < index; i++)
                x = x.next;
            return x;
        } else {
            Node<E> x = last;
            for (int i = size - 1; i > index; i--)
                x = x.prev;
            return x;
        }
    }
```
