### ISSUE TITLE
MissingCasesInEnumSwitch doc is not clear

### ISSUE THREAD

**Issue by stephanenicolas** [google/error-prone#770]
https://github.com/google/error-prone/blob/master/docs/bugpattern/MissingCasesInEnumSwitch.md

```java
switch (color) {
  case RED:
  case GREEN:
    paint(color);
    break;
}
```

The example contains 2 issues: there is no default close and it would make sense to have one, or add a case for the last enum value. But there is another issue : cases RED & GREEN are processed in the same way. 

The example could be better, it's hard to understand if 
* A) we should apply the `// fall out` comment to RED --> GREEN, which would make sense.
* B) we should apply when a default statement "absorbs" missing cases. Which is strange a bit. 

And finally, why do we need the `// fall out` comment when `default: break` would do.

**Comment by cushon** [comment]
> But there is another issue : cases RED & GREEN are processed in the same way.

The style guide doesn't requires a `// fall through` comment here, only between distinct 'statement groups': https://google.github.io/styleguide/javaguide.html#s4.8.4-switch

`default: break;` and `default: // fall out` are both OK, that's more of a matter of taste. The [MissingDefault](http://errorprone.info/bugpattern/MissingDefault) check suggests the comment, but it doesn't require it.

**Comment by stephanenicolas** [comment]
Thx for clarifying it.

2017-10-11 10:08 GMT-07:00 Liam Miller-Cushon <notifications@github.com>:
