### ISSUE TITLE
error-prone-javac is missing --release support

### ISSUE THREAD

**Issue by cushon** [google/error-prone#784]
The repackaged jar doesn't contain `META-INF/services/com.sun.tools.javac.platform.PlatformProvider`, which is needed for `--release` support. See https://github.com/tbroyer/gradle-errorprone-plugin/issues/52#issuecomment-337007077.

**Comment by tbroyer** [comment]
Fwiw (and I have absolutely no idea what impact it would have), it doesn't include the `module-info.class` either (which can also be used to declare services)

**Comment by cushon** [comment]
I think that's going to be harder to fix until we drop support for running on JDK 8, or unless we want to publish separate artifacts for 8 and 9.

**Comment by cushon** [comment]
This is fixed by fcbbd714958586a73389409f6bfa0557db557ed5.
