### ISSUE TITLE
Compile error:  incompatible types: inference variable E has incompatible equality constraints Foo,Object

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#803]
Error-Prone 2.1.2 fails to infer types correctly and produces the following error:
```
    [javac] Foo.java:8: error: incompatible types: inference variable E has incompatible equality constraints Foo,Object
    [javac]     return FluentIterable.from(
    [javac]                               ^
    [javac]   where E is a type-variable:
    [javac]     E extends Object declared in method <E>from(Iterable<E>)
```

The code is this:
```
import com.google.common.collect.FluentIterable;
import com.google.common.collect.ImmutableList;
import com.google.common.graph.Traverser;

public class Foo {

  public static FluentIterable<Foo> foo(Foo f) {
    return FluentIterable.from(
        Traverser.forTree(g -> ImmutableList.of(new Foo())).depthFirstPreOrder(f));
  }
}
```
`Foo` is obviously compatible with `Object`, so the error message about "incompatible types" seems wrong. The Eclipse Java Compiler compiles this code correctly. It works with error-prone if I write for example `(Foo g)` as lambda parameter.

**Comment by cushon** [comment]
> `Foo` is obviously compatible with `Object`

Not as a type argument of `Iterable` - `Iterable<Foo>` is not compatible with `Iterable<Object>`. Simpler example:

```java
  public static Iterable<Foo> foo(Foo f) {
    return Traverser.forTree(g -> ImmutableList.of(new Foo())).depthFirstPreOrder(f);
  }
```

```
Foo.java:7: error: incompatible types: Iterable<Object> cannot be converted to Iterable<Foo>
    return Traverser.forTree(g -> ImmutableList.of(new Foo())).depthFirstPreOrder(f);
                                                                                 ^
```

javac doesn't do target typing across chained method calls, so the return type of `foo` isn't considered when doing inference on `Traverser.forTree(g -> ImmutableList.of(new Foo()))`.

> The Eclipse Java Compiler compiles this code

Which version? With `4.6.1` I get:

```
1. ERROR in /tmp/tmp.eROzROCRRi/Foo.java (at line 8)
        return FluentIterable.from(
        Traverser.forTree(g -> ImmutableList.of(new Foo())).depthFirstPreOrder(f));
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Type mismatch: cannot convert from FluentIterable<Object> to FluentIterable<Foo>
```

**Comment by PhilippWendler** [comment]
I used ECJ 4.7.

I would still claim that the error message is wrong, because `Object` and `Foo` are compatible, just `Iterable<Object>` and `Iterable<Foo>` are incompatible, but this sounds like it is actually a javac problem and can't be fixed in error-prone?

**Comment by cushon** [comment]
It's interesting that ecj 4.7 has different behaviour than javac, that it isn't necessarily a javac bug. The JLS is the source of truth. And yes, this is javac behaviour rather than something in Error Prone. javac bugs can be reported to http://bugreport.java.com/.
