### ISSUE TITLE
False positive ConstructorLeaksThis when "this" is used only in last line of constructor

### ISSUE THREAD

**Issue by vorburger** [google/error-prone#809]
In order to [satify ConstructorLeaksThis](http://errorprone.info/bugpattern/ConstructorLeaksThis), I've just found myself having to turn this:

    private final ListenableFuture<V> guavaListenableFuture;

    public ListenableToCompletableFutureWrapper(ListenableFuture<V> guavaListenableFuture) {
        this.guavaListenableFuture = guavaListenableFuture;
        Futures.addCallback(guavaListenableFuture, this, MoreExecutors.directExecutor());
    }

into this:

    public static <T> CompletionStage<T> create(ListenableFuture<T> guavaListenableFuture) {
        ListenableToCompletableFutureWrapper<T> instance
            = new ListenableToCompletableFutureWrapper<>(guavaListenableFuture);
        Futures.addCallback(guavaListenableFuture, instance, MoreExecutors.directExecutor());
        return instance;
    }

    private final ListenableFuture<V> guavaListenableFuture;

    private ListenableToCompletableFutureWrapper(ListenableFuture<V> guavaListenableFuture) {
        this.guavaListenableFuture = guavaListenableFuture;
    }

but thought tthat this was a bit silly, and wonder if this isn't a false positive which in an ideal world could be auto detected and not raised by `ConstructorLeaksThis`... as the `this` was only used in the last line of the constructor, which was as method returning void which did not itself assign any (final) fields, it's guaranteed that at that exact point in time all final fields have already been initialized, right? So in reality in this specific case there's no real issues. Or am I missing something?

If this is asking for too much smarts :smile_cat: then feel free to just close, but thought worth bringing up.

**Comment by graememorgan** [comment]
I agree this is a good idea: it's a similar request to matching the behaviour of the checker framework w.r.t. @UnderInitialization objects.

However, it's a bit more subtle than just "last statement in constructor". Your class also has to be final, otherwise you might be calling out to an overridable method (or something which can access one) which sees uninitialised fields in the subclass.

**Comment by cushon** [comment]
98d25b520237aacb941bdf27ad4b73ffddacbb14
