### ISSUE TITLE
Alternatives to `javax.annotation.Generated` in JDK 9

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#811]
I'm filing this issue to bring your attention to the discussion in immutables/immutables#703. As Error Prone's (non-test) code only refers to `javax.annotation.Generated` [as a string](https://github.com/google/error-prone/blob/master/check_api/src/main/java/com/google/errorprone/SuppressionHelper.java#L102), it can trivially keep supporting this annotation. But reading the aforementioned thread, I ask:
* Should EP also support `javax.annotation.processing.Generated`? (I assume so.)
* Are there plans for a custom annotation that libraries such as Immutables could use?
* Would it perhaps not be easier to make the set of annotations that mark generated code configurable, through a compiler flag?

(I'm willing to work on a PR for this, provided consensus is reached.)

**Comment by cushon** [comment]
> Are there plans for a custom annotation that libraries such as Immutables could use?

Like another definition of `@Generated`? Code generators should be using the version of the annotation that's available at compile-time, maybe with a preference for the new one. We weren't planning to introduce another version of the annotation.

**Comment by arakelian** [comment]
@cushon Respectfully, please consider addition of javax.annotation.processing.Generated, which is the JDK9 method of marking a class as having been generated, as explained here in more detail: https://github.com/google/dagger/issues/880

**Comment by eaftan** [comment]
@arakelian We have no objection to supporting `javax.annotation.processing.Generated`, I'll take care of that.  Liam's objection is to adding more definitions of `@Generated` or providing a configurable set of annotations.

**Comment by arakelian** [comment]
@eaftan Thank you.
