### ISSUE TITLE
IntelliJ IDEA Plugin cast error

### ISSUE THREAD

**Issue by CookieAvenger** [google/error-prone#819]
I'm running IntelliJ IDEA 2017.2, just installed Error-prone Compiler Integration version 171.4342, set Javac with error-prone as my as the compiler to use, hit run on something simple and everytime I try to compile it just says;
Error:java: com.google.errorprone.ErrorProneJavaCompiler cannot be cast to java.compiler/javax.tools.JavaCompiler
Also worth mentioning, I'm running Ubuntu 16.04 and Oracle JDK 9.0.1

**Comment by mmoayyed** [comment]
Just noting here that the plugin seems not compatible with the latest 2017.3. I have opened up a jira with JetBrains.

**Comment by happy15** [comment]
I reproduced this by setting compiler to java 9. I am using 2017.3 community.
