### ISSUE TITLE
Checking equality of objects of different types

### ISSUE THREAD

**Issue by cushon** [google/error-prone#83]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=83) created by **eaftan@google.com** on 2013-02-11 at 09:53 PM_

---

For reference equality: If the two references are of different class types with no common subclasses, then this will always return false.

For equals(): This method calls equals() on two references of different class types with no common subclasses.  In this case, equals() will most likely return false.  Note that it is possible to define an equals() method that *does* return true when given an object of different types.

**Comment by eaftan** [comment]
This was fixed in 9544011b59ba13ab46d99f7bfdeadd1fa25389e7.
