### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin.

### ISSUE THREAD

**Issue by RNAi** [google/error-prone#830]
The following error was found when building a new target by bazel.
     error-prone version: 2.1.1
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.sun.jna.Structure not found

bazel version:
Build label: 0.7.0-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 09:12:48 2017 (1508404368)
Build timestamp: 1508404368
Build timestamp as int: 1508404368

**Comment by eaftan** [comment]
Can you share a repro?  Can you also try building with the bazel flag `--java_classpath=off`?

**Comment by cushon** [comment]
I suspect this is google/error-prone#827, especially if the flag @eaftan mentioned makes a difference.

**Comment by RNAi** [comment]
Thank you, I will try it with --java_classpath=off to see if it is gone, and, regarding the repro, let me see if I can sever the code to get a repro w/o leaking any sensitive info.

For google/error-prone#827, I am not sure I understand why it may be the same cause as mine as my java file is not a generated one, and the error message from both cases look different to me.

**Comment by cushon** [comment]
I wasn't thinking - the error messages are related and both issues affect Bazel, but the other one is windows-only.

**Comment by cushon** [comment]
@RNAi can you check if disabling FunctionalInterfaceClash with `-Xep:FunctionalInterfaceClash:OFF` makes a difference?

**Comment by RNAi** [comment]
Sorry for the late response.

It still complains about 'com.sun.jna.Structure not found' with --java_classpath=off.

bazel build --java_classpath=off //:target_name

error: An unhandled exception was thrown by the Error Prone static analysis plugin.

     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.1.1
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.sun.jna.Structure not found
