### ISSUE TITLE
Error with SuggestedFix.replace

### ISSUE THREAD

**Issue by mkruber** [google/error-prone#852]
Assume the following code: 

```
if(some condition) {
    x = something.blah(new foo() {
               @Override
                public void bar(...) { .... }
               ....
}
else {

}
```

By matching using matchIf(IfTree ifTree, VisitorState visitorState), if I do a SuggestedFix.replace(ifTree) with its body, I get the following: 

```
  x = something.blah(new foo() {
               () {
                   super();
               }

               @Override
                public void bar(...) { .... }
               ....
```

The nameless constructor obviously causes a compiler error. It seems like a bug to me.

**Comment by nglorioso** [comment]
Can you use visistorState.getSourceForNode(tree.getThenStatement()) as the replacement text instead of tree.getThenStatement().toString()? That should avoid the behavior you see now.

**Comment by nglorioso** [comment]
Namely,` tree.toString()` pretty-prints the AST, which also removes any block/line comments, while `getSourceForNode` will re-read the source from the right position and put it in as-is.

**Comment by mkruber** [comment]
Thanks. I think that may fix the issue. Let me try it and I will update here.

**Comment by Stephan202** [comment]
(`tree.toString()` also causes expressions of the form `"foo" + "bar"` to be rendered as `"foobar"`, which may not be what you want in case of long wrapped strings.)

**Comment by mkruber** [comment]
Yes, this works though it adds an extra paranthesis. I think the ASTUtils.stripParantheses can be used to handle it. Thanks for the quick response!
