### ISSUE TITLE
Handling javadoc

### ISSUE THREAD

**Issue by mkruber** [google/error-prone#853]
I am building an analysis to delete a given set of methods and all the details for the method (modifiers, annotations, etc) are conveniently available from the AST node. 
However, I also want to ensure that there are no dangling javadoc comments and want to remove the comment corresponding to each method that is deleted. 

Is there a way to get the node corresponding to the javadoc comment for a method? This node can then be deleted using SuggestedFix.delete(...). I have access to the (MethodTree tree, Symbol sym, Context context) from RefasterScanner.java

**Comment by epmjohnston** [comment]
Here's an example of getting a javadoc DCTree node from its JCTree https://github.com/google/error-prone/blob/49eabf7fcf36bcfe46c7a2abb6132da06ab36863/core/src/test/java/com/google/errorprone/fixes/SuggestedFixesTest.java#L649

**Comment by mkruber** [comment]
Thanks. I will look into using the state object then.
