### ISSUE TITLE
Incompatibility between Parceler and Error Prone

### ISSUE THREAD

**Issue by tspoke** [google/error-prone#857]
Hi,

I run into a bug yesterday using NullAway library and my project. I as not able to make ErrorProne and Parceler work together.

It looks like the bug comes from Error Prone, not NullAway.

The original issue, and links to repositories to test, can be found here : [https://github.com/uber/NullAway/issues/72](https://github.com/uber/NullAway/issues/72)

Thank you.

**Comment by cushon** [comment]
Hello, sorry this didn't get a response when it was reported.

If you're still seeing this with the latest versions of Error Prone and the [gradle plugin](https://github.com/tbroyer/gradle-errorprone-plugin)?
