### ISSUE TITLE
Project will not compile without transitive dependency exclusion when I believe it should.

### ISSUE THREAD

**Issue by andrewparmet** [google/error-prone#864]
I originally filed this issue with Gradle (https://github.com/gradle/gradle/issues/3817) but I actually think it belongs here, as it only happens when I try to include error-prone core.

When I try to include error-prone in a project that itself uses a more recent version of Guava, I seem to be forced into the version of Guava that error-prone uses (i.e., the method I call appears to not exist).

I have a minimal working example of a single Java file and build.gradle:
```java
import com.google.common.base.Throwables;

public class Main {
    public static void main(String... args) {
        Throwables.throwIfInstanceOf(new Exception(), RuntimeException.class);
    }
}
```

```
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.google.guava:guava:23.5-jre'
    compileOnly('com.google.errorprone:error_prone_core:2.0.5') {
        exclude group: 'com.google.guava'
    }
}
```

The output I get from `./gradlew compileJava` is: 
```
$ ./gradlew compileJava

> Task :compileJava FAILED
<...>/test-gradle-transitive-dependencies/src/main/java/Main.java:6: error: cannot find symbol
        Throwables.throwIfInstanceOf(new Exception(), RuntimeException.class);
                  ^
  symbol:   method throwIfInstanceOf(Exception,Class<RuntimeException>)
  location: class Throwables
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

The project can be found here: https://github.com/andrewparmet/test-gradle-transitive-dependencies

If I comment out the `exclude group` line compilation fails. I also tried to use a resolution strategy to force versions of the Guava module to version 23.5-jre but this also failed. I include the `build.gradle` file I used with this attempt as `build.gradle.alt`. 

This problem did not occur on Gradle 3.5 or 3.5.1, and first occurs in version 4.0.

I appreciate any insight into why this is going wrong.

**Comment by jbduncan** [comment]
Hi @andrewparmet. I find that error-prone doesn't exhibit this behaviour if I follow the Gradle-specific installation instructions [here](http://errorprone.info/docs/installation) and use the [gradle-errorprone-plugin](https://github.com/tbroyer/gradle-errorprone-plugin), import it into my `build.gradle` as described in https://plugins.gradle.org/plugin/net.ltgt.errorprone, and then use an `errorprone` dependency on error-prone instead of a `compileOnly` one, as shown in this [official example](https://github.com/google/error-prone/blob/master/examples/gradle/build.gradle).

It's my hope that if you try the method above, it will solve your problem. :)

**Comment by jbduncan** [comment]
But as to why using `compileOnly` instead of the error-prone plugin's `errorprone` causes this weird dependency problem, I have no clue.

@tbroyer, @cushon, I wonder if you have any insight on this?

**Comment by andrewparmet** [comment]
@jbduncan Ah - so in my actual project I do use the Gradle error-prone plugin as given in that example, but I _also_ have a `compileOnly` dependency on error-prone core. Removing the `compileOnly` dependency altogether fixes the issue. Thanks!

**Comment by jbduncan** [comment]
@andrewparmet You're very welcome!

Hrm, I do hope that @tbroyer, @cushon or someone on the Gradle team over at https://github.com/gradle/gradle/issues/3817 can provide some insight on why importing error-prone with `compileOnly` causes this strange problem with forcing the Guava version to the version that error-prone uses. :/

**Comment by tbroyer** [comment]
From your MCVE, this definitely looks like a Gradle issue.

You could try running `./gradlew compileJava --debug` and look at the compile classpath; or even just `./gradlew dependencies --configuration=compileClasspath`.

**Comment by andrewparmet** [comment]
Here's the output of `./gradlew dependencies --configuration=compileClasspath`. As expected I get this line under error-prone core: `com.google.guava:guava:18.0 -> 23.5-jre (*)`.

```$ ./gradlew dependencies --configuration=compileClasspath

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

compileClasspath - Compile classpath for source set 'main'.
+--- com.google.guava:guava:23.5-jre
|    +--- com.google.code.findbugs:jsr305:1.3.9 -> 3.0.0
|    +--- org.checkerframework:checker-qual:2.0.0
|    +--- com.google.errorprone:error_prone_annotations:2.0.18
|    +--- com.google.j2objc:j2objc-annotations:1.1
|    \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
\--- com.google.errorprone:error_prone_core:2.0.5
     +--- com.google.errorprone:error_prone_annotation:2.0.5
     +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
     +--- org.pcollections:pcollections:2.1.2
     +--- com.google.guava:guava:18.0 -> 23.5-jre (*)
     +--- com.google.code.findbugs:jFormatString:3.0.0
     +--- com.google.code.findbugs:jsr305:3.0.0
     +--- org.checkerframework:dataflow:1.8.10
     |    \--- org.checkerframework:javacutil:1.8.10
     +--- com.google.errorprone:javac:1.9.0-dev-r2644-1
     \--- com.google.errorprone:error_prone_annotations:2.0.5 -> 2.0.18

(*) - dependencies omitted (listed previously)


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed```

Thanks for your response - we'll see if the folks at Gradle have any insights.
