### ISSUE TITLE
proposed new check: String.split with only one argument

### ISSUE THREAD

**Issue by novalis** [google/error-prone#867]
Consider the code at 
https://github.com/google/error-prone/blob/92254ee562f449c3aef387949094221b1ff8c0d1/check_api/src/main/java/com/google/errorprone/ErrorProneOptions.java#L241

If you pass -Xep:: (two colons) to that function, you'll get an ArrayIndexOutOfBoundsException. 

This is because String.split has a funny behavior inherited from Perl (see http://konigsberg.blogspot.com/2009/11/final-thoughts-java-puzzler-splitting.html ) 

I think String.split should only ever be called with two arguments (e.g. (arg, -1)), to prevent this gotcha.

**Comment by jbduncan** [comment]
Just throwing in my 2 cents, but how about requiring that `com.google.common.base.Splitter` from Guava be used instead if it's available on the classpath or module path? (For those not in the know, `Splitter` fixes much if not all of the behaviour quirks that `String.split` has.)

**Comment by novalis** [comment]
That would be fine too.

**Comment by cushon** [comment]
Thanks for the report, that is a good puzzler.

I'm not sure this meets the "small but noticeable frequency" critera from http://errorprone.info/docs/criteria, though. `String.split(String)` is a very widely used method, which may suggest this doesn't cause a lot of problems in practice.

**Comment by novalis** [comment]
Out of the three instances in this very codebase, one was bad.  I learned about this issue because a colleague pointed out that it might bite some of my code.  I don't know how to do a larger-scale check without manually checking a lot of cases. Also, it's easy to autofix, and somewhat hard to audit ("oh, but this case is OK because the calling method, three layers up, ensures that something other than the delimiter is present").  

I'm not sure what cases even count as bugs.  For example, we have the following code somewhere in our codebase:
String[] lines = fileContents.split("\n");
doSomething(lines[0]);

We expect, I guess, that fileContents is in some reasonable format.  Perhaps we even do the atomic file write thing to ensure it (I have no idea -- I found this code randomly through code search, and I don't even know if fileContents really comes from a file).  Is that any worse than if we said doSomething(lines[3])?  Maybe nobody would write that without checking, and if they did, nobody would be confused to see an AIOOBE?  But folks would be surprise in the doSomething(lines[0]) case.

I agree that the ratio of bugs to occurrences is not likely to be 1/3 in general.  But since it's autofixable, I don't think it's a big deal to get it right.

**Comment by cushon** [comment]
I agree that avoiding `split(String)` is probably a good idea.

I was thinking mostly about whether we want to enable this check by default, since it's going to be fairly noisy as a warning.

For fixes, `split(arg, -1)` is a little unfortunate, and we can't be certain that was actually the intent. Migrating to `Splitter` isn't a good drop-in replacement if the code needs an array, and it also changes semantics.

**Comment by novalis** [comment]
We can't be certain about the intent -- maybe someone really did want an AIOOBE!  But that seems pretty unlikely.  Is there something else I'm missing?

Splitter is not only not a drop-in replacement, but it's also not universally available.

I guess I don't care if it's enabled by default as long as I can enable it (which, since I can edit my company's -Xep, I presumbly can).

**Comment by cushon** [comment]
>  Is there something else I'm missing?

I don't think so, I'm just thinking through how we'll want to use the check internally.

Adding it to Error Prone (probably disabled by default, at first) SGTM.

**Comment by cushon** [comment]
The PR was merged as 37ee5440d0d062cd308b4d1caeb4acd2f05a6b8b. I also added a refactoring that can migrate common uses of `String.split` to `Splitter`: 25ea27d4ecaffb9a0cf9f46ca30f82ca9df937bc
