### ISSUE TITLE
2.1.0 no more supports encodings other than UTF-8

### ISSUE THREAD

**Issue by lasselindqvist** [google/error-prone#873]
Example command line:
java -Xbootclasspath/p:error_prone_ant-2.1.0.jar com.google.errorprone.ErrorProneCompiler Constants.java

Below is an example of an ANSI file which produces an error with version 2.1.0 but not with 2.0.9.
...
package com.constants;

/**
 * Mikäli
 */
public class Constants {	
	public final static String SALA = "SALA";
	public final static String SÄLÄ = "SÄLÄ";
	public final static String SÄLÄ = "SALA";
	public final static String SALA = "SÄLÄ";
}
...

Constants.java:4: error: unmappable character (0xE4) for encoding UTF-8
 * Mik?li
      ^
Constants.java:8: error: unmappable character (0xC4) for encoding UTF-8
        public final static String S?L? = "S?L?";
                                    ^
Constants.java:8: error: unmappable character (0xC4) for encoding UTF-8
        public final static String S?L? = "S?L?";
                                      ^
Constants.java:8: error: unmappable character (0xC4) for encoding UTF-8
        public final static String S?L? = "S?L?";
                                            ^
Constants.java:8: error: unmappable character (0xC4) for encoding UTF-8
        public final static String S?L? = "S?L?";
                                              ^
Constants.java:9: error: unmappable character (0xC4) for encoding UTF-8
        public final static String S?L? = "SALA";
                                    ^
Constants.java:9: error: unmappable character (0xC4) for encoding UTF-8
        public final static String S?L? = "SALA";
                                      ^
Constants.java:10: error: unmappable character (0xC4) for encoding UTF-8
        public final static String SALA = "S?L?";
                                            ^
Constants.java:10: error: unmappable character (0xC4) for encoding UTF-8
        public final static String SALA = "S?L?";
                                              ^
Constants.java:8: error: illegal character: '\ufffd'
        public final static String S?L? = "S?L?";
                                    ^
Constants.java:8: error: illegal character: '\ufffd'
        public final static String S?L? = "S?L?";
                                      ^
Constants.java:9: error: illegal character: '\ufffd'
        public final static String S?L? = "SALA";
                                    ^
Constants.java:9: error: illegal character: '\ufffd'
        public final static String S?L? = "SALA";
                                      ^
4 errors

**Comment by lasselindqvist** [comment]
According to https://github.com/google/error-prone/pull/681/files and http://errorprone.info/docs/installation it would seem that the problem can be circumvented only with JDK 9

**Comment by cushon** [comment]
`com.google.errorprone.ErrorProneCompiler` has been replaced by the `-Xplugin:` integration documented at http://errorprone.info/docs/installation, which shouldn't have this problem: it supports whatever `-encoding` options `javac` does.
