### ISSUE TITLE
Problematic Vector warning

### ISSUE THREAD

**Issue by RoiEXLab** [google/error-prone#879]
I just found a case where the JdkObsolete warning can't be fixed (just supressed),  using the java standard library:
Imagine the following code:
```
public static <T> JComboBox<T> createCombobox(List<T> list){
  return new JComboBox<>(new Vector<>(list));
}
```
`list.toArray(new T[list.size()])` can't be used here, because generic are not available at runtime, and there's really no other way of fixing this I can think of.
My suggestion would be to not generate a warning, when the object is used in a Swing Component.
Thoughts?

**Comment by Maaartinus** [comment]
I guess, you can use `new JComboBox<>((T[]) list.toArray()));` which is an unsafe cast which won't throw for the very same reason. I'm not saying this is any better than using `Vector`, especially because the array gets converted to a `Vector` anyway. It's actually worse.

**Comment by RoiEXLab** [comment]
I'm not sure if array casting works that way.
The compiler accepts it, but too often this resulted in a classcastexception

**Comment by Maaartinus** [comment]
Unlike collections, array have a runtime-type, so a `ClassCastException` could occur, when assigning `E[] a = (E[]) someObjectArray`, where `E` isn't erased. In this case, I'm rather sure it doesn't happen, but anyway: An unchecked cast is a bad idea and on the second though, I'm surely *not* recommending my workaround.

**Comment by trejkaz** [comment]
We fixed that particular problem (years ago, before Error Prone existed ;) ) by making a new implementation of `ComboBoxModel` based on `List` to replace `DefaultComboBoxModel` which to this day is still based on `Vector`.

**Comment by cushon** [comment]
This is working as intended--it's understood that sometimes it's not possible to fix an API that uses a type flagged by `JdkObsolete`, and the recommendation is to use `@SuppressWarnings` in that case. (Or create a wrapper for the type so you only have to suppress it once in the implementation of that wrapper, as @trejkaz suggested.)
