### ISSUE TITLE
bugpattern web documention has bad layout

### ISSUE THREAD

**Issue by vorburger** [google/error-prone#890]
On e.g. http://errorprone.info/bugpattern/ReturnMissingNullable the layout is messed up, see screenshot below.

Perhaps something not right perhaps due to `java {.good}` (just a guess) ? The sources on both https://github.com/google/error-prone/blob/master/docs/bugpattern/ReturnMissingNullable.md as well as https://github.com/google/error-prone/blob/gh-pages/bugpattern/ReturnMissingNullable.md render find by GitHub though (see 2nd screenshot), so ... not sure what's going on here - is this perhaps some subtle [bug in Jekyll](https://jekyllrb.com)?!

Screenshot of bad layout on http://errorprone.info/bugpattern/ReturnMissingNullable site:

![error-prone-bugpattern-bad-layout](https://user-images.githubusercontent.com/298598/34673761-b88941ac-f483-11e7-8919-d2c20a3a63b3.png)

Screenshot of good layout in source on https://github.com/google/error-prone/blob/master/docs/bugpattern/ReturnMissingNullable.md:

![screenshot from 2018-01-08 14-57-03](https://user-images.githubusercontent.com/298598/34673919-3a11c654-f484-11e7-9a3f-2b2555a093f9.png)

**Comment by epmjohnston** [comment]
Documentation template has been updated to include new fields, exclude deprecated fields, and skip empty fields as of 7c182eb54ea92294ac0314d1af30f54b96a9593c

<img width="312" alt="screen shot 2018-01-30 at 10 13 52 am" src="https://user-images.githubusercontent.com/8797239/35583299-58a4ddee-05a6-11e8-8b73-b9028becc5fa.png">

**Comment by vorburger** [comment]
@epmjohnston thanks! But http://errorprone.info/bugpattern/ReturnMissingNullable is still looking NOK (as in screenshot above) - perhaps this needs something to be re-run to re-publish, or something? Do you want to re-open this issue until it's good?
