### ISSUE TITLE
trigger through command line with classpaths will generate .class file

### ISSUE THREAD

**Issue by jdneo** [google/error-prone#894]
### What version of Error Prone are you using?
error_prone_ant-2.2.0.jar

### Does this issue reproduce with the latest release?
yes

### What did you do?
I trigger the error prone through command, it's something like:

```
java -Xbootclasspath/p:error_prone_ant-2.2.0.jar com.google.errorprone.ErrorProneCompiler ${source file} -cp ${classpaths}
```

Then this command will give me the detection result, meanwhile, it will generate `*.class` file at the same directory of the source file.

Is there any mis-uses in this command? Or Can I disable it from generating the `.class` file?

Thanks.

**Comment by eaftan** [comment]
Error Prone is intended to replace your compiler, so that it can break builds when it detects problems with your code.  If you don't want to use it as a compiler, you can just discard the .class file outputs.

**Comment by jdneo** [comment]
Hi @eaftan , I am currently using error prone to detect potential bugs in the java code. It's ok for me to ignore the .class file.  but it will be better I can prevent error prone from generating the class file, may I ask is there any command line flag to achieve that?

**Comment by eaftan** [comment]
No, I'm sorry.  Our intent is to be a compiler replacement for easy integration and performance.

**Comment by msridhar** [comment]
You can use the javac `-d` option to dump the class files to `/tmp` or a temporary directory you create

**Comment by jdneo** [comment]
Thank you @eaftan @msridhar , I like this tool and the `-d` option can be a good work-around for me.
