### ISSUE TITLE
Detect collections using double brace initialization

### ISSUE THREAD

**Issue by gaul** [google/error-prone#914]
Some call sites construct collections via double brace initialization:

```java
new HashSet<String>() {{ add("NU"); add("TK"); add("NC"); add("AC"); }};
```

error-prone should recommend the more succinct and efficient:

```java
new HashSet<String>(Arrays.asList("NU", "TK", "NC", "AC"));
```

The former creates an anonymous inner class and an implicit this reference which can prolong the outer class lifetime:

https://blog.nishtahir.com/2015/09/27/why-you-shouldnt-use-the-double-brace-initializer/

**Comment by JakeWharton** [comment]
Or suggest Set.of, List.of, or Map.of in about 45 days when Java 10 is out.

**Comment by JakeWharton** [comment]
Oops that's in Java 9!

**Comment by jbduncan** [comment]
Or even Guava's `Immutable*` collections?
