### ISSUE TITLE
AssertionFailureIgnored reports cases where error is caught to add more info

### ISSUE THREAD

**Issue by trejkaz** [google/error-prone#918]
Currently using:
* Error-prone 2.2.0

There are two common patterns in our test code.

1:

    try {
        doSomething();
    } catch (AssertionError e) {
        logger.info("detailed info about what happened");
        throw e;
    }

2:

    try {
        doSomething();
    } catch (AssertionError e) {
        throw new AssertionError("more info", e);
    }

Both of these currently get reported as `AssertionFailureIgnored`, but I wouldn't really say that either of these patterns are ignoring the exception.

For the first example, there could be an argument that logging the additional info could cause another exception to be thrown, which would mask the original. That's fair enough, and there is an easy workaround where you move the additional info dump into the `finally` block.

For the second example, we want to include the original exception in the one we throw, so we have no choice but to put it in the catch.

I think that both of these should be considered "good" examples, but if there is a good reason why they should remain as bad, a suitable workaround suggestion would really help. :)

**Comment by cushon** [comment]
e96741693d5242f802966bbfe1348a1dd0f77f1d
