### ISSUE TITLE
Validate annotations that use @RequiredModifiers or @IncompatibleModifiers

### ISSUE THREAD

**Issue by cushon** [google/error-prone#93]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=93) created by **kevinb@google.com** on 2013-02-25 at 06:59 PM_

---

Some annotations are misused when applied to the wrong "kinds" of program elements; this is why annotations can be restricted to only classes, or only methods, etc. But some annotations only make sense for certain kinds of methods, for example based on modifiers.

We use two experimental annotations called @﻿RequiredModifiers and @﻿IncompatibleModifiers. For example, if a particular annotation only makes sense to be applied to a static method, we annotate that annotation with @﻿RequiredModifiers(STATIC). If it only makes sense for an overrideable method, we use @﻿IncompatibleModifiers({PRIVATE, STATIC, FINAL}), etc.

If error-prone could enforce these attributes, it can help the user annotations in question to be used correctly more often and with less head-scratching later.

I am not necessarily claiming this should be high priority or huge value, but I wanted to capture the request. We certainly wouldn't want to proceed with open-sourcing our custom home-brewed checker.

**Comment by cushon** [comment]
We're in the process of creating a separate error-prone package for annotations, so we should be able to open-source the checks soon.

**Comment by Stephan202** [comment]
@cushon, is there a specific ticket that tracks the work on this annotation package? I assume such a package will contain the annotations mentioned in this issue and in #276 / #279.

If possible, I'd like for you to consider another annotation, namely `@EverythingIsNonnullByDefault` as defined in [this SO answer](http://stackoverflow.com/a/13429092/74939) or variations thereof, such as `@ReturnTypesAreNonnullByDefault` and `@FieldsAreNonnullByDefault`, as defined in [this SO answer](http://stackoverflow.com/a/11807961/74939). It would do away with the need for everybody to re-implement/redefine these annotations themselves. (I used these in several internal projects, and based on the SO answers it's not uncommon for other to do, too.)

If you think another project would be more suited to provide such annotations (the Checker Framework, perhaps?), let me know. If desired I can open a separate issue for this.

**Comment by cushon** [comment]
@Stephan202 - initially the package is only going to contain annotations that error-prone can enforce the semantics of. Error-prone doesn't currently check nullness annotations, so we probably won't add the annotations you suggest until we can actually analyze them. I created #280 to track your suggestion.

The Checker Framework might be a better home, but their analysis already assumes fields, parameters, and return types are non-null.

**Comment by cushon** [comment]
Fixed in 792f43fbcb7e999c9e9b815346d90685ab1c2e0f
