### ISSUE TITLE
Output on maven plugin should not go directly to stderr but it should go along with maven

### ISSUE THREAD

**Issue by iemejia** [google/error-prone#935]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?
2.2.0

### Does this issue reproduce with the latest release?
Yes

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete small program is good.

Run the maven plugin with some code with errors and redirected the output just to discover that the output file has only the output of maven but not the one of error-prone
`mvn clean verify -Perrorprone > errorprone.log`

### What did you expect to see?
The file should have the text of the output of the maven execution with the error prone output.

### What did you see instead?
The errorprone output is printed in the terminal and the file has the maven only  output.

**Comment by cushon** [comment]
The Error Prone output should go to the same location as other output from javac.

Please let us know if you're still having issues with the latest version of Error Prone and the `-Xplugin:` integration.
