### ISSUE TITLE
Find instantiations of HashMap<SomeEnum> and HashSet<SomeEnum>

### ISSUE THREAD

**Issue by gaul** [google/error-prone#940]
`EnumMap<SomeEnum>` is usually and `EnumSet<SomeEnum>` is always more efficient than more general hashed alternatives.  error-prone could trigger on instantiations of these collections.

**Comment by lowasser** [comment]
This is already covered in Google's (separate) best practices analysis, which we are in the process of open sourcing.  Error Prone is intended to address probable errors and correctness issues, not optimizations.

**Comment by gaul** [comment]
Could you share more about these best practice analyses and their timeline?  I found some references to Klippy from 2016 and further hints in #649.  I have an interest in these kinds of microoptimizations on Android.

**Comment by eaftan** [comment]
#649 is the canonical issue for open sourcing our best practices patterns.
