### ISSUE TITLE
false+ in IdentityBinaryExpression

### ISSUE THREAD

**Issue by grandinj** [google/error-prone#945]
## What version of Error Prone are you using?
2.2.0

Warning message is:

C:\Users\noel\Documents\GitHub\h2database-noel\h2\src\main\org\h2\table\TableLink.java:124: error: [IdentityBinaryExpression] A binary expression where both operands are the same is usually incorrect; the value of this expression is equivalent to `rs.next()`.
        if (rs.next() && rs.next()) {
                      ^
    (see http://errorprone.info/bugpattern/IdentityBinaryExpression)
1 error

Code looks like:
        ResultSet rs = meta.getTables(null, originalSchema, originalTable, null);
        if (rs.next() && rs.next()) {
            throw DbException.get(ErrorCode.SCHEMA_NAME_MUST_MATCH, originalTable);
        }

Probably ResultSet::next should be treated like Iterator next method

**Comment by cushon** [comment]
I agree this is a false positive, thanks for the bug.

One work-around is to refactor that to move some of the side-effects out of the binary expression, which may make it clearer to the reader that there are side-effects and checking the value twice is deliberate. E.g.:

```
boolean hasNext = rs.next();
if (hasNext && rs.next()) {
  // ...
}
```
