### ISSUE TITLE
CompletionFailure causes the compiler to crash

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#978]
This is with Error Prone 2.2.0 / master.  It seems from [this code](https://github.com/google/error-prone/blob/v2.2.0/check_api/src/main/java/com/google/errorprone/ErrorProneAnalyzer.java#L159) that there is an intention that if an EP check causes a `CompletionFailure` that the javac compilation shouldn't crash.  But [`handleError` in `ErrorProneScanner`](https://github.com/google/error-prone/blob/a612236eb0599f2fe2b0c201be8447c5990ec12e/check_api/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java#L1192) takes any `Throwable` and wraps it as an `ErrorProneError`, which prevents the first catch block from running if an Error Prone check causes the `CompletionFailure`.  Not clear what "should" happen here, but if the intention is to not crash on `CompletionFailure`s then that is not what is happening currently.

**Comment by cushon** [comment]
This was fixed in 2.3.2: https://github.com/google/error-prone/commit/819e1ed5e171b1567cd6a5a6bac389dc2b37bebc#diff-f2090e6faa88c20d0b7ed5618965faacae1e5aac95e7ef89a8dc9cfe414ff197R1197-R1199
