### ISSUE TITLE
HTTP/1.1 404 Not Found - http://errorprone.info/bugpattern/SimpleDateFormatConstant

### ISSUE THREAD

**Issue by jaredsburrows** [google/error-prone#993]
It looks like there is HTML page for `SimpleDateFormatConstant`

**Comment by eaftan** [comment]
We renamed that check in 4796400185cdb99b90599f61a3b006e5ebfd3769, so the doc tooling removed the markdown.

As a workaround, please refer to http://errorprone.info/bugpattern/DateFormatConstant.  

I'll also investigate modifying the doc updater to keep docs for deleted checks.
